// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newGateEntry(db *gorm.DB, opts ...gen.DOOption) gateEntry {
	_gateEntry := gateEntry{}

	_gateEntry.gateEntryDo.UseDB(db, opts...)
	_gateEntry.gateEntryDo.UseModel(&models.GateEntry{})

	tableName := _gateEntry.gateEntryDo.TableName()
	_gateEntry.ALL = field.NewAsterisk(tableName)
	_gateEntry.DocumentNo = field.NewString(tableName, "document_number")
	_gateEntry.TokenId = field.NewString(tableName, "token_id")
	_gateEntry.LoadingSlipNo = field.NewString(tableName, "loading_slip_no")
	_gateEntry.VehicleNo = field.NewString(tableName, "vehicle_number")
	_gateEntry.DriverName = field.NewString(tableName, "driver_name")
	_gateEntry.DriverMobile = field.NewString(tableName, "driver_mobile")
	_gateEntry.Purpose = field.NewString(tableName, "purpose")
	_gateEntry.EntryDate = field.NewString(tableName, "entry_date")
	_gateEntry.EntryTime = field.NewString(tableName, "entry_time")
	_gateEntry.ExitDate = field.NewString(tableName, "exit_date")
	_gateEntry.ExitTime = field.NewString(tableName, "exit_time")
	_gateEntry.GateUser = field.NewInt(tableName, "gate_user")
	_gateEntry.ThulokataEntry = field.NewInt(tableName, "thulokata_entry")
	_gateEntry.ScrapEntry = field.NewInt(tableName, "scrap_entry")
	_gateEntry.Scrap = gateEntryHasOneScrap{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Scrap", "models.Scrap"),
		Vendor: struct {
			field.RelationField
			Scraps struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Scrap.Vendor", "models.Vendors"),
			Scraps: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Scrap.Vendor.Scraps", "models.Scrap"),
			},
		},
		GateEntry: struct {
			field.RelationField
			QualityReport struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}
			Scrap struct {
				field.RelationField
			}
			Thulokata struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			LoadingEntry struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Sanokatas struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}
			SHooks struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Scrap.GateEntry", "models.GateEntry"),
			QualityReport: struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Scrap.GateEntry.QualityReport", "models.QualityReport"),
				Agent: struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.QualityReport.Agent", "models.Agent"),
					QualityReports: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scrap.GateEntry.QualityReport.Agent.QualityReports", "models.QualityReport"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.QualityReport.GateEntry", "models.GateEntry"),
				},
				Details: struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.QualityReport.Details", "models.QualityReportDetails"),
					ScrapTypeInfo: struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Scrap.GateEntry.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
						Details: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Scrap.GateEntry.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
						},
					},
					Report: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scrap.GateEntry.QualityReport.Details.Report", "models.QualityReport"),
					},
				},
			},
			Scrap: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Scrap.GateEntry.Scrap", "models.Scrap"),
			},
			Thulokata: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scrap.GateEntry.Thulokata", "models.Thulokata"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.Thulokata.GateEntry", "models.GateEntry"),
				},
				Loadings: struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.Thulokata.Loadings", "models.ThulokataLoading"),
					Thulokata: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scrap.GateEntry.Thulokata.Loadings.Thulokata", "models.Thulokata"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.Thulokata.GateEntries", "models.GateEntry"),
				},
			},
			LoadingEntry: struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scrap.GateEntry.LoadingEntry", "models.LoadingEntry"),
				Details: struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.LoadingEntry.Details", "models.LoadingEntryDetails"),
					LoadingEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scrap.GateEntry.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.LoadingEntry.GateEntries", "models.GateEntry"),
				},
			},
			Sanokatas: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scrap.GateEntry.Sanokatas", "models.Sanokata"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.Sanokatas.User", "models.User"),
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.Sanokatas.GateEntry", "models.GateEntry"),
				},
			},
			SHooks: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scrap.GateEntry.SHooks", "models.SHook"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntry.SHooks.GateEntry", "models.GateEntry"),
				},
			},
		},
		MultiUnloads: struct {
			field.RelationField
			Scrap struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Scrap.MultiUnloads", "models.ScrapMultiUnload"),
			Scrap: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Scrap.MultiUnloads.Scrap", "models.Scrap"),
			},
		},
		GateEntries: struct {
			field.RelationField
			QualityReport struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}
			Scrap struct {
				field.RelationField
			}
			Thulokata struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			LoadingEntry struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Sanokatas struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}
			SHooks struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Scrap.GateEntries", "models.GateEntry"),
			QualityReport: struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Scrap.GateEntries.QualityReport", "models.QualityReport"),
				Agent: struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.QualityReport.Agent", "models.Agent"),
					QualityReports: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scrap.GateEntries.QualityReport.Agent.QualityReports", "models.QualityReport"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.QualityReport.GateEntry", "models.GateEntry"),
				},
				Details: struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.QualityReport.Details", "models.QualityReportDetails"),
					ScrapTypeInfo: struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Scrap.GateEntries.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
						Details: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Scrap.GateEntries.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
						},
					},
					Report: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scrap.GateEntries.QualityReport.Details.Report", "models.QualityReport"),
					},
				},
			},
			Scrap: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Scrap.GateEntries.Scrap", "models.Scrap"),
			},
			Thulokata: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scrap.GateEntries.Thulokata", "models.Thulokata"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.Thulokata.GateEntry", "models.GateEntry"),
				},
				Loadings: struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.Thulokata.Loadings", "models.ThulokataLoading"),
					Thulokata: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scrap.GateEntries.Thulokata.Loadings.Thulokata", "models.Thulokata"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.Thulokata.GateEntries", "models.GateEntry"),
				},
			},
			LoadingEntry: struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scrap.GateEntries.LoadingEntry", "models.LoadingEntry"),
				Details: struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.LoadingEntry.Details", "models.LoadingEntryDetails"),
					LoadingEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scrap.GateEntries.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.LoadingEntry.GateEntries", "models.GateEntry"),
				},
			},
			Sanokatas: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scrap.GateEntries.Sanokatas", "models.Sanokata"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.Sanokatas.User", "models.User"),
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.Sanokatas.GateEntry", "models.GateEntry"),
				},
			},
			SHooks: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scrap.GateEntries.SHooks", "models.SHook"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scrap.GateEntries.SHooks.GateEntry", "models.GateEntry"),
				},
			},
		},
	}

	_gateEntry.Thulokata = gateEntryHasOneThulokata{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Thulokata", "models.Thulokata"),
		GateEntry: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Thulokata.GateEntry", "models.GateEntry"),
		},
		Loadings: struct {
			field.RelationField
			Thulokata struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Thulokata.Loadings", "models.ThulokataLoading"),
			Thulokata: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Thulokata.Loadings.Thulokata", "models.Thulokata"),
			},
		},
		GateEntries: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Thulokata.GateEntries", "models.GateEntry"),
		},
	}

	_gateEntry.LoadingEntry = gateEntryHasOneLoadingEntry{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("LoadingEntry", "models.LoadingEntry"),
		Details: struct {
			field.RelationField
			LoadingEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("LoadingEntry.Details", "models.LoadingEntryDetails"),
			LoadingEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
			},
		},
		GateEntries: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("LoadingEntry.GateEntries", "models.GateEntry"),
		},
	}

	_gateEntry.Sanokatas = gateEntryHasManySanokatas{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Sanokatas", "models.Sanokata"),
		User: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Sanokatas.User", "models.User"),
		},
		GateEntry: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Sanokatas.GateEntry", "models.GateEntry"),
		},
	}

	_gateEntry.SHooks = gateEntryHasManySHooks{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SHooks", "models.SHook"),
		GateEntry: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("SHooks.GateEntry", "models.GateEntry"),
		},
	}

	_gateEntry.QualityReport = gateEntryBelongsToQualityReport{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("QualityReport", "models.QualityReport"),
		Agent: struct {
			field.RelationField
			QualityReports struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("QualityReport.Agent", "models.Agent"),
			QualityReports: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("QualityReport.Agent.QualityReports", "models.QualityReport"),
			},
		},
		GateEntry: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("QualityReport.GateEntry", "models.GateEntry"),
		},
		Details: struct {
			field.RelationField
			ScrapTypeInfo struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}
			Report struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("QualityReport.Details", "models.QualityReportDetails"),
			ScrapTypeInfo: struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
				Details: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
				},
			},
			Report: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("QualityReport.Details.Report", "models.QualityReport"),
			},
		},
	}

	_gateEntry.fillFieldMap()

	return _gateEntry
}

type gateEntry struct {
	gateEntryDo gateEntryDo

	ALL            field.Asterisk
	DocumentNo     field.String
	TokenId        field.String
	LoadingSlipNo  field.String
	VehicleNo      field.String
	DriverName     field.String
	DriverMobile   field.String
	Purpose        field.String
	EntryDate      field.String
	EntryTime      field.String
	ExitDate       field.String
	ExitTime       field.String
	GateUser       field.Int
	ThulokataEntry field.Int
	ScrapEntry     field.Int
	Scrap          gateEntryHasOneScrap

	Thulokata gateEntryHasOneThulokata

	LoadingEntry gateEntryHasOneLoadingEntry

	Sanokatas gateEntryHasManySanokatas

	SHooks gateEntryHasManySHooks

	QualityReport gateEntryBelongsToQualityReport

	fieldMap map[string]field.Expr
}

func (g gateEntry) Table(newTableName string) *gateEntry {
	g.gateEntryDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gateEntry) As(alias string) *gateEntry {
	g.gateEntryDo.DO = *(g.gateEntryDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gateEntry) updateTableName(table string) *gateEntry {
	g.ALL = field.NewAsterisk(table)
	g.DocumentNo = field.NewString(table, "document_number")
	g.TokenId = field.NewString(table, "token_id")
	g.LoadingSlipNo = field.NewString(table, "loading_slip_no")
	g.VehicleNo = field.NewString(table, "vehicle_number")
	g.DriverName = field.NewString(table, "driver_name")
	g.DriverMobile = field.NewString(table, "driver_mobile")
	g.Purpose = field.NewString(table, "purpose")
	g.EntryDate = field.NewString(table, "entry_date")
	g.EntryTime = field.NewString(table, "entry_time")
	g.ExitDate = field.NewString(table, "exit_date")
	g.ExitTime = field.NewString(table, "exit_time")
	g.GateUser = field.NewInt(table, "gate_user")
	g.ThulokataEntry = field.NewInt(table, "thulokata_entry")
	g.ScrapEntry = field.NewInt(table, "scrap_entry")

	g.fillFieldMap()

	return g
}

func (g *gateEntry) WithContext(ctx context.Context) *gateEntryDo {
	return g.gateEntryDo.WithContext(ctx)
}

func (g gateEntry) TableName() string { return g.gateEntryDo.TableName() }

func (g gateEntry) Alias() string { return g.gateEntryDo.Alias() }

func (g gateEntry) Columns(cols ...field.Expr) gen.Columns { return g.gateEntryDo.Columns(cols...) }

func (g *gateEntry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gateEntry) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 20)
	g.fieldMap["document_number"] = g.DocumentNo
	g.fieldMap["token_id"] = g.TokenId
	g.fieldMap["loading_slip_no"] = g.LoadingSlipNo
	g.fieldMap["vehicle_number"] = g.VehicleNo
	g.fieldMap["driver_name"] = g.DriverName
	g.fieldMap["driver_mobile"] = g.DriverMobile
	g.fieldMap["purpose"] = g.Purpose
	g.fieldMap["entry_date"] = g.EntryDate
	g.fieldMap["entry_time"] = g.EntryTime
	g.fieldMap["exit_date"] = g.ExitDate
	g.fieldMap["exit_time"] = g.ExitTime
	g.fieldMap["gate_user"] = g.GateUser
	g.fieldMap["thulokata_entry"] = g.ThulokataEntry
	g.fieldMap["scrap_entry"] = g.ScrapEntry

}

func (g gateEntry) clone(db *gorm.DB) gateEntry {
	g.gateEntryDo.ReplaceConnPool(db.Statement.ConnPool)
	g.Scrap.db = db.Session(&gorm.Session{Initialized: true})
	g.Scrap.db.Statement.ConnPool = db.Statement.ConnPool
	g.Thulokata.db = db.Session(&gorm.Session{Initialized: true})
	g.Thulokata.db.Statement.ConnPool = db.Statement.ConnPool
	g.LoadingEntry.db = db.Session(&gorm.Session{Initialized: true})
	g.LoadingEntry.db.Statement.ConnPool = db.Statement.ConnPool
	g.Sanokatas.db = db.Session(&gorm.Session{Initialized: true})
	g.Sanokatas.db.Statement.ConnPool = db.Statement.ConnPool
	g.SHooks.db = db.Session(&gorm.Session{Initialized: true})
	g.SHooks.db.Statement.ConnPool = db.Statement.ConnPool
	g.QualityReport.db = db.Session(&gorm.Session{Initialized: true})
	g.QualityReport.db.Statement.ConnPool = db.Statement.ConnPool
	return g
}

func (g gateEntry) replaceDB(db *gorm.DB) gateEntry {
	g.gateEntryDo.ReplaceDB(db)
	g.Scrap.db = db.Session(&gorm.Session{})
	g.Thulokata.db = db.Session(&gorm.Session{})
	g.LoadingEntry.db = db.Session(&gorm.Session{})
	g.Sanokatas.db = db.Session(&gorm.Session{})
	g.SHooks.db = db.Session(&gorm.Session{})
	g.QualityReport.db = db.Session(&gorm.Session{})
	return g
}

type gateEntryHasOneScrap struct {
	db *gorm.DB

	field.RelationField

	Vendor struct {
		field.RelationField
		Scraps struct {
			field.RelationField
		}
	}
	GateEntry struct {
		field.RelationField
		QualityReport struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}
		Scrap struct {
			field.RelationField
		}
		Thulokata struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		LoadingEntry struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Sanokatas struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}
		SHooks struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}
	}
	MultiUnloads struct {
		field.RelationField
		Scrap struct {
			field.RelationField
		}
	}
	GateEntries struct {
		field.RelationField
		QualityReport struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}
		Scrap struct {
			field.RelationField
		}
		Thulokata struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		LoadingEntry struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Sanokatas struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}
		SHooks struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}
	}
}

func (a gateEntryHasOneScrap) Where(conds ...field.Expr) *gateEntryHasOneScrap {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a gateEntryHasOneScrap) WithContext(ctx context.Context) *gateEntryHasOneScrap {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a gateEntryHasOneScrap) Session(session *gorm.Session) *gateEntryHasOneScrap {
	a.db = a.db.Session(session)
	return &a
}

func (a gateEntryHasOneScrap) Model(m *models.GateEntry) *gateEntryHasOneScrapTx {
	return &gateEntryHasOneScrapTx{a.db.Model(m).Association(a.Name())}
}

func (a gateEntryHasOneScrap) Unscoped() *gateEntryHasOneScrap {
	a.db = a.db.Unscoped()
	return &a
}

type gateEntryHasOneScrapTx struct{ tx *gorm.Association }

func (a gateEntryHasOneScrapTx) Find() (result *models.Scrap, err error) {
	return result, a.tx.Find(&result)
}

func (a gateEntryHasOneScrapTx) Append(values ...*models.Scrap) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a gateEntryHasOneScrapTx) Replace(values ...*models.Scrap) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a gateEntryHasOneScrapTx) Delete(values ...*models.Scrap) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a gateEntryHasOneScrapTx) Clear() error {
	return a.tx.Clear()
}

func (a gateEntryHasOneScrapTx) Count() int64 {
	return a.tx.Count()
}

func (a gateEntryHasOneScrapTx) Unscoped() *gateEntryHasOneScrapTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type gateEntryHasOneThulokata struct {
	db *gorm.DB

	field.RelationField

	GateEntry struct {
		field.RelationField
	}
	Loadings struct {
		field.RelationField
		Thulokata struct {
			field.RelationField
		}
	}
	GateEntries struct {
		field.RelationField
	}
}

func (a gateEntryHasOneThulokata) Where(conds ...field.Expr) *gateEntryHasOneThulokata {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a gateEntryHasOneThulokata) WithContext(ctx context.Context) *gateEntryHasOneThulokata {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a gateEntryHasOneThulokata) Session(session *gorm.Session) *gateEntryHasOneThulokata {
	a.db = a.db.Session(session)
	return &a
}

func (a gateEntryHasOneThulokata) Model(m *models.GateEntry) *gateEntryHasOneThulokataTx {
	return &gateEntryHasOneThulokataTx{a.db.Model(m).Association(a.Name())}
}

func (a gateEntryHasOneThulokata) Unscoped() *gateEntryHasOneThulokata {
	a.db = a.db.Unscoped()
	return &a
}

type gateEntryHasOneThulokataTx struct{ tx *gorm.Association }

func (a gateEntryHasOneThulokataTx) Find() (result *models.Thulokata, err error) {
	return result, a.tx.Find(&result)
}

func (a gateEntryHasOneThulokataTx) Append(values ...*models.Thulokata) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a gateEntryHasOneThulokataTx) Replace(values ...*models.Thulokata) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a gateEntryHasOneThulokataTx) Delete(values ...*models.Thulokata) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a gateEntryHasOneThulokataTx) Clear() error {
	return a.tx.Clear()
}

func (a gateEntryHasOneThulokataTx) Count() int64 {
	return a.tx.Count()
}

func (a gateEntryHasOneThulokataTx) Unscoped() *gateEntryHasOneThulokataTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type gateEntryHasOneLoadingEntry struct {
	db *gorm.DB

	field.RelationField

	Details struct {
		field.RelationField
		LoadingEntry struct {
			field.RelationField
		}
	}
	GateEntries struct {
		field.RelationField
	}
}

func (a gateEntryHasOneLoadingEntry) Where(conds ...field.Expr) *gateEntryHasOneLoadingEntry {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a gateEntryHasOneLoadingEntry) WithContext(ctx context.Context) *gateEntryHasOneLoadingEntry {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a gateEntryHasOneLoadingEntry) Session(session *gorm.Session) *gateEntryHasOneLoadingEntry {
	a.db = a.db.Session(session)
	return &a
}

func (a gateEntryHasOneLoadingEntry) Model(m *models.GateEntry) *gateEntryHasOneLoadingEntryTx {
	return &gateEntryHasOneLoadingEntryTx{a.db.Model(m).Association(a.Name())}
}

func (a gateEntryHasOneLoadingEntry) Unscoped() *gateEntryHasOneLoadingEntry {
	a.db = a.db.Unscoped()
	return &a
}

type gateEntryHasOneLoadingEntryTx struct{ tx *gorm.Association }

func (a gateEntryHasOneLoadingEntryTx) Find() (result *models.LoadingEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a gateEntryHasOneLoadingEntryTx) Append(values ...*models.LoadingEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a gateEntryHasOneLoadingEntryTx) Replace(values ...*models.LoadingEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a gateEntryHasOneLoadingEntryTx) Delete(values ...*models.LoadingEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a gateEntryHasOneLoadingEntryTx) Clear() error {
	return a.tx.Clear()
}

func (a gateEntryHasOneLoadingEntryTx) Count() int64 {
	return a.tx.Count()
}

func (a gateEntryHasOneLoadingEntryTx) Unscoped() *gateEntryHasOneLoadingEntryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type gateEntryHasManySanokatas struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
	}
	GateEntry struct {
		field.RelationField
	}
}

func (a gateEntryHasManySanokatas) Where(conds ...field.Expr) *gateEntryHasManySanokatas {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a gateEntryHasManySanokatas) WithContext(ctx context.Context) *gateEntryHasManySanokatas {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a gateEntryHasManySanokatas) Session(session *gorm.Session) *gateEntryHasManySanokatas {
	a.db = a.db.Session(session)
	return &a
}

func (a gateEntryHasManySanokatas) Model(m *models.GateEntry) *gateEntryHasManySanokatasTx {
	return &gateEntryHasManySanokatasTx{a.db.Model(m).Association(a.Name())}
}

func (a gateEntryHasManySanokatas) Unscoped() *gateEntryHasManySanokatas {
	a.db = a.db.Unscoped()
	return &a
}

type gateEntryHasManySanokatasTx struct{ tx *gorm.Association }

func (a gateEntryHasManySanokatasTx) Find() (result []*models.Sanokata, err error) {
	return result, a.tx.Find(&result)
}

func (a gateEntryHasManySanokatasTx) Append(values ...*models.Sanokata) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a gateEntryHasManySanokatasTx) Replace(values ...*models.Sanokata) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a gateEntryHasManySanokatasTx) Delete(values ...*models.Sanokata) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a gateEntryHasManySanokatasTx) Clear() error {
	return a.tx.Clear()
}

func (a gateEntryHasManySanokatasTx) Count() int64 {
	return a.tx.Count()
}

func (a gateEntryHasManySanokatasTx) Unscoped() *gateEntryHasManySanokatasTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type gateEntryHasManySHooks struct {
	db *gorm.DB

	field.RelationField

	GateEntry struct {
		field.RelationField
	}
}

func (a gateEntryHasManySHooks) Where(conds ...field.Expr) *gateEntryHasManySHooks {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a gateEntryHasManySHooks) WithContext(ctx context.Context) *gateEntryHasManySHooks {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a gateEntryHasManySHooks) Session(session *gorm.Session) *gateEntryHasManySHooks {
	a.db = a.db.Session(session)
	return &a
}

func (a gateEntryHasManySHooks) Model(m *models.GateEntry) *gateEntryHasManySHooksTx {
	return &gateEntryHasManySHooksTx{a.db.Model(m).Association(a.Name())}
}

func (a gateEntryHasManySHooks) Unscoped() *gateEntryHasManySHooks {
	a.db = a.db.Unscoped()
	return &a
}

type gateEntryHasManySHooksTx struct{ tx *gorm.Association }

func (a gateEntryHasManySHooksTx) Find() (result []*models.SHook, err error) {
	return result, a.tx.Find(&result)
}

func (a gateEntryHasManySHooksTx) Append(values ...*models.SHook) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a gateEntryHasManySHooksTx) Replace(values ...*models.SHook) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a gateEntryHasManySHooksTx) Delete(values ...*models.SHook) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a gateEntryHasManySHooksTx) Clear() error {
	return a.tx.Clear()
}

func (a gateEntryHasManySHooksTx) Count() int64 {
	return a.tx.Count()
}

func (a gateEntryHasManySHooksTx) Unscoped() *gateEntryHasManySHooksTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type gateEntryBelongsToQualityReport struct {
	db *gorm.DB

	field.RelationField

	Agent struct {
		field.RelationField
		QualityReports struct {
			field.RelationField
		}
	}
	GateEntry struct {
		field.RelationField
	}
	Details struct {
		field.RelationField
		ScrapTypeInfo struct {
			field.RelationField
			Details struct {
				field.RelationField
			}
		}
		Report struct {
			field.RelationField
		}
	}
}

func (a gateEntryBelongsToQualityReport) Where(conds ...field.Expr) *gateEntryBelongsToQualityReport {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a gateEntryBelongsToQualityReport) WithContext(ctx context.Context) *gateEntryBelongsToQualityReport {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a gateEntryBelongsToQualityReport) Session(session *gorm.Session) *gateEntryBelongsToQualityReport {
	a.db = a.db.Session(session)
	return &a
}

func (a gateEntryBelongsToQualityReport) Model(m *models.GateEntry) *gateEntryBelongsToQualityReportTx {
	return &gateEntryBelongsToQualityReportTx{a.db.Model(m).Association(a.Name())}
}

func (a gateEntryBelongsToQualityReport) Unscoped() *gateEntryBelongsToQualityReport {
	a.db = a.db.Unscoped()
	return &a
}

type gateEntryBelongsToQualityReportTx struct{ tx *gorm.Association }

func (a gateEntryBelongsToQualityReportTx) Find() (result *models.QualityReport, err error) {
	return result, a.tx.Find(&result)
}

func (a gateEntryBelongsToQualityReportTx) Append(values ...*models.QualityReport) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a gateEntryBelongsToQualityReportTx) Replace(values ...*models.QualityReport) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a gateEntryBelongsToQualityReportTx) Delete(values ...*models.QualityReport) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a gateEntryBelongsToQualityReportTx) Clear() error {
	return a.tx.Clear()
}

func (a gateEntryBelongsToQualityReportTx) Count() int64 {
	return a.tx.Count()
}

func (a gateEntryBelongsToQualityReportTx) Unscoped() *gateEntryBelongsToQualityReportTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type gateEntryDo struct{ gen.DO }

func (g gateEntryDo) Debug() *gateEntryDo {
	return g.withDO(g.DO.Debug())
}

func (g gateEntryDo) WithContext(ctx context.Context) *gateEntryDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gateEntryDo) ReadDB() *gateEntryDo {
	return g.Clauses(dbresolver.Read)
}

func (g gateEntryDo) WriteDB() *gateEntryDo {
	return g.Clauses(dbresolver.Write)
}

func (g gateEntryDo) Session(config *gorm.Session) *gateEntryDo {
	return g.withDO(g.DO.Session(config))
}

func (g gateEntryDo) Clauses(conds ...clause.Expression) *gateEntryDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gateEntryDo) Returning(value interface{}, columns ...string) *gateEntryDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gateEntryDo) Not(conds ...gen.Condition) *gateEntryDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gateEntryDo) Or(conds ...gen.Condition) *gateEntryDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gateEntryDo) Select(conds ...field.Expr) *gateEntryDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gateEntryDo) Where(conds ...gen.Condition) *gateEntryDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gateEntryDo) Order(conds ...field.Expr) *gateEntryDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gateEntryDo) Distinct(cols ...field.Expr) *gateEntryDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gateEntryDo) Omit(cols ...field.Expr) *gateEntryDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gateEntryDo) Join(table schema.Tabler, on ...field.Expr) *gateEntryDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gateEntryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gateEntryDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gateEntryDo) RightJoin(table schema.Tabler, on ...field.Expr) *gateEntryDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gateEntryDo) Group(cols ...field.Expr) *gateEntryDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gateEntryDo) Having(conds ...gen.Condition) *gateEntryDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gateEntryDo) Limit(limit int) *gateEntryDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gateEntryDo) Offset(offset int) *gateEntryDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gateEntryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gateEntryDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gateEntryDo) Unscoped() *gateEntryDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gateEntryDo) Create(values ...*models.GateEntry) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gateEntryDo) CreateInBatches(values []*models.GateEntry, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gateEntryDo) Save(values ...*models.GateEntry) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gateEntryDo) First() (*models.GateEntry, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.GateEntry), nil
	}
}

func (g gateEntryDo) Take() (*models.GateEntry, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.GateEntry), nil
	}
}

func (g gateEntryDo) Last() (*models.GateEntry, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.GateEntry), nil
	}
}

func (g gateEntryDo) Find() ([]*models.GateEntry, error) {
	result, err := g.DO.Find()
	return result.([]*models.GateEntry), err
}

func (g gateEntryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.GateEntry, err error) {
	buf := make([]*models.GateEntry, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gateEntryDo) FindInBatches(result *[]*models.GateEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gateEntryDo) Attrs(attrs ...field.AssignExpr) *gateEntryDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gateEntryDo) Assign(attrs ...field.AssignExpr) *gateEntryDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gateEntryDo) Joins(fields ...field.RelationField) *gateEntryDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gateEntryDo) Preload(fields ...field.RelationField) *gateEntryDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gateEntryDo) FirstOrInit() (*models.GateEntry, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.GateEntry), nil
	}
}

func (g gateEntryDo) FirstOrCreate() (*models.GateEntry, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.GateEntry), nil
	}
}

func (g gateEntryDo) FindByPage(offset int, limit int) (result []*models.GateEntry, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gateEntryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gateEntryDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gateEntryDo) Delete(models ...*models.GateEntry) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gateEntryDo) withDO(do gen.Dao) *gateEntryDo {
	g.DO = *do.(*gen.DO)
	return g
}
