// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newGateLoadingSlip(db *gorm.DB, opts ...gen.DOOption) gateLoadingSlip {
	_gateLoadingSlip := gateLoadingSlip{}

	_gateLoadingSlip.gateLoadingSlipDo.UseDB(db, opts...)
	_gateLoadingSlip.gateLoadingSlipDo.UseModel(&models.GateLoadingSlip{})

	tableName := _gateLoadingSlip.gateLoadingSlipDo.TableName()
	_gateLoadingSlip.ALL = field.NewAsterisk(tableName)
	_gateLoadingSlip.ID = field.NewInt64(tableName, "id")
	_gateLoadingSlip.LoadingSlipNo = field.NewString(tableName, "loading_slip_no")
	_gateLoadingSlip.PartyName = field.NewString(tableName, "party_name")
	_gateLoadingSlip.VehicleNumber = field.NewString(tableName, "vehicle_number")
	_gateLoadingSlip.CreatedAt = field.NewString(tableName, "created_at")

	_gateLoadingSlip.fillFieldMap()

	return _gateLoadingSlip
}

type gateLoadingSlip struct {
	gateLoadingSlipDo gateLoadingSlipDo

	ALL           field.Asterisk
	ID            field.Int64
	LoadingSlipNo field.String
	PartyName     field.String
	VehicleNumber field.String
	CreatedAt     field.String

	fieldMap map[string]field.Expr
}

func (g gateLoadingSlip) Table(newTableName string) *gateLoadingSlip {
	g.gateLoadingSlipDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gateLoadingSlip) As(alias string) *gateLoadingSlip {
	g.gateLoadingSlipDo.DO = *(g.gateLoadingSlipDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gateLoadingSlip) updateTableName(table string) *gateLoadingSlip {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.LoadingSlipNo = field.NewString(table, "loading_slip_no")
	g.PartyName = field.NewString(table, "party_name")
	g.VehicleNumber = field.NewString(table, "vehicle_number")
	g.CreatedAt = field.NewString(table, "created_at")

	g.fillFieldMap()

	return g
}

func (g *gateLoadingSlip) WithContext(ctx context.Context) *gateLoadingSlipDo {
	return g.gateLoadingSlipDo.WithContext(ctx)
}

func (g gateLoadingSlip) TableName() string { return g.gateLoadingSlipDo.TableName() }

func (g gateLoadingSlip) Alias() string { return g.gateLoadingSlipDo.Alias() }

func (g gateLoadingSlip) Columns(cols ...field.Expr) gen.Columns {
	return g.gateLoadingSlipDo.Columns(cols...)
}

func (g *gateLoadingSlip) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gateLoadingSlip) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 5)
	g.fieldMap["id"] = g.ID
	g.fieldMap["loading_slip_no"] = g.LoadingSlipNo
	g.fieldMap["party_name"] = g.PartyName
	g.fieldMap["vehicle_number"] = g.VehicleNumber
	g.fieldMap["created_at"] = g.CreatedAt
}

func (g gateLoadingSlip) clone(db *gorm.DB) gateLoadingSlip {
	g.gateLoadingSlipDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gateLoadingSlip) replaceDB(db *gorm.DB) gateLoadingSlip {
	g.gateLoadingSlipDo.ReplaceDB(db)
	return g
}

type gateLoadingSlipDo struct{ gen.DO }

func (g gateLoadingSlipDo) Debug() *gateLoadingSlipDo {
	return g.withDO(g.DO.Debug())
}

func (g gateLoadingSlipDo) WithContext(ctx context.Context) *gateLoadingSlipDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gateLoadingSlipDo) ReadDB() *gateLoadingSlipDo {
	return g.Clauses(dbresolver.Read)
}

func (g gateLoadingSlipDo) WriteDB() *gateLoadingSlipDo {
	return g.Clauses(dbresolver.Write)
}

func (g gateLoadingSlipDo) Session(config *gorm.Session) *gateLoadingSlipDo {
	return g.withDO(g.DO.Session(config))
}

func (g gateLoadingSlipDo) Clauses(conds ...clause.Expression) *gateLoadingSlipDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gateLoadingSlipDo) Returning(value interface{}, columns ...string) *gateLoadingSlipDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gateLoadingSlipDo) Not(conds ...gen.Condition) *gateLoadingSlipDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gateLoadingSlipDo) Or(conds ...gen.Condition) *gateLoadingSlipDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gateLoadingSlipDo) Select(conds ...field.Expr) *gateLoadingSlipDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gateLoadingSlipDo) Where(conds ...gen.Condition) *gateLoadingSlipDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gateLoadingSlipDo) Order(conds ...field.Expr) *gateLoadingSlipDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gateLoadingSlipDo) Distinct(cols ...field.Expr) *gateLoadingSlipDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gateLoadingSlipDo) Omit(cols ...field.Expr) *gateLoadingSlipDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gateLoadingSlipDo) Join(table schema.Tabler, on ...field.Expr) *gateLoadingSlipDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gateLoadingSlipDo) LeftJoin(table schema.Tabler, on ...field.Expr) *gateLoadingSlipDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gateLoadingSlipDo) RightJoin(table schema.Tabler, on ...field.Expr) *gateLoadingSlipDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gateLoadingSlipDo) Group(cols ...field.Expr) *gateLoadingSlipDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gateLoadingSlipDo) Having(conds ...gen.Condition) *gateLoadingSlipDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gateLoadingSlipDo) Limit(limit int) *gateLoadingSlipDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gateLoadingSlipDo) Offset(offset int) *gateLoadingSlipDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gateLoadingSlipDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *gateLoadingSlipDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gateLoadingSlipDo) Unscoped() *gateLoadingSlipDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gateLoadingSlipDo) Create(values ...*models.GateLoadingSlip) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gateLoadingSlipDo) CreateInBatches(values []*models.GateLoadingSlip, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gateLoadingSlipDo) Save(values ...*models.GateLoadingSlip) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gateLoadingSlipDo) First() (*models.GateLoadingSlip, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.GateLoadingSlip), nil
	}
}

func (g gateLoadingSlipDo) Take() (*models.GateLoadingSlip, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.GateLoadingSlip), nil
	}
}

func (g gateLoadingSlipDo) Last() (*models.GateLoadingSlip, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.GateLoadingSlip), nil
	}
}

func (g gateLoadingSlipDo) Find() ([]*models.GateLoadingSlip, error) {
	result, err := g.DO.Find()
	return result.([]*models.GateLoadingSlip), err
}

func (g gateLoadingSlipDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.GateLoadingSlip, err error) {
	buf := make([]*models.GateLoadingSlip, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gateLoadingSlipDo) FindInBatches(result *[]*models.GateLoadingSlip, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gateLoadingSlipDo) Attrs(attrs ...field.AssignExpr) *gateLoadingSlipDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gateLoadingSlipDo) Assign(attrs ...field.AssignExpr) *gateLoadingSlipDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gateLoadingSlipDo) Joins(fields ...field.RelationField) *gateLoadingSlipDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gateLoadingSlipDo) Preload(fields ...field.RelationField) *gateLoadingSlipDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gateLoadingSlipDo) FirstOrInit() (*models.GateLoadingSlip, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.GateLoadingSlip), nil
	}
}

func (g gateLoadingSlipDo) FirstOrCreate() (*models.GateLoadingSlip, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.GateLoadingSlip), nil
	}
}

func (g gateLoadingSlipDo) FindByPage(offset int, limit int) (result []*models.GateLoadingSlip, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gateLoadingSlipDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gateLoadingSlipDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gateLoadingSlipDo) Delete(models ...*models.GateLoadingSlip) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gateLoadingSlipDo) withDO(do gen.Dao) *gateLoadingSlipDo {
	g.DO = *do.(*gen.DO)
	return g
}
