// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                   db,
		GateEntry:            newGateEntry(db, opts...),
		GateLoadingSlip:      newGateLoadingSlip(db, opts...),
		LoadingEntry:         newLoadingEntry(db, opts...),
		LoadingEntryDetails:  newLoadingEntryDetails(db, opts...),
		QualityReport:        newQualityReport(db, opts...),
		QualityReportDetails: newQualityReportDetails(db, opts...),
		SHook:                newSHook(db, opts...),
		Sanokata:             newSanokata(db, opts...),
		Scrap:                newScrap(db, opts...),
		Thulokata:            newThulokata(db, opts...),
		ThulokataLoading:     newThulokataLoading(db, opts...),
		User:                 newUser(db, opts...),
		Vendors:              newVendors(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	GateEntry            gateEntry
	GateLoadingSlip      gateLoadingSlip
	LoadingEntry         loadingEntry
	LoadingEntryDetails  loadingEntryDetails
	QualityReport        qualityReport
	QualityReportDetails qualityReportDetails
	SHook                sHook
	Sanokata             sanokata
	Scrap                scrap
	Thulokata            thulokata
	ThulokataLoading     thulokataLoading
	User                 user
	Vendors              vendors
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		GateEntry:            q.GateEntry.clone(db),
		GateLoadingSlip:      q.GateLoadingSlip.clone(db),
		LoadingEntry:         q.LoadingEntry.clone(db),
		LoadingEntryDetails:  q.LoadingEntryDetails.clone(db),
		QualityReport:        q.QualityReport.clone(db),
		QualityReportDetails: q.QualityReportDetails.clone(db),
		SHook:                q.SHook.clone(db),
		Sanokata:             q.Sanokata.clone(db),
		Scrap:                q.Scrap.clone(db),
		Thulokata:            q.Thulokata.clone(db),
		ThulokataLoading:     q.ThulokataLoading.clone(db),
		User:                 q.User.clone(db),
		Vendors:              q.Vendors.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		GateEntry:            q.GateEntry.replaceDB(db),
		GateLoadingSlip:      q.GateLoadingSlip.replaceDB(db),
		LoadingEntry:         q.LoadingEntry.replaceDB(db),
		LoadingEntryDetails:  q.LoadingEntryDetails.replaceDB(db),
		QualityReport:        q.QualityReport.replaceDB(db),
		QualityReportDetails: q.QualityReportDetails.replaceDB(db),
		SHook:                q.SHook.replaceDB(db),
		Sanokata:             q.Sanokata.replaceDB(db),
		Scrap:                q.Scrap.replaceDB(db),
		Thulokata:            q.Thulokata.replaceDB(db),
		ThulokataLoading:     q.ThulokataLoading.replaceDB(db),
		User:                 q.User.replaceDB(db),
		Vendors:              q.Vendors.replaceDB(db),
	}
}

type queryCtx struct {
	GateEntry            *gateEntryDo
	GateLoadingSlip      *gateLoadingSlipDo
	LoadingEntry         *loadingEntryDo
	LoadingEntryDetails  *loadingEntryDetailsDo
	QualityReport        *qualityReportDo
	QualityReportDetails *qualityReportDetailsDo
	SHook                *sHookDo
	Sanokata             *sanokataDo
	Scrap                *scrapDo
	Thulokata            *thulokataDo
	ThulokataLoading     *thulokataLoadingDo
	User                 *userDo
	Vendors              *vendorsDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		GateEntry:            q.GateEntry.WithContext(ctx),
		GateLoadingSlip:      q.GateLoadingSlip.WithContext(ctx),
		LoadingEntry:         q.LoadingEntry.WithContext(ctx),
		LoadingEntryDetails:  q.LoadingEntryDetails.WithContext(ctx),
		QualityReport:        q.QualityReport.WithContext(ctx),
		QualityReportDetails: q.QualityReportDetails.WithContext(ctx),
		SHook:                q.SHook.WithContext(ctx),
		Sanokata:             q.Sanokata.WithContext(ctx),
		Scrap:                q.Scrap.WithContext(ctx),
		Thulokata:            q.Thulokata.WithContext(ctx),
		ThulokataLoading:     q.ThulokataLoading.WithContext(ctx),
		User:                 q.User.WithContext(ctx),
		Vendors:              q.Vendors.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
