// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newLoadingEntryDetails(db *gorm.DB, opts ...gen.DOOption) loadingEntryDetails {
	_loadingEntryDetails := loadingEntryDetails{}

	_loadingEntryDetails.loadingEntryDetailsDo.UseDB(db, opts...)
	_loadingEntryDetails.loadingEntryDetailsDo.UseModel(&models.LoadingEntryDetails{})

	tableName := _loadingEntryDetails.loadingEntryDetailsDo.TableName()
	_loadingEntryDetails.ALL = field.NewAsterisk(tableName)
	_loadingEntryDetails.ID = field.NewInt64(tableName, "id")
	_loadingEntryDetails.LoadingEntryID = field.NewInt64(tableName, "loading_entry_id")
	_loadingEntryDetails.Sn = field.NewString(tableName, "sn")
	_loadingEntryDetails.Item = field.NewString(tableName, "item")
	_loadingEntryDetails.Weight = field.NewString(tableName, "weight")
	_loadingEntryDetails.Bundles = field.NewInt(tableName, "bundles")
	_loadingEntryDetails.ItemCode = field.NewString(tableName, "itemcode")
	_loadingEntryDetails.LoadingEntry = loadingEntryDetailsBelongsToLoadingEntry{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("LoadingEntry", "models.LoadingEntry"),
		Details: struct {
			field.RelationField
			LoadingEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("LoadingEntry.Details", "models.LoadingEntryDetails"),
			LoadingEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
			},
		},
		GateEntries: struct {
			field.RelationField
			QualityReport struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}
			Scrap struct {
				field.RelationField
				Vendor struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				MultiUnloads struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Thulokata struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			LoadingEntry struct {
				field.RelationField
			}
			Sanokatas struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}
			SHooks struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("LoadingEntry.GateEntries", "models.GateEntry"),
			QualityReport: struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("LoadingEntry.GateEntries.QualityReport", "models.QualityReport"),
				Agent: struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.QualityReport.Agent", "models.Agent"),
					QualityReports: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("LoadingEntry.GateEntries.QualityReport.Agent.QualityReports", "models.QualityReport"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.QualityReport.GateEntry", "models.GateEntry"),
				},
				Details: struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.QualityReport.Details", "models.QualityReportDetails"),
					ScrapTypeInfo: struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("LoadingEntry.GateEntries.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
						Details: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("LoadingEntry.GateEntries.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
						},
					},
					Report: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("LoadingEntry.GateEntries.QualityReport.Details.Report", "models.QualityReport"),
					},
				},
			},
			Scrap: struct {
				field.RelationField
				Vendor struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				MultiUnloads struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LoadingEntry.GateEntries.Scrap", "models.Scrap"),
				Vendor: struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.Scrap.Vendor", "models.Vendors"),
					Scraps: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("LoadingEntry.GateEntries.Scrap.Vendor.Scraps", "models.Scrap"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.Scrap.GateEntry", "models.GateEntry"),
				},
				MultiUnloads: struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
					Scrap: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("LoadingEntry.GateEntries.Scrap.MultiUnloads.Scrap", "models.Scrap"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.Scrap.GateEntries", "models.GateEntry"),
				},
			},
			Thulokata: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LoadingEntry.GateEntries.Thulokata", "models.Thulokata"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.Thulokata.GateEntry", "models.GateEntry"),
				},
				Loadings: struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.Thulokata.Loadings", "models.ThulokataLoading"),
					Thulokata: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("LoadingEntry.GateEntries.Thulokata.Loadings.Thulokata", "models.Thulokata"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.Thulokata.GateEntries", "models.GateEntry"),
				},
			},
			LoadingEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("LoadingEntry.GateEntries.LoadingEntry", "models.LoadingEntry"),
			},
			Sanokatas: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LoadingEntry.GateEntries.Sanokatas", "models.Sanokata"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.Sanokatas.User", "models.User"),
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.Sanokatas.GateEntry", "models.GateEntry"),
				},
			},
			SHooks: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("LoadingEntry.GateEntries.SHooks", "models.SHook"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("LoadingEntry.GateEntries.SHooks.GateEntry", "models.GateEntry"),
				},
			},
		},
	}

	_loadingEntryDetails.fillFieldMap()

	return _loadingEntryDetails
}

type loadingEntryDetails struct {
	loadingEntryDetailsDo loadingEntryDetailsDo

	ALL            field.Asterisk
	ID             field.Int64
	LoadingEntryID field.Int64
	Sn             field.String
	Item           field.String
	Weight         field.String
	Bundles        field.Int
	ItemCode       field.String
	LoadingEntry   loadingEntryDetailsBelongsToLoadingEntry

	fieldMap map[string]field.Expr
}

func (l loadingEntryDetails) Table(newTableName string) *loadingEntryDetails {
	l.loadingEntryDetailsDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l loadingEntryDetails) As(alias string) *loadingEntryDetails {
	l.loadingEntryDetailsDo.DO = *(l.loadingEntryDetailsDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *loadingEntryDetails) updateTableName(table string) *loadingEntryDetails {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.LoadingEntryID = field.NewInt64(table, "loading_entry_id")
	l.Sn = field.NewString(table, "sn")
	l.Item = field.NewString(table, "item")
	l.Weight = field.NewString(table, "weight")
	l.Bundles = field.NewInt(table, "bundles")
	l.ItemCode = field.NewString(table, "itemcode")

	l.fillFieldMap()

	return l
}

func (l *loadingEntryDetails) WithContext(ctx context.Context) *loadingEntryDetailsDo {
	return l.loadingEntryDetailsDo.WithContext(ctx)
}

func (l loadingEntryDetails) TableName() string { return l.loadingEntryDetailsDo.TableName() }

func (l loadingEntryDetails) Alias() string { return l.loadingEntryDetailsDo.Alias() }

func (l loadingEntryDetails) Columns(cols ...field.Expr) gen.Columns {
	return l.loadingEntryDetailsDo.Columns(cols...)
}

func (l *loadingEntryDetails) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *loadingEntryDetails) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 8)
	l.fieldMap["id"] = l.ID
	l.fieldMap["loading_entry_id"] = l.LoadingEntryID
	l.fieldMap["sn"] = l.Sn
	l.fieldMap["item"] = l.Item
	l.fieldMap["weight"] = l.Weight
	l.fieldMap["bundles"] = l.Bundles
	l.fieldMap["itemcode"] = l.ItemCode

}

func (l loadingEntryDetails) clone(db *gorm.DB) loadingEntryDetails {
	l.loadingEntryDetailsDo.ReplaceConnPool(db.Statement.ConnPool)
	l.LoadingEntry.db = db.Session(&gorm.Session{Initialized: true})
	l.LoadingEntry.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l loadingEntryDetails) replaceDB(db *gorm.DB) loadingEntryDetails {
	l.loadingEntryDetailsDo.ReplaceDB(db)
	l.LoadingEntry.db = db.Session(&gorm.Session{})
	return l
}

type loadingEntryDetailsBelongsToLoadingEntry struct {
	db *gorm.DB

	field.RelationField

	Details struct {
		field.RelationField
		LoadingEntry struct {
			field.RelationField
		}
	}
	GateEntries struct {
		field.RelationField
		QualityReport struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}
		Scrap struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Thulokata struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		LoadingEntry struct {
			field.RelationField
		}
		Sanokatas struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}
		SHooks struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}
	}
}

func (a loadingEntryDetailsBelongsToLoadingEntry) Where(conds ...field.Expr) *loadingEntryDetailsBelongsToLoadingEntry {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a loadingEntryDetailsBelongsToLoadingEntry) WithContext(ctx context.Context) *loadingEntryDetailsBelongsToLoadingEntry {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a loadingEntryDetailsBelongsToLoadingEntry) Session(session *gorm.Session) *loadingEntryDetailsBelongsToLoadingEntry {
	a.db = a.db.Session(session)
	return &a
}

func (a loadingEntryDetailsBelongsToLoadingEntry) Model(m *models.LoadingEntryDetails) *loadingEntryDetailsBelongsToLoadingEntryTx {
	return &loadingEntryDetailsBelongsToLoadingEntryTx{a.db.Model(m).Association(a.Name())}
}

func (a loadingEntryDetailsBelongsToLoadingEntry) Unscoped() *loadingEntryDetailsBelongsToLoadingEntry {
	a.db = a.db.Unscoped()
	return &a
}

type loadingEntryDetailsBelongsToLoadingEntryTx struct{ tx *gorm.Association }

func (a loadingEntryDetailsBelongsToLoadingEntryTx) Find() (result *models.LoadingEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a loadingEntryDetailsBelongsToLoadingEntryTx) Append(values ...*models.LoadingEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a loadingEntryDetailsBelongsToLoadingEntryTx) Replace(values ...*models.LoadingEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a loadingEntryDetailsBelongsToLoadingEntryTx) Delete(values ...*models.LoadingEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a loadingEntryDetailsBelongsToLoadingEntryTx) Clear() error {
	return a.tx.Clear()
}

func (a loadingEntryDetailsBelongsToLoadingEntryTx) Count() int64 {
	return a.tx.Count()
}

func (a loadingEntryDetailsBelongsToLoadingEntryTx) Unscoped() *loadingEntryDetailsBelongsToLoadingEntryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type loadingEntryDetailsDo struct{ gen.DO }

func (l loadingEntryDetailsDo) Debug() *loadingEntryDetailsDo {
	return l.withDO(l.DO.Debug())
}

func (l loadingEntryDetailsDo) WithContext(ctx context.Context) *loadingEntryDetailsDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l loadingEntryDetailsDo) ReadDB() *loadingEntryDetailsDo {
	return l.Clauses(dbresolver.Read)
}

func (l loadingEntryDetailsDo) WriteDB() *loadingEntryDetailsDo {
	return l.Clauses(dbresolver.Write)
}

func (l loadingEntryDetailsDo) Session(config *gorm.Session) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Session(config))
}

func (l loadingEntryDetailsDo) Clauses(conds ...clause.Expression) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l loadingEntryDetailsDo) Returning(value interface{}, columns ...string) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l loadingEntryDetailsDo) Not(conds ...gen.Condition) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l loadingEntryDetailsDo) Or(conds ...gen.Condition) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l loadingEntryDetailsDo) Select(conds ...field.Expr) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l loadingEntryDetailsDo) Where(conds ...gen.Condition) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l loadingEntryDetailsDo) Order(conds ...field.Expr) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l loadingEntryDetailsDo) Distinct(cols ...field.Expr) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l loadingEntryDetailsDo) Omit(cols ...field.Expr) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l loadingEntryDetailsDo) Join(table schema.Tabler, on ...field.Expr) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l loadingEntryDetailsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *loadingEntryDetailsDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l loadingEntryDetailsDo) RightJoin(table schema.Tabler, on ...field.Expr) *loadingEntryDetailsDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l loadingEntryDetailsDo) Group(cols ...field.Expr) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l loadingEntryDetailsDo) Having(conds ...gen.Condition) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l loadingEntryDetailsDo) Limit(limit int) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l loadingEntryDetailsDo) Offset(offset int) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l loadingEntryDetailsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l loadingEntryDetailsDo) Unscoped() *loadingEntryDetailsDo {
	return l.withDO(l.DO.Unscoped())
}

func (l loadingEntryDetailsDo) Create(values ...*models.LoadingEntryDetails) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l loadingEntryDetailsDo) CreateInBatches(values []*models.LoadingEntryDetails, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l loadingEntryDetailsDo) Save(values ...*models.LoadingEntryDetails) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l loadingEntryDetailsDo) First() (*models.LoadingEntryDetails, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LoadingEntryDetails), nil
	}
}

func (l loadingEntryDetailsDo) Take() (*models.LoadingEntryDetails, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LoadingEntryDetails), nil
	}
}

func (l loadingEntryDetailsDo) Last() (*models.LoadingEntryDetails, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LoadingEntryDetails), nil
	}
}

func (l loadingEntryDetailsDo) Find() ([]*models.LoadingEntryDetails, error) {
	result, err := l.DO.Find()
	return result.([]*models.LoadingEntryDetails), err
}

func (l loadingEntryDetailsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LoadingEntryDetails, err error) {
	buf := make([]*models.LoadingEntryDetails, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l loadingEntryDetailsDo) FindInBatches(result *[]*models.LoadingEntryDetails, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l loadingEntryDetailsDo) Attrs(attrs ...field.AssignExpr) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l loadingEntryDetailsDo) Assign(attrs ...field.AssignExpr) *loadingEntryDetailsDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l loadingEntryDetailsDo) Joins(fields ...field.RelationField) *loadingEntryDetailsDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l loadingEntryDetailsDo) Preload(fields ...field.RelationField) *loadingEntryDetailsDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l loadingEntryDetailsDo) FirstOrInit() (*models.LoadingEntryDetails, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LoadingEntryDetails), nil
	}
}

func (l loadingEntryDetailsDo) FirstOrCreate() (*models.LoadingEntryDetails, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LoadingEntryDetails), nil
	}
}

func (l loadingEntryDetailsDo) FindByPage(offset int, limit int) (result []*models.LoadingEntryDetails, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l loadingEntryDetailsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l loadingEntryDetailsDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l loadingEntryDetailsDo) Delete(models ...*models.LoadingEntryDetails) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *loadingEntryDetailsDo) withDO(do gen.Dao) *loadingEntryDetailsDo {
	l.DO = *do.(*gen.DO)
	return l
}
