// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newLoadingEntry(db *gorm.DB, opts ...gen.DOOption) loadingEntry {
	_loadingEntry := loadingEntry{}

	_loadingEntry.loadingEntryDo.UseDB(db, opts...)
	_loadingEntry.loadingEntryDo.UseModel(&models.LoadingEntry{})

	tableName := _loadingEntry.loadingEntryDo.TableName()
	_loadingEntry.ALL = field.NewAsterisk(tableName)
	_loadingEntry.ID = field.NewInt64(tableName, "id")
	_loadingEntry.LoadingSlipNo = field.NewString(tableName, "token")
	_loadingEntry.BookletNo = field.NewString(tableName, "booklet_no")
	_loadingEntry.PartyName = field.NewString(tableName, "party_name")
	_loadingEntry.VatNo = field.NewString(tableName, "vat")
	_loadingEntry.VehicleNo = field.NewString(tableName, "vehicle_number")
	_loadingEntry.SalesOrder = field.NewString(tableName, "sales_order")
	_loadingEntry.Transporter = field.NewString(tableName, "transporter")
	_loadingEntry.CreatedAt = field.NewString(tableName, "created_at")
	_loadingEntry.ShippingAddress = field.NewString(tableName, "shipping_address")
	_loadingEntry.Type = field.NewString(tableName, "type")
	_loadingEntry.BillingComplete = field.NewBool(tableName, "billing_complete")
	_loadingEntry.SoDocEntry = field.NewInt64(tableName, "so_doc_entry")
	_loadingEntry.Details = loadingEntryHasManyDetails{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Details", "models.LoadingEntryDetails"),
		LoadingEntry: struct {
			field.RelationField
			Details struct {
				field.RelationField
			}
			GateEntries struct {
				field.RelationField
				QualityReport struct {
					field.RelationField
					Agent struct {
						field.RelationField
						QualityReports struct {
							field.RelationField
						}
					}
					GateEntry struct {
						field.RelationField
					}
					Details struct {
						field.RelationField
						ScrapTypeInfo struct {
							field.RelationField
							Details struct {
								field.RelationField
							}
						}
						Report struct {
							field.RelationField
						}
					}
				}
				Scrap struct {
					field.RelationField
					Vendor struct {
						field.RelationField
						Scraps struct {
							field.RelationField
						}
					}
					GateEntry struct {
						field.RelationField
					}
					MultiUnloads struct {
						field.RelationField
						Scrap struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}
				Thulokata struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
					Loadings struct {
						field.RelationField
						Thulokata struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}
				LoadingEntry struct {
					field.RelationField
				}
				Sanokatas struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					GateEntry struct {
						field.RelationField
					}
				}
				SHooks struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
				}
			}
		}{
			RelationField: field.NewRelation("Details.LoadingEntry", "models.LoadingEntry"),
			Details: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Details.LoadingEntry.Details", "models.LoadingEntryDetails"),
			},
			GateEntries: struct {
				field.RelationField
				QualityReport struct {
					field.RelationField
					Agent struct {
						field.RelationField
						QualityReports struct {
							field.RelationField
						}
					}
					GateEntry struct {
						field.RelationField
					}
					Details struct {
						field.RelationField
						ScrapTypeInfo struct {
							field.RelationField
							Details struct {
								field.RelationField
							}
						}
						Report struct {
							field.RelationField
						}
					}
				}
				Scrap struct {
					field.RelationField
					Vendor struct {
						field.RelationField
						Scraps struct {
							field.RelationField
						}
					}
					GateEntry struct {
						field.RelationField
					}
					MultiUnloads struct {
						field.RelationField
						Scrap struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}
				Thulokata struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
					Loadings struct {
						field.RelationField
						Thulokata struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}
				LoadingEntry struct {
					field.RelationField
				}
				Sanokatas struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					GateEntry struct {
						field.RelationField
					}
				}
				SHooks struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Details.LoadingEntry.GateEntries", "models.GateEntry"),
				QualityReport: struct {
					field.RelationField
					Agent struct {
						field.RelationField
						QualityReports struct {
							field.RelationField
						}
					}
					GateEntry struct {
						field.RelationField
					}
					Details struct {
						field.RelationField
						ScrapTypeInfo struct {
							field.RelationField
							Details struct {
								field.RelationField
							}
						}
						Report struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.QualityReport", "models.QualityReport"),
					Agent: struct {
						field.RelationField
						QualityReports struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.QualityReport.Agent", "models.Agent"),
						QualityReports: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.QualityReport.Agent.QualityReports", "models.QualityReport"),
						},
					},
					GateEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.QualityReport.GateEntry", "models.GateEntry"),
					},
					Details: struct {
						field.RelationField
						ScrapTypeInfo struct {
							field.RelationField
							Details struct {
								field.RelationField
							}
						}
						Report struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.QualityReport.Details", "models.QualityReportDetails"),
						ScrapTypeInfo: struct {
							field.RelationField
							Details struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
							Details: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
							},
						},
						Report: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.QualityReport.Details.Report", "models.QualityReport"),
						},
					},
				},
				Scrap: struct {
					field.RelationField
					Vendor struct {
						field.RelationField
						Scraps struct {
							field.RelationField
						}
					}
					GateEntry struct {
						field.RelationField
					}
					MultiUnloads struct {
						field.RelationField
						Scrap struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Scrap", "models.Scrap"),
					Vendor: struct {
						field.RelationField
						Scraps struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Scrap.Vendor", "models.Vendors"),
						Scraps: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Scrap.Vendor.Scraps", "models.Scrap"),
						},
					},
					GateEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Scrap.GateEntry", "models.GateEntry"),
					},
					MultiUnloads: struct {
						field.RelationField
						Scrap struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
						Scrap: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Scrap.MultiUnloads.Scrap", "models.Scrap"),
						},
					},
					GateEntries: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Scrap.GateEntries", "models.GateEntry"),
					},
				},
				Thulokata: struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
					Loadings struct {
						field.RelationField
						Thulokata struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Thulokata", "models.Thulokata"),
					GateEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Thulokata.GateEntry", "models.GateEntry"),
					},
					Loadings: struct {
						field.RelationField
						Thulokata struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Thulokata.Loadings", "models.ThulokataLoading"),
						Thulokata: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Thulokata.Loadings.Thulokata", "models.Thulokata"),
						},
					},
					GateEntries: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Thulokata.GateEntries", "models.GateEntry"),
					},
				},
				LoadingEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.LoadingEntry", "models.LoadingEntry"),
				},
				Sanokatas: struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					GateEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Sanokatas", "models.Sanokata"),
					User: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Sanokatas.User", "models.User"),
					},
					GateEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.Sanokatas.GateEntry", "models.GateEntry"),
					},
				},
				SHooks: struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.SHooks", "models.SHook"),
					GateEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.LoadingEntry.GateEntries.SHooks.GateEntry", "models.GateEntry"),
					},
				},
			},
		},
	}

	_loadingEntry.GateEntries = loadingEntryHasManyGateEntries{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("GateEntries", "models.GateEntry"),
		QualityReport: struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("GateEntries.QualityReport", "models.QualityReport"),
			Agent: struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.QualityReport.Agent", "models.Agent"),
				QualityReports: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.QualityReport.Agent.QualityReports", "models.QualityReport"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.QualityReport.GateEntry", "models.GateEntry"),
			},
			Details: struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.QualityReport.Details", "models.QualityReportDetails"),
				ScrapTypeInfo: struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("GateEntries.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
					Details: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("GateEntries.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
					},
				},
				Report: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.QualityReport.Details.Report", "models.QualityReport"),
				},
			},
		},
		Scrap: struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.Scrap", "models.Scrap"),
			Vendor: struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.Vendor", "models.Vendors"),
				Scraps: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.Scrap.Vendor.Scraps", "models.Scrap"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.GateEntry", "models.GateEntry"),
			},
			MultiUnloads: struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
				Scrap: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.Scrap.MultiUnloads.Scrap", "models.Scrap"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.GateEntries", "models.GateEntry"),
			},
		},
		Thulokata: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.Thulokata", "models.Thulokata"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Thulokata.GateEntry", "models.GateEntry"),
			},
			Loadings: struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.Thulokata.Loadings", "models.ThulokataLoading"),
				Thulokata: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.Thulokata.Loadings.Thulokata", "models.Thulokata"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Thulokata.GateEntries", "models.GateEntry"),
			},
		},
		LoadingEntry: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("GateEntries.LoadingEntry", "models.LoadingEntry"),
		},
		Sanokatas: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.Sanokatas", "models.Sanokata"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Sanokatas.User", "models.User"),
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Sanokatas.GateEntry", "models.GateEntry"),
			},
		},
		SHooks: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.SHooks", "models.SHook"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.SHooks.GateEntry", "models.GateEntry"),
			},
		},
	}

	_loadingEntry.fillFieldMap()

	return _loadingEntry
}

type loadingEntry struct {
	loadingEntryDo loadingEntryDo

	ALL             field.Asterisk
	ID              field.Int64
	LoadingSlipNo   field.String
	BookletNo       field.String
	PartyName       field.String
	VatNo           field.String
	VehicleNo       field.String
	SalesOrder      field.String
	Transporter     field.String
	CreatedAt       field.String
	ShippingAddress field.String
	Type            field.String
	BillingComplete field.Bool
	SoDocEntry      field.Int64
	Details         loadingEntryHasManyDetails

	GateEntries loadingEntryHasManyGateEntries

	fieldMap map[string]field.Expr
}

func (l loadingEntry) Table(newTableName string) *loadingEntry {
	l.loadingEntryDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l loadingEntry) As(alias string) *loadingEntry {
	l.loadingEntryDo.DO = *(l.loadingEntryDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *loadingEntry) updateTableName(table string) *loadingEntry {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.LoadingSlipNo = field.NewString(table, "token")
	l.BookletNo = field.NewString(table, "booklet_no")
	l.PartyName = field.NewString(table, "party_name")
	l.VatNo = field.NewString(table, "vat")
	l.VehicleNo = field.NewString(table, "vehicle_number")
	l.SalesOrder = field.NewString(table, "sales_order")
	l.Transporter = field.NewString(table, "transporter")
	l.CreatedAt = field.NewString(table, "created_at")
	l.ShippingAddress = field.NewString(table, "shipping_address")
	l.Type = field.NewString(table, "type")
	l.BillingComplete = field.NewBool(table, "billing_complete")
	l.SoDocEntry = field.NewInt64(table, "so_doc_entry")

	l.fillFieldMap()

	return l
}

func (l *loadingEntry) WithContext(ctx context.Context) *loadingEntryDo {
	return l.loadingEntryDo.WithContext(ctx)
}

func (l loadingEntry) TableName() string { return l.loadingEntryDo.TableName() }

func (l loadingEntry) Alias() string { return l.loadingEntryDo.Alias() }

func (l loadingEntry) Columns(cols ...field.Expr) gen.Columns {
	return l.loadingEntryDo.Columns(cols...)
}

func (l *loadingEntry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *loadingEntry) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 15)
	l.fieldMap["id"] = l.ID
	l.fieldMap["token"] = l.LoadingSlipNo
	l.fieldMap["booklet_no"] = l.BookletNo
	l.fieldMap["party_name"] = l.PartyName
	l.fieldMap["vat"] = l.VatNo
	l.fieldMap["vehicle_number"] = l.VehicleNo
	l.fieldMap["sales_order"] = l.SalesOrder
	l.fieldMap["transporter"] = l.Transporter
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["shipping_address"] = l.ShippingAddress
	l.fieldMap["type"] = l.Type
	l.fieldMap["billing_complete"] = l.BillingComplete
	l.fieldMap["so_doc_entry"] = l.SoDocEntry

}

func (l loadingEntry) clone(db *gorm.DB) loadingEntry {
	l.loadingEntryDo.ReplaceConnPool(db.Statement.ConnPool)
	l.Details.db = db.Session(&gorm.Session{Initialized: true})
	l.Details.db.Statement.ConnPool = db.Statement.ConnPool
	l.GateEntries.db = db.Session(&gorm.Session{Initialized: true})
	l.GateEntries.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l loadingEntry) replaceDB(db *gorm.DB) loadingEntry {
	l.loadingEntryDo.ReplaceDB(db)
	l.Details.db = db.Session(&gorm.Session{})
	l.GateEntries.db = db.Session(&gorm.Session{})
	return l
}

type loadingEntryHasManyDetails struct {
	db *gorm.DB

	field.RelationField

	LoadingEntry struct {
		field.RelationField
		Details struct {
			field.RelationField
		}
		GateEntries struct {
			field.RelationField
			QualityReport struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}
			Scrap struct {
				field.RelationField
				Vendor struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				MultiUnloads struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Thulokata struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			LoadingEntry struct {
				field.RelationField
			}
			Sanokatas struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}
			SHooks struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}
		}
	}
}

func (a loadingEntryHasManyDetails) Where(conds ...field.Expr) *loadingEntryHasManyDetails {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a loadingEntryHasManyDetails) WithContext(ctx context.Context) *loadingEntryHasManyDetails {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a loadingEntryHasManyDetails) Session(session *gorm.Session) *loadingEntryHasManyDetails {
	a.db = a.db.Session(session)
	return &a
}

func (a loadingEntryHasManyDetails) Model(m *models.LoadingEntry) *loadingEntryHasManyDetailsTx {
	return &loadingEntryHasManyDetailsTx{a.db.Model(m).Association(a.Name())}
}

func (a loadingEntryHasManyDetails) Unscoped() *loadingEntryHasManyDetails {
	a.db = a.db.Unscoped()
	return &a
}

type loadingEntryHasManyDetailsTx struct{ tx *gorm.Association }

func (a loadingEntryHasManyDetailsTx) Find() (result []*models.LoadingEntryDetails, err error) {
	return result, a.tx.Find(&result)
}

func (a loadingEntryHasManyDetailsTx) Append(values ...*models.LoadingEntryDetails) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a loadingEntryHasManyDetailsTx) Replace(values ...*models.LoadingEntryDetails) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a loadingEntryHasManyDetailsTx) Delete(values ...*models.LoadingEntryDetails) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a loadingEntryHasManyDetailsTx) Clear() error {
	return a.tx.Clear()
}

func (a loadingEntryHasManyDetailsTx) Count() int64 {
	return a.tx.Count()
}

func (a loadingEntryHasManyDetailsTx) Unscoped() *loadingEntryHasManyDetailsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type loadingEntryHasManyGateEntries struct {
	db *gorm.DB

	field.RelationField

	QualityReport struct {
		field.RelationField
		Agent struct {
			field.RelationField
			QualityReports struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		Details struct {
			field.RelationField
			ScrapTypeInfo struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}
			Report struct {
				field.RelationField
			}
		}
	}
	Scrap struct {
		field.RelationField
		Vendor struct {
			field.RelationField
			Scraps struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		MultiUnloads struct {
			field.RelationField
			Scrap struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Thulokata struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
		Loadings struct {
			field.RelationField
			Thulokata struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	LoadingEntry struct {
		field.RelationField
	}
	Sanokatas struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		GateEntry struct {
			field.RelationField
		}
	}
	SHooks struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
	}
}

func (a loadingEntryHasManyGateEntries) Where(conds ...field.Expr) *loadingEntryHasManyGateEntries {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a loadingEntryHasManyGateEntries) WithContext(ctx context.Context) *loadingEntryHasManyGateEntries {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a loadingEntryHasManyGateEntries) Session(session *gorm.Session) *loadingEntryHasManyGateEntries {
	a.db = a.db.Session(session)
	return &a
}

func (a loadingEntryHasManyGateEntries) Model(m *models.LoadingEntry) *loadingEntryHasManyGateEntriesTx {
	return &loadingEntryHasManyGateEntriesTx{a.db.Model(m).Association(a.Name())}
}

func (a loadingEntryHasManyGateEntries) Unscoped() *loadingEntryHasManyGateEntries {
	a.db = a.db.Unscoped()
	return &a
}

type loadingEntryHasManyGateEntriesTx struct{ tx *gorm.Association }

func (a loadingEntryHasManyGateEntriesTx) Find() (result []*models.GateEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a loadingEntryHasManyGateEntriesTx) Append(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a loadingEntryHasManyGateEntriesTx) Replace(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a loadingEntryHasManyGateEntriesTx) Delete(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a loadingEntryHasManyGateEntriesTx) Clear() error {
	return a.tx.Clear()
}

func (a loadingEntryHasManyGateEntriesTx) Count() int64 {
	return a.tx.Count()
}

func (a loadingEntryHasManyGateEntriesTx) Unscoped() *loadingEntryHasManyGateEntriesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type loadingEntryDo struct{ gen.DO }

func (l loadingEntryDo) Debug() *loadingEntryDo {
	return l.withDO(l.DO.Debug())
}

func (l loadingEntryDo) WithContext(ctx context.Context) *loadingEntryDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l loadingEntryDo) ReadDB() *loadingEntryDo {
	return l.Clauses(dbresolver.Read)
}

func (l loadingEntryDo) WriteDB() *loadingEntryDo {
	return l.Clauses(dbresolver.Write)
}

func (l loadingEntryDo) Session(config *gorm.Session) *loadingEntryDo {
	return l.withDO(l.DO.Session(config))
}

func (l loadingEntryDo) Clauses(conds ...clause.Expression) *loadingEntryDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l loadingEntryDo) Returning(value interface{}, columns ...string) *loadingEntryDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l loadingEntryDo) Not(conds ...gen.Condition) *loadingEntryDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l loadingEntryDo) Or(conds ...gen.Condition) *loadingEntryDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l loadingEntryDo) Select(conds ...field.Expr) *loadingEntryDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l loadingEntryDo) Where(conds ...gen.Condition) *loadingEntryDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l loadingEntryDo) Order(conds ...field.Expr) *loadingEntryDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l loadingEntryDo) Distinct(cols ...field.Expr) *loadingEntryDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l loadingEntryDo) Omit(cols ...field.Expr) *loadingEntryDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l loadingEntryDo) Join(table schema.Tabler, on ...field.Expr) *loadingEntryDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l loadingEntryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *loadingEntryDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l loadingEntryDo) RightJoin(table schema.Tabler, on ...field.Expr) *loadingEntryDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l loadingEntryDo) Group(cols ...field.Expr) *loadingEntryDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l loadingEntryDo) Having(conds ...gen.Condition) *loadingEntryDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l loadingEntryDo) Limit(limit int) *loadingEntryDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l loadingEntryDo) Offset(offset int) *loadingEntryDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l loadingEntryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *loadingEntryDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l loadingEntryDo) Unscoped() *loadingEntryDo {
	return l.withDO(l.DO.Unscoped())
}

func (l loadingEntryDo) Create(values ...*models.LoadingEntry) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l loadingEntryDo) CreateInBatches(values []*models.LoadingEntry, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l loadingEntryDo) Save(values ...*models.LoadingEntry) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l loadingEntryDo) First() (*models.LoadingEntry, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LoadingEntry), nil
	}
}

func (l loadingEntryDo) Take() (*models.LoadingEntry, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LoadingEntry), nil
	}
}

func (l loadingEntryDo) Last() (*models.LoadingEntry, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LoadingEntry), nil
	}
}

func (l loadingEntryDo) Find() ([]*models.LoadingEntry, error) {
	result, err := l.DO.Find()
	return result.([]*models.LoadingEntry), err
}

func (l loadingEntryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LoadingEntry, err error) {
	buf := make([]*models.LoadingEntry, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l loadingEntryDo) FindInBatches(result *[]*models.LoadingEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l loadingEntryDo) Attrs(attrs ...field.AssignExpr) *loadingEntryDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l loadingEntryDo) Assign(attrs ...field.AssignExpr) *loadingEntryDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l loadingEntryDo) Joins(fields ...field.RelationField) *loadingEntryDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l loadingEntryDo) Preload(fields ...field.RelationField) *loadingEntryDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l loadingEntryDo) FirstOrInit() (*models.LoadingEntry, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LoadingEntry), nil
	}
}

func (l loadingEntryDo) FirstOrCreate() (*models.LoadingEntry, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LoadingEntry), nil
	}
}

func (l loadingEntryDo) FindByPage(offset int, limit int) (result []*models.LoadingEntry, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l loadingEntryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l loadingEntryDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l loadingEntryDo) Delete(models ...*models.LoadingEntry) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *loadingEntryDo) withDO(do gen.Dao) *loadingEntryDo {
	l.DO = *do.(*gen.DO)
	return l
}
