// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newVendors(db *gorm.DB, opts ...gen.DOOption) vendors {
	_vendors := vendors{}

	_vendors.vendorsDo.UseDB(db, opts...)
	_vendors.vendorsDo.UseModel(&models.Vendors{})

	tableName := _vendors.vendorsDo.TableName()
	_vendors.ALL = field.NewAsterisk(tableName)
	_vendors.Id = field.NewInt64(tableName, "id")
	_vendors.PanNo = field.NewString(tableName, "pan_number")
	_vendors.VendorName = field.NewString(tableName, "supplier_name")
	_vendors.VendorCode = field.NewString(tableName, "CardCode")
	_vendors.Active = field.NewBool(tableName, "active")
	_vendors.Scraps = vendorsHasManyScraps{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Scraps", "models.Scrap"),
		Vendor: struct {
			field.RelationField
			Scraps struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Scraps.Vendor", "models.Vendors"),
			Scraps: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Scraps.Vendor.Scraps", "models.Scrap"),
			},
		},
		GateEntry: struct {
			field.RelationField
			QualityReport struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}
			Scrap struct {
				field.RelationField
			}
			Thulokata struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			LoadingEntry struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Sanokatas struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}
			SHooks struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Scraps.GateEntry", "models.GateEntry"),
			QualityReport: struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Scraps.GateEntry.QualityReport", "models.QualityReport"),
				Agent: struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.QualityReport.Agent", "models.Agent"),
					QualityReports: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scraps.GateEntry.QualityReport.Agent.QualityReports", "models.QualityReport"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.QualityReport.GateEntry", "models.GateEntry"),
				},
				Details: struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.QualityReport.Details", "models.QualityReportDetails"),
					ScrapTypeInfo: struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Scraps.GateEntry.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
						Details: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Scraps.GateEntry.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
						},
					},
					Report: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scraps.GateEntry.QualityReport.Details.Report", "models.QualityReport"),
					},
				},
			},
			Scrap: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Scraps.GateEntry.Scrap", "models.Scrap"),
			},
			Thulokata: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scraps.GateEntry.Thulokata", "models.Thulokata"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.Thulokata.GateEntry", "models.GateEntry"),
				},
				Loadings: struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.Thulokata.Loadings", "models.ThulokataLoading"),
					Thulokata: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scraps.GateEntry.Thulokata.Loadings.Thulokata", "models.Thulokata"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.Thulokata.GateEntries", "models.GateEntry"),
				},
			},
			LoadingEntry: struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scraps.GateEntry.LoadingEntry", "models.LoadingEntry"),
				Details: struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.LoadingEntry.Details", "models.LoadingEntryDetails"),
					LoadingEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scraps.GateEntry.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.LoadingEntry.GateEntries", "models.GateEntry"),
				},
			},
			Sanokatas: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scraps.GateEntry.Sanokatas", "models.Sanokata"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.Sanokatas.User", "models.User"),
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.Sanokatas.GateEntry", "models.GateEntry"),
				},
			},
			SHooks: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scraps.GateEntry.SHooks", "models.SHook"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntry.SHooks.GateEntry", "models.GateEntry"),
				},
			},
		},
		MultiUnloads: struct {
			field.RelationField
			Scrap struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Scraps.MultiUnloads", "models.ScrapMultiUnload"),
			Scrap: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Scraps.MultiUnloads.Scrap", "models.Scrap"),
			},
		},
		GateEntries: struct {
			field.RelationField
			QualityReport struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}
			Scrap struct {
				field.RelationField
			}
			Thulokata struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			LoadingEntry struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Sanokatas struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}
			SHooks struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Scraps.GateEntries", "models.GateEntry"),
			QualityReport: struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Scraps.GateEntries.QualityReport", "models.QualityReport"),
				Agent: struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.QualityReport.Agent", "models.Agent"),
					QualityReports: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scraps.GateEntries.QualityReport.Agent.QualityReports", "models.QualityReport"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.QualityReport.GateEntry", "models.GateEntry"),
				},
				Details: struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.QualityReport.Details", "models.QualityReportDetails"),
					ScrapTypeInfo: struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Scraps.GateEntries.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
						Details: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Scraps.GateEntries.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
						},
					},
					Report: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scraps.GateEntries.QualityReport.Details.Report", "models.QualityReport"),
					},
				},
			},
			Scrap: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Scraps.GateEntries.Scrap", "models.Scrap"),
			},
			Thulokata: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scraps.GateEntries.Thulokata", "models.Thulokata"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.Thulokata.GateEntry", "models.GateEntry"),
				},
				Loadings: struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.Thulokata.Loadings", "models.ThulokataLoading"),
					Thulokata: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scraps.GateEntries.Thulokata.Loadings.Thulokata", "models.Thulokata"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.Thulokata.GateEntries", "models.GateEntry"),
				},
			},
			LoadingEntry: struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scraps.GateEntries.LoadingEntry", "models.LoadingEntry"),
				Details: struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.LoadingEntry.Details", "models.LoadingEntryDetails"),
					LoadingEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Scraps.GateEntries.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.LoadingEntry.GateEntries", "models.GateEntry"),
				},
			},
			Sanokatas: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scraps.GateEntries.Sanokatas", "models.Sanokata"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.Sanokatas.User", "models.User"),
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.Sanokatas.GateEntry", "models.GateEntry"),
				},
			},
			SHooks: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Scraps.GateEntries.SHooks", "models.SHook"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Scraps.GateEntries.SHooks.GateEntry", "models.GateEntry"),
				},
			},
		},
	}

	_vendors.fillFieldMap()

	return _vendors
}

type vendors struct {
	vendorsDo vendorsDo

	ALL        field.Asterisk
	Id         field.Int64
	PanNo      field.String
	VendorName field.String
	VendorCode field.String
	Active     field.Bool
	Scraps     vendorsHasManyScraps

	fieldMap map[string]field.Expr
}

func (v vendors) Table(newTableName string) *vendors {
	v.vendorsDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vendors) As(alias string) *vendors {
	v.vendorsDo.DO = *(v.vendorsDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vendors) updateTableName(table string) *vendors {
	v.ALL = field.NewAsterisk(table)
	v.Id = field.NewInt64(table, "id")
	v.PanNo = field.NewString(table, "pan_number")
	v.VendorName = field.NewString(table, "supplier_name")
	v.VendorCode = field.NewString(table, "CardCode")
	v.Active = field.NewBool(table, "active")

	v.fillFieldMap()

	return v
}

func (v *vendors) WithContext(ctx context.Context) *vendorsDo { return v.vendorsDo.WithContext(ctx) }

func (v vendors) TableName() string { return v.vendorsDo.TableName() }

func (v vendors) Alias() string { return v.vendorsDo.Alias() }

func (v vendors) Columns(cols ...field.Expr) gen.Columns { return v.vendorsDo.Columns(cols...) }

func (v *vendors) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vendors) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 6)
	v.fieldMap["id"] = v.Id
	v.fieldMap["pan_number"] = v.PanNo
	v.fieldMap["supplier_name"] = v.VendorName
	v.fieldMap["CardCode"] = v.VendorCode
	v.fieldMap["active"] = v.Active

}

func (v vendors) clone(db *gorm.DB) vendors {
	v.vendorsDo.ReplaceConnPool(db.Statement.ConnPool)
	v.Scraps.db = db.Session(&gorm.Session{Initialized: true})
	v.Scraps.db.Statement.ConnPool = db.Statement.ConnPool
	return v
}

func (v vendors) replaceDB(db *gorm.DB) vendors {
	v.vendorsDo.ReplaceDB(db)
	v.Scraps.db = db.Session(&gorm.Session{})
	return v
}

type vendorsHasManyScraps struct {
	db *gorm.DB

	field.RelationField

	Vendor struct {
		field.RelationField
		Scraps struct {
			field.RelationField
		}
	}
	GateEntry struct {
		field.RelationField
		QualityReport struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}
		Scrap struct {
			field.RelationField
		}
		Thulokata struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		LoadingEntry struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Sanokatas struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}
		SHooks struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}
	}
	MultiUnloads struct {
		field.RelationField
		Scrap struct {
			field.RelationField
		}
	}
	GateEntries struct {
		field.RelationField
		QualityReport struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}
		Scrap struct {
			field.RelationField
		}
		Thulokata struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		LoadingEntry struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Sanokatas struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}
		SHooks struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}
	}
}

func (a vendorsHasManyScraps) Where(conds ...field.Expr) *vendorsHasManyScraps {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a vendorsHasManyScraps) WithContext(ctx context.Context) *vendorsHasManyScraps {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a vendorsHasManyScraps) Session(session *gorm.Session) *vendorsHasManyScraps {
	a.db = a.db.Session(session)
	return &a
}

func (a vendorsHasManyScraps) Model(m *models.Vendors) *vendorsHasManyScrapsTx {
	return &vendorsHasManyScrapsTx{a.db.Model(m).Association(a.Name())}
}

func (a vendorsHasManyScraps) Unscoped() *vendorsHasManyScraps {
	a.db = a.db.Unscoped()
	return &a
}

type vendorsHasManyScrapsTx struct{ tx *gorm.Association }

func (a vendorsHasManyScrapsTx) Find() (result []*models.Scrap, err error) {
	return result, a.tx.Find(&result)
}

func (a vendorsHasManyScrapsTx) Append(values ...*models.Scrap) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a vendorsHasManyScrapsTx) Replace(values ...*models.Scrap) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a vendorsHasManyScrapsTx) Delete(values ...*models.Scrap) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a vendorsHasManyScrapsTx) Clear() error {
	return a.tx.Clear()
}

func (a vendorsHasManyScrapsTx) Count() int64 {
	return a.tx.Count()
}

func (a vendorsHasManyScrapsTx) Unscoped() *vendorsHasManyScrapsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type vendorsDo struct{ gen.DO }

func (v vendorsDo) Debug() *vendorsDo {
	return v.withDO(v.DO.Debug())
}

func (v vendorsDo) WithContext(ctx context.Context) *vendorsDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vendorsDo) ReadDB() *vendorsDo {
	return v.Clauses(dbresolver.Read)
}

func (v vendorsDo) WriteDB() *vendorsDo {
	return v.Clauses(dbresolver.Write)
}

func (v vendorsDo) Session(config *gorm.Session) *vendorsDo {
	return v.withDO(v.DO.Session(config))
}

func (v vendorsDo) Clauses(conds ...clause.Expression) *vendorsDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vendorsDo) Returning(value interface{}, columns ...string) *vendorsDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vendorsDo) Not(conds ...gen.Condition) *vendorsDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vendorsDo) Or(conds ...gen.Condition) *vendorsDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vendorsDo) Select(conds ...field.Expr) *vendorsDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vendorsDo) Where(conds ...gen.Condition) *vendorsDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vendorsDo) Order(conds ...field.Expr) *vendorsDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vendorsDo) Distinct(cols ...field.Expr) *vendorsDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vendorsDo) Omit(cols ...field.Expr) *vendorsDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vendorsDo) Join(table schema.Tabler, on ...field.Expr) *vendorsDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vendorsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *vendorsDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vendorsDo) RightJoin(table schema.Tabler, on ...field.Expr) *vendorsDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vendorsDo) Group(cols ...field.Expr) *vendorsDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vendorsDo) Having(conds ...gen.Condition) *vendorsDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vendorsDo) Limit(limit int) *vendorsDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vendorsDo) Offset(offset int) *vendorsDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vendorsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *vendorsDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vendorsDo) Unscoped() *vendorsDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vendorsDo) Create(values ...*models.Vendors) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vendorsDo) CreateInBatches(values []*models.Vendors, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vendorsDo) Save(values ...*models.Vendors) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vendorsDo) First() (*models.Vendors, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Vendors), nil
	}
}

func (v vendorsDo) Take() (*models.Vendors, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Vendors), nil
	}
}

func (v vendorsDo) Last() (*models.Vendors, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Vendors), nil
	}
}

func (v vendorsDo) Find() ([]*models.Vendors, error) {
	result, err := v.DO.Find()
	return result.([]*models.Vendors), err
}

func (v vendorsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Vendors, err error) {
	buf := make([]*models.Vendors, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vendorsDo) FindInBatches(result *[]*models.Vendors, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vendorsDo) Attrs(attrs ...field.AssignExpr) *vendorsDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vendorsDo) Assign(attrs ...field.AssignExpr) *vendorsDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vendorsDo) Joins(fields ...field.RelationField) *vendorsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vendorsDo) Preload(fields ...field.RelationField) *vendorsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vendorsDo) FirstOrInit() (*models.Vendors, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Vendors), nil
	}
}

func (v vendorsDo) FirstOrCreate() (*models.Vendors, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Vendors), nil
	}
}

func (v vendorsDo) FindByPage(offset int, limit int) (result []*models.Vendors, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vendorsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vendorsDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vendorsDo) Delete(models ...*models.Vendors) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vendorsDo) withDO(do gen.Dao) *vendorsDo {
	v.DO = *do.(*gen.DO)
	return v
}
