// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newQualityReportDetails(db *gorm.DB, opts ...gen.DOOption) qualityReportDetails {
	_qualityReportDetails := qualityReportDetails{}

	_qualityReportDetails.qualityReportDetailsDo.UseDB(db, opts...)
	_qualityReportDetails.qualityReportDetailsDo.UseModel(&models.QualityReportDetails{})

	tableName := _qualityReportDetails.qualityReportDetailsDo.TableName()
	_qualityReportDetails.ALL = field.NewAsterisk(tableName)
	_qualityReportDetails.ID = field.NewInt64(tableName, "id")
	_qualityReportDetails.SslSno = field.NewString(tableName, "ssl_sno")
	_qualityReportDetails.ScrapType = field.NewString(tableName, "scrap_type")
	_qualityReportDetails.Percentage = field.NewFloat64(tableName, "percentage")
	_qualityReportDetails.Qty = field.NewFloat64(tableName, "qty")
	_qualityReportDetails.Rate = field.NewFloat64(tableName, "rate")
	_qualityReportDetails.Amount = field.NewFloat64(tableName, "amount")
	_qualityReportDetails.Report = qualityReportDetailsHasOneReport{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Report", "models.QualityReport"),
		Agent: struct {
			field.RelationField
			QualityReports struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Report.Agent", "models.Agent"),
			QualityReports: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Report.Agent.QualityReports", "models.QualityReport"),
			},
		},
		GateEntry: struct {
			field.RelationField
			QualityReport struct {
				field.RelationField
			}
			Scrap struct {
				field.RelationField
				Vendor struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				MultiUnloads struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Thulokata struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			LoadingEntry struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Sanokatas struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}
			SHooks struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Report.GateEntry", "models.GateEntry"),
			QualityReport: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Report.GateEntry.QualityReport", "models.QualityReport"),
			},
			Scrap: struct {
				field.RelationField
				Vendor struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				MultiUnloads struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Report.GateEntry.Scrap", "models.Scrap"),
				Vendor: struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Report.GateEntry.Scrap.Vendor", "models.Vendors"),
					Scraps: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Report.GateEntry.Scrap.Vendor.Scraps", "models.Scrap"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Report.GateEntry.Scrap.GateEntry", "models.GateEntry"),
				},
				MultiUnloads: struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Report.GateEntry.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
					Scrap: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Report.GateEntry.Scrap.MultiUnloads.Scrap", "models.Scrap"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Report.GateEntry.Scrap.GateEntries", "models.GateEntry"),
				},
			},
			Thulokata: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Report.GateEntry.Thulokata", "models.Thulokata"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Report.GateEntry.Thulokata.GateEntry", "models.GateEntry"),
				},
				Loadings: struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Report.GateEntry.Thulokata.Loadings", "models.ThulokataLoading"),
					Thulokata: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Report.GateEntry.Thulokata.Loadings.Thulokata", "models.Thulokata"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Report.GateEntry.Thulokata.GateEntries", "models.GateEntry"),
				},
			},
			LoadingEntry: struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Report.GateEntry.LoadingEntry", "models.LoadingEntry"),
				Details: struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Report.GateEntry.LoadingEntry.Details", "models.LoadingEntryDetails"),
					LoadingEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Report.GateEntry.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Report.GateEntry.LoadingEntry.GateEntries", "models.GateEntry"),
				},
			},
			Sanokatas: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Report.GateEntry.Sanokatas", "models.Sanokata"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Report.GateEntry.Sanokatas.User", "models.User"),
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Report.GateEntry.Sanokatas.GateEntry", "models.GateEntry"),
				},
			},
			SHooks: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Report.GateEntry.SHooks", "models.SHook"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Report.GateEntry.SHooks.GateEntry", "models.GateEntry"),
				},
			},
		},
		Details: struct {
			field.RelationField
			ScrapTypeInfo struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}
			Report struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Report.Details", "models.QualityReportDetails"),
			ScrapTypeInfo: struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Report.Details.ScrapTypeInfo", "models.ScrapType"),
				Details: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Report.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
				},
			},
			Report: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Report.Details.Report", "models.QualityReport"),
			},
		},
	}

	_qualityReportDetails.ScrapTypeInfo = qualityReportDetailsBelongsToScrapTypeInfo{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ScrapTypeInfo", "models.ScrapType"),
		Details: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ScrapTypeInfo.Details", "models.QualityReportDetails"),
		},
	}

	_qualityReportDetails.fillFieldMap()

	return _qualityReportDetails
}

type qualityReportDetails struct {
	qualityReportDetailsDo qualityReportDetailsDo

	ALL        field.Asterisk
	ID         field.Int64
	SslSno     field.String
	ScrapType  field.String
	Percentage field.Float64
	Qty        field.Float64
	Rate       field.Float64
	Amount     field.Float64
	Report     qualityReportDetailsHasOneReport

	ScrapTypeInfo qualityReportDetailsBelongsToScrapTypeInfo

	fieldMap map[string]field.Expr
}

func (q qualityReportDetails) Table(newTableName string) *qualityReportDetails {
	q.qualityReportDetailsDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q qualityReportDetails) As(alias string) *qualityReportDetails {
	q.qualityReportDetailsDo.DO = *(q.qualityReportDetailsDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *qualityReportDetails) updateTableName(table string) *qualityReportDetails {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewInt64(table, "id")
	q.SslSno = field.NewString(table, "ssl_sno")
	q.ScrapType = field.NewString(table, "scrap_type")
	q.Percentage = field.NewFloat64(table, "percentage")
	q.Qty = field.NewFloat64(table, "qty")
	q.Rate = field.NewFloat64(table, "rate")
	q.Amount = field.NewFloat64(table, "amount")

	q.fillFieldMap()

	return q
}

func (q *qualityReportDetails) WithContext(ctx context.Context) *qualityReportDetailsDo {
	return q.qualityReportDetailsDo.WithContext(ctx)
}

func (q qualityReportDetails) TableName() string { return q.qualityReportDetailsDo.TableName() }

func (q qualityReportDetails) Alias() string { return q.qualityReportDetailsDo.Alias() }

func (q qualityReportDetails) Columns(cols ...field.Expr) gen.Columns {
	return q.qualityReportDetailsDo.Columns(cols...)
}

func (q *qualityReportDetails) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *qualityReportDetails) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 9)
	q.fieldMap["id"] = q.ID
	q.fieldMap["ssl_sno"] = q.SslSno
	q.fieldMap["scrap_type"] = q.ScrapType
	q.fieldMap["percentage"] = q.Percentage
	q.fieldMap["qty"] = q.Qty
	q.fieldMap["rate"] = q.Rate
	q.fieldMap["amount"] = q.Amount

}

func (q qualityReportDetails) clone(db *gorm.DB) qualityReportDetails {
	q.qualityReportDetailsDo.ReplaceConnPool(db.Statement.ConnPool)
	q.Report.db = db.Session(&gorm.Session{Initialized: true})
	q.Report.db.Statement.ConnPool = db.Statement.ConnPool
	q.ScrapTypeInfo.db = db.Session(&gorm.Session{Initialized: true})
	q.ScrapTypeInfo.db.Statement.ConnPool = db.Statement.ConnPool
	return q
}

func (q qualityReportDetails) replaceDB(db *gorm.DB) qualityReportDetails {
	q.qualityReportDetailsDo.ReplaceDB(db)
	q.Report.db = db.Session(&gorm.Session{})
	q.ScrapTypeInfo.db = db.Session(&gorm.Session{})
	return q
}

type qualityReportDetailsHasOneReport struct {
	db *gorm.DB

	field.RelationField

	Agent struct {
		field.RelationField
		QualityReports struct {
			field.RelationField
		}
	}
	GateEntry struct {
		field.RelationField
		QualityReport struct {
			field.RelationField
		}
		Scrap struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Thulokata struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		LoadingEntry struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Sanokatas struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}
		SHooks struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}
	}
	Details struct {
		field.RelationField
		ScrapTypeInfo struct {
			field.RelationField
			Details struct {
				field.RelationField
			}
		}
		Report struct {
			field.RelationField
		}
	}
}

func (a qualityReportDetailsHasOneReport) Where(conds ...field.Expr) *qualityReportDetailsHasOneReport {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a qualityReportDetailsHasOneReport) WithContext(ctx context.Context) *qualityReportDetailsHasOneReport {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a qualityReportDetailsHasOneReport) Session(session *gorm.Session) *qualityReportDetailsHasOneReport {
	a.db = a.db.Session(session)
	return &a
}

func (a qualityReportDetailsHasOneReport) Model(m *models.QualityReportDetails) *qualityReportDetailsHasOneReportTx {
	return &qualityReportDetailsHasOneReportTx{a.db.Model(m).Association(a.Name())}
}

func (a qualityReportDetailsHasOneReport) Unscoped() *qualityReportDetailsHasOneReport {
	a.db = a.db.Unscoped()
	return &a
}

type qualityReportDetailsHasOneReportTx struct{ tx *gorm.Association }

func (a qualityReportDetailsHasOneReportTx) Find() (result *models.QualityReport, err error) {
	return result, a.tx.Find(&result)
}

func (a qualityReportDetailsHasOneReportTx) Append(values ...*models.QualityReport) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a qualityReportDetailsHasOneReportTx) Replace(values ...*models.QualityReport) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a qualityReportDetailsHasOneReportTx) Delete(values ...*models.QualityReport) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a qualityReportDetailsHasOneReportTx) Clear() error {
	return a.tx.Clear()
}

func (a qualityReportDetailsHasOneReportTx) Count() int64 {
	return a.tx.Count()
}

func (a qualityReportDetailsHasOneReportTx) Unscoped() *qualityReportDetailsHasOneReportTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type qualityReportDetailsBelongsToScrapTypeInfo struct {
	db *gorm.DB

	field.RelationField

	Details struct {
		field.RelationField
	}
}

func (a qualityReportDetailsBelongsToScrapTypeInfo) Where(conds ...field.Expr) *qualityReportDetailsBelongsToScrapTypeInfo {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a qualityReportDetailsBelongsToScrapTypeInfo) WithContext(ctx context.Context) *qualityReportDetailsBelongsToScrapTypeInfo {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a qualityReportDetailsBelongsToScrapTypeInfo) Session(session *gorm.Session) *qualityReportDetailsBelongsToScrapTypeInfo {
	a.db = a.db.Session(session)
	return &a
}

func (a qualityReportDetailsBelongsToScrapTypeInfo) Model(m *models.QualityReportDetails) *qualityReportDetailsBelongsToScrapTypeInfoTx {
	return &qualityReportDetailsBelongsToScrapTypeInfoTx{a.db.Model(m).Association(a.Name())}
}

func (a qualityReportDetailsBelongsToScrapTypeInfo) Unscoped() *qualityReportDetailsBelongsToScrapTypeInfo {
	a.db = a.db.Unscoped()
	return &a
}

type qualityReportDetailsBelongsToScrapTypeInfoTx struct{ tx *gorm.Association }

func (a qualityReportDetailsBelongsToScrapTypeInfoTx) Find() (result *models.ScrapType, err error) {
	return result, a.tx.Find(&result)
}

func (a qualityReportDetailsBelongsToScrapTypeInfoTx) Append(values ...*models.ScrapType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a qualityReportDetailsBelongsToScrapTypeInfoTx) Replace(values ...*models.ScrapType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a qualityReportDetailsBelongsToScrapTypeInfoTx) Delete(values ...*models.ScrapType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a qualityReportDetailsBelongsToScrapTypeInfoTx) Clear() error {
	return a.tx.Clear()
}

func (a qualityReportDetailsBelongsToScrapTypeInfoTx) Count() int64 {
	return a.tx.Count()
}

func (a qualityReportDetailsBelongsToScrapTypeInfoTx) Unscoped() *qualityReportDetailsBelongsToScrapTypeInfoTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type qualityReportDetailsDo struct{ gen.DO }

func (q qualityReportDetailsDo) Debug() *qualityReportDetailsDo {
	return q.withDO(q.DO.Debug())
}

func (q qualityReportDetailsDo) WithContext(ctx context.Context) *qualityReportDetailsDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q qualityReportDetailsDo) ReadDB() *qualityReportDetailsDo {
	return q.Clauses(dbresolver.Read)
}

func (q qualityReportDetailsDo) WriteDB() *qualityReportDetailsDo {
	return q.Clauses(dbresolver.Write)
}

func (q qualityReportDetailsDo) Session(config *gorm.Session) *qualityReportDetailsDo {
	return q.withDO(q.DO.Session(config))
}

func (q qualityReportDetailsDo) Clauses(conds ...clause.Expression) *qualityReportDetailsDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q qualityReportDetailsDo) Returning(value interface{}, columns ...string) *qualityReportDetailsDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q qualityReportDetailsDo) Not(conds ...gen.Condition) *qualityReportDetailsDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q qualityReportDetailsDo) Or(conds ...gen.Condition) *qualityReportDetailsDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q qualityReportDetailsDo) Select(conds ...field.Expr) *qualityReportDetailsDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q qualityReportDetailsDo) Where(conds ...gen.Condition) *qualityReportDetailsDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q qualityReportDetailsDo) Order(conds ...field.Expr) *qualityReportDetailsDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q qualityReportDetailsDo) Distinct(cols ...field.Expr) *qualityReportDetailsDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q qualityReportDetailsDo) Omit(cols ...field.Expr) *qualityReportDetailsDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q qualityReportDetailsDo) Join(table schema.Tabler, on ...field.Expr) *qualityReportDetailsDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q qualityReportDetailsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *qualityReportDetailsDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q qualityReportDetailsDo) RightJoin(table schema.Tabler, on ...field.Expr) *qualityReportDetailsDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q qualityReportDetailsDo) Group(cols ...field.Expr) *qualityReportDetailsDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q qualityReportDetailsDo) Having(conds ...gen.Condition) *qualityReportDetailsDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q qualityReportDetailsDo) Limit(limit int) *qualityReportDetailsDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q qualityReportDetailsDo) Offset(offset int) *qualityReportDetailsDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q qualityReportDetailsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *qualityReportDetailsDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q qualityReportDetailsDo) Unscoped() *qualityReportDetailsDo {
	return q.withDO(q.DO.Unscoped())
}

func (q qualityReportDetailsDo) Create(values ...*models.QualityReportDetails) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q qualityReportDetailsDo) CreateInBatches(values []*models.QualityReportDetails, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q qualityReportDetailsDo) Save(values ...*models.QualityReportDetails) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q qualityReportDetailsDo) First() (*models.QualityReportDetails, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.QualityReportDetails), nil
	}
}

func (q qualityReportDetailsDo) Take() (*models.QualityReportDetails, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.QualityReportDetails), nil
	}
}

func (q qualityReportDetailsDo) Last() (*models.QualityReportDetails, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.QualityReportDetails), nil
	}
}

func (q qualityReportDetailsDo) Find() ([]*models.QualityReportDetails, error) {
	result, err := q.DO.Find()
	return result.([]*models.QualityReportDetails), err
}

func (q qualityReportDetailsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.QualityReportDetails, err error) {
	buf := make([]*models.QualityReportDetails, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q qualityReportDetailsDo) FindInBatches(result *[]*models.QualityReportDetails, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q qualityReportDetailsDo) Attrs(attrs ...field.AssignExpr) *qualityReportDetailsDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q qualityReportDetailsDo) Assign(attrs ...field.AssignExpr) *qualityReportDetailsDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q qualityReportDetailsDo) Joins(fields ...field.RelationField) *qualityReportDetailsDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q qualityReportDetailsDo) Preload(fields ...field.RelationField) *qualityReportDetailsDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q qualityReportDetailsDo) FirstOrInit() (*models.QualityReportDetails, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.QualityReportDetails), nil
	}
}

func (q qualityReportDetailsDo) FirstOrCreate() (*models.QualityReportDetails, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.QualityReportDetails), nil
	}
}

func (q qualityReportDetailsDo) FindByPage(offset int, limit int) (result []*models.QualityReportDetails, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q qualityReportDetailsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q qualityReportDetailsDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q qualityReportDetailsDo) Delete(models ...*models.QualityReportDetails) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *qualityReportDetailsDo) withDO(do gen.Dao) *qualityReportDetailsDo {
	q.DO = *do.(*gen.DO)
	return q
}
