// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newQualityReport(db *gorm.DB, opts ...gen.DOOption) qualityReport {
	_qualityReport := qualityReport{}

	_qualityReport.qualityReportDo.UseDB(db, opts...)
	_qualityReport.qualityReportDo.UseModel(&models.QualityReport{})

	tableName := _qualityReport.qualityReportDo.TableName()
	_qualityReport.ALL = field.NewAsterisk(tableName)
	_qualityReport.SslSno = field.NewString(tableName, "ssl_sno")
	_qualityReport.QualityId = field.NewString(tableName, "quality_id")
	_qualityReport.TokenNo = field.NewString(tableName, "token_no")
	_qualityReport.Miti = field.NewString(tableName, "miti")
	_qualityReport.AgentName = field.NewString(tableName, "agent_name")
	_qualityReport.BillingRate = field.NewFloat64(tableName, "billing_rate")
	_qualityReport.EndCutDetails = field.NewString(tableName, "end_cut_details")
	_qualityReport.OverSizeDetails = field.NewString(tableName, "over_size_details")
	_qualityReport.Bags = field.NewString(tableName, "bags")
	_qualityReport.TotalBagsWeight = field.NewFloat64(tableName, "total_bags_weight")
	_qualityReport.CreatedAt = field.NewString(tableName, "created_at")
	_qualityReport.Updated_at = field.NewString(tableName, "updated_at")
	_qualityReport.PoCreated = field.NewBool(tableName, "po_created")
	_qualityReport.PostingDate = field.NewString(tableName, "posting_date")
	_qualityReport.Details = qualityReportHasManyDetails{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Details", "models.QualityReportDetails"),
		ScrapTypeInfo: struct {
			field.RelationField
			Details struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Details.ScrapTypeInfo", "models.ScrapType"),
			Details: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
			},
		},
		Report: struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
				QualityReport struct {
					field.RelationField
				}
				Scrap struct {
					field.RelationField
					Vendor struct {
						field.RelationField
						Scraps struct {
							field.RelationField
						}
					}
					GateEntry struct {
						field.RelationField
					}
					MultiUnloads struct {
						field.RelationField
						Scrap struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}
				Thulokata struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
					Loadings struct {
						field.RelationField
						Thulokata struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}
				LoadingEntry struct {
					field.RelationField
					Details struct {
						field.RelationField
						LoadingEntry struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}
				Sanokatas struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					GateEntry struct {
						field.RelationField
					}
				}
				SHooks struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
				}
			}
			Details struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Details.Report", "models.QualityReport"),
			Agent: struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Details.Report.Agent", "models.Agent"),
				QualityReports: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Details.Report.Agent.QualityReports", "models.QualityReport"),
				},
			},
			GateEntry: struct {
				field.RelationField
				QualityReport struct {
					field.RelationField
				}
				Scrap struct {
					field.RelationField
					Vendor struct {
						field.RelationField
						Scraps struct {
							field.RelationField
						}
					}
					GateEntry struct {
						field.RelationField
					}
					MultiUnloads struct {
						field.RelationField
						Scrap struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}
				Thulokata struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
					Loadings struct {
						field.RelationField
						Thulokata struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}
				LoadingEntry struct {
					field.RelationField
					Details struct {
						field.RelationField
						LoadingEntry struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}
				Sanokatas struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					GateEntry struct {
						field.RelationField
					}
				}
				SHooks struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Details.Report.GateEntry", "models.GateEntry"),
				QualityReport: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Details.Report.GateEntry.QualityReport", "models.QualityReport"),
				},
				Scrap: struct {
					field.RelationField
					Vendor struct {
						field.RelationField
						Scraps struct {
							field.RelationField
						}
					}
					GateEntry struct {
						field.RelationField
					}
					MultiUnloads struct {
						field.RelationField
						Scrap struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Details.Report.GateEntry.Scrap", "models.Scrap"),
					Vendor: struct {
						field.RelationField
						Scraps struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.Scrap.Vendor", "models.Vendors"),
						Scraps: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Details.Report.GateEntry.Scrap.Vendor.Scraps", "models.Scrap"),
						},
					},
					GateEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.Scrap.GateEntry", "models.GateEntry"),
					},
					MultiUnloads: struct {
						field.RelationField
						Scrap struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
						Scrap: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Details.Report.GateEntry.Scrap.MultiUnloads.Scrap", "models.Scrap"),
						},
					},
					GateEntries: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.Scrap.GateEntries", "models.GateEntry"),
					},
				},
				Thulokata: struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
					Loadings struct {
						field.RelationField
						Thulokata struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Details.Report.GateEntry.Thulokata", "models.Thulokata"),
					GateEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.Thulokata.GateEntry", "models.GateEntry"),
					},
					Loadings: struct {
						field.RelationField
						Thulokata struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.Thulokata.Loadings", "models.ThulokataLoading"),
						Thulokata: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Details.Report.GateEntry.Thulokata.Loadings.Thulokata", "models.Thulokata"),
						},
					},
					GateEntries: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.Thulokata.GateEntries", "models.GateEntry"),
					},
				},
				LoadingEntry: struct {
					field.RelationField
					Details struct {
						field.RelationField
						LoadingEntry struct {
							field.RelationField
						}
					}
					GateEntries struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Details.Report.GateEntry.LoadingEntry", "models.LoadingEntry"),
					Details: struct {
						field.RelationField
						LoadingEntry struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.LoadingEntry.Details", "models.LoadingEntryDetails"),
						LoadingEntry: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Details.Report.GateEntry.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
						},
					},
					GateEntries: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.LoadingEntry.GateEntries", "models.GateEntry"),
					},
				},
				Sanokatas: struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					GateEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Details.Report.GateEntry.Sanokatas", "models.Sanokata"),
					User: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.Sanokatas.User", "models.User"),
					},
					GateEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.Sanokatas.GateEntry", "models.GateEntry"),
					},
				},
				SHooks: struct {
					field.RelationField
					GateEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Details.Report.GateEntry.SHooks", "models.SHook"),
					GateEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Details.Report.GateEntry.SHooks.GateEntry", "models.GateEntry"),
					},
				},
			},
			Details: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Details.Report.Details", "models.QualityReportDetails"),
			},
		},
	}

	_qualityReport.Agent = qualityReportBelongsToAgent{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Agent", "models.Agent"),
		QualityReports: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Agent.QualityReports", "models.QualityReport"),
		},
	}

	_qualityReport.GateEntry = qualityReportBelongsToGateEntry{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("GateEntry", "models.GateEntry"),
		QualityReport: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("GateEntry.QualityReport", "models.QualityReport"),
		},
		Scrap: struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Scrap", "models.Scrap"),
			Vendor: struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.Vendor", "models.Vendors"),
				Scraps: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Scrap.Vendor.Scraps", "models.Scrap"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.GateEntry", "models.GateEntry"),
			},
			MultiUnloads: struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
				Scrap: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Scrap.MultiUnloads.Scrap", "models.Scrap"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.GateEntries", "models.GateEntry"),
			},
		},
		Thulokata: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Thulokata", "models.Thulokata"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.GateEntry", "models.GateEntry"),
			},
			Loadings: struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.Loadings", "models.ThulokataLoading"),
				Thulokata: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Thulokata.Loadings.Thulokata", "models.Thulokata"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.GateEntries", "models.GateEntry"),
			},
		},
		LoadingEntry: struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.LoadingEntry", "models.LoadingEntry"),
			Details: struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.LoadingEntry.Details", "models.LoadingEntryDetails"),
				LoadingEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.LoadingEntry.GateEntries", "models.GateEntry"),
			},
		},
		Sanokatas: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Sanokatas", "models.Sanokata"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Sanokatas.User", "models.User"),
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Sanokatas.GateEntry", "models.GateEntry"),
			},
		},
		SHooks: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.SHooks", "models.SHook"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.SHooks.GateEntry", "models.GateEntry"),
			},
		},
	}

	_qualityReport.fillFieldMap()

	return _qualityReport
}

type qualityReport struct {
	qualityReportDo qualityReportDo

	ALL             field.Asterisk
	SslSno          field.String
	QualityId       field.String
	TokenNo         field.String
	Miti            field.String
	AgentName       field.String
	BillingRate     field.Float64
	EndCutDetails   field.String
	OverSizeDetails field.String
	Bags            field.String
	TotalBagsWeight field.Float64
	CreatedAt       field.String
	Updated_at      field.String
	PoCreated       field.Bool
	PostingDate     field.String
	Details         qualityReportHasManyDetails

	Agent qualityReportBelongsToAgent

	GateEntry qualityReportBelongsToGateEntry

	fieldMap map[string]field.Expr
}

func (q qualityReport) Table(newTableName string) *qualityReport {
	q.qualityReportDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q qualityReport) As(alias string) *qualityReport {
	q.qualityReportDo.DO = *(q.qualityReportDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *qualityReport) updateTableName(table string) *qualityReport {
	q.ALL = field.NewAsterisk(table)
	q.SslSno = field.NewString(table, "ssl_sno")
	q.QualityId = field.NewString(table, "quality_id")
	q.TokenNo = field.NewString(table, "token_no")
	q.Miti = field.NewString(table, "miti")
	q.AgentName = field.NewString(table, "agent_name")
	q.BillingRate = field.NewFloat64(table, "billing_rate")
	q.EndCutDetails = field.NewString(table, "end_cut_details")
	q.OverSizeDetails = field.NewString(table, "over_size_details")
	q.Bags = field.NewString(table, "bags")
	q.TotalBagsWeight = field.NewFloat64(table, "total_bags_weight")
	q.CreatedAt = field.NewString(table, "created_at")
	q.Updated_at = field.NewString(table, "updated_at")
	q.PoCreated = field.NewBool(table, "po_created")
	q.PostingDate = field.NewString(table, "posting_date")

	q.fillFieldMap()

	return q
}

func (q *qualityReport) WithContext(ctx context.Context) *qualityReportDo {
	return q.qualityReportDo.WithContext(ctx)
}

func (q qualityReport) TableName() string { return q.qualityReportDo.TableName() }

func (q qualityReport) Alias() string { return q.qualityReportDo.Alias() }

func (q qualityReport) Columns(cols ...field.Expr) gen.Columns {
	return q.qualityReportDo.Columns(cols...)
}

func (q *qualityReport) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *qualityReport) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 17)
	q.fieldMap["ssl_sno"] = q.SslSno
	q.fieldMap["quality_id"] = q.QualityId
	q.fieldMap["token_no"] = q.TokenNo
	q.fieldMap["miti"] = q.Miti
	q.fieldMap["agent_name"] = q.AgentName
	q.fieldMap["billing_rate"] = q.BillingRate
	q.fieldMap["end_cut_details"] = q.EndCutDetails
	q.fieldMap["over_size_details"] = q.OverSizeDetails
	q.fieldMap["bags"] = q.Bags
	q.fieldMap["total_bags_weight"] = q.TotalBagsWeight
	q.fieldMap["created_at"] = q.CreatedAt
	q.fieldMap["updated_at"] = q.Updated_at
	q.fieldMap["po_created"] = q.PoCreated
	q.fieldMap["posting_date"] = q.PostingDate

}

func (q qualityReport) clone(db *gorm.DB) qualityReport {
	q.qualityReportDo.ReplaceConnPool(db.Statement.ConnPool)
	q.Details.db = db.Session(&gorm.Session{Initialized: true})
	q.Details.db.Statement.ConnPool = db.Statement.ConnPool
	q.Agent.db = db.Session(&gorm.Session{Initialized: true})
	q.Agent.db.Statement.ConnPool = db.Statement.ConnPool
	q.GateEntry.db = db.Session(&gorm.Session{Initialized: true})
	q.GateEntry.db.Statement.ConnPool = db.Statement.ConnPool
	return q
}

func (q qualityReport) replaceDB(db *gorm.DB) qualityReport {
	q.qualityReportDo.ReplaceDB(db)
	q.Details.db = db.Session(&gorm.Session{})
	q.Agent.db = db.Session(&gorm.Session{})
	q.GateEntry.db = db.Session(&gorm.Session{})
	return q
}

type qualityReportHasManyDetails struct {
	db *gorm.DB

	field.RelationField

	ScrapTypeInfo struct {
		field.RelationField
		Details struct {
			field.RelationField
		}
	}
	Report struct {
		field.RelationField
		Agent struct {
			field.RelationField
			QualityReports struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
			QualityReport struct {
				field.RelationField
			}
			Scrap struct {
				field.RelationField
				Vendor struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				MultiUnloads struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Thulokata struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
				Loadings struct {
					field.RelationField
					Thulokata struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			LoadingEntry struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Sanokatas struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}
			SHooks struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}
		}
		Details struct {
			field.RelationField
		}
	}
}

func (a qualityReportHasManyDetails) Where(conds ...field.Expr) *qualityReportHasManyDetails {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a qualityReportHasManyDetails) WithContext(ctx context.Context) *qualityReportHasManyDetails {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a qualityReportHasManyDetails) Session(session *gorm.Session) *qualityReportHasManyDetails {
	a.db = a.db.Session(session)
	return &a
}

func (a qualityReportHasManyDetails) Model(m *models.QualityReport) *qualityReportHasManyDetailsTx {
	return &qualityReportHasManyDetailsTx{a.db.Model(m).Association(a.Name())}
}

func (a qualityReportHasManyDetails) Unscoped() *qualityReportHasManyDetails {
	a.db = a.db.Unscoped()
	return &a
}

type qualityReportHasManyDetailsTx struct{ tx *gorm.Association }

func (a qualityReportHasManyDetailsTx) Find() (result []*models.QualityReportDetails, err error) {
	return result, a.tx.Find(&result)
}

func (a qualityReportHasManyDetailsTx) Append(values ...*models.QualityReportDetails) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a qualityReportHasManyDetailsTx) Replace(values ...*models.QualityReportDetails) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a qualityReportHasManyDetailsTx) Delete(values ...*models.QualityReportDetails) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a qualityReportHasManyDetailsTx) Clear() error {
	return a.tx.Clear()
}

func (a qualityReportHasManyDetailsTx) Count() int64 {
	return a.tx.Count()
}

func (a qualityReportHasManyDetailsTx) Unscoped() *qualityReportHasManyDetailsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type qualityReportBelongsToAgent struct {
	db *gorm.DB

	field.RelationField

	QualityReports struct {
		field.RelationField
	}
}

func (a qualityReportBelongsToAgent) Where(conds ...field.Expr) *qualityReportBelongsToAgent {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a qualityReportBelongsToAgent) WithContext(ctx context.Context) *qualityReportBelongsToAgent {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a qualityReportBelongsToAgent) Session(session *gorm.Session) *qualityReportBelongsToAgent {
	a.db = a.db.Session(session)
	return &a
}

func (a qualityReportBelongsToAgent) Model(m *models.QualityReport) *qualityReportBelongsToAgentTx {
	return &qualityReportBelongsToAgentTx{a.db.Model(m).Association(a.Name())}
}

func (a qualityReportBelongsToAgent) Unscoped() *qualityReportBelongsToAgent {
	a.db = a.db.Unscoped()
	return &a
}

type qualityReportBelongsToAgentTx struct{ tx *gorm.Association }

func (a qualityReportBelongsToAgentTx) Find() (result *models.Agent, err error) {
	return result, a.tx.Find(&result)
}

func (a qualityReportBelongsToAgentTx) Append(values ...*models.Agent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a qualityReportBelongsToAgentTx) Replace(values ...*models.Agent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a qualityReportBelongsToAgentTx) Delete(values ...*models.Agent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a qualityReportBelongsToAgentTx) Clear() error {
	return a.tx.Clear()
}

func (a qualityReportBelongsToAgentTx) Count() int64 {
	return a.tx.Count()
}

func (a qualityReportBelongsToAgentTx) Unscoped() *qualityReportBelongsToAgentTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type qualityReportBelongsToGateEntry struct {
	db *gorm.DB

	field.RelationField

	QualityReport struct {
		field.RelationField
	}
	Scrap struct {
		field.RelationField
		Vendor struct {
			field.RelationField
			Scraps struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		MultiUnloads struct {
			field.RelationField
			Scrap struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Thulokata struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
		Loadings struct {
			field.RelationField
			Thulokata struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	LoadingEntry struct {
		field.RelationField
		Details struct {
			field.RelationField
			LoadingEntry struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Sanokatas struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		GateEntry struct {
			field.RelationField
		}
	}
	SHooks struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
	}
}

func (a qualityReportBelongsToGateEntry) Where(conds ...field.Expr) *qualityReportBelongsToGateEntry {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a qualityReportBelongsToGateEntry) WithContext(ctx context.Context) *qualityReportBelongsToGateEntry {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a qualityReportBelongsToGateEntry) Session(session *gorm.Session) *qualityReportBelongsToGateEntry {
	a.db = a.db.Session(session)
	return &a
}

func (a qualityReportBelongsToGateEntry) Model(m *models.QualityReport) *qualityReportBelongsToGateEntryTx {
	return &qualityReportBelongsToGateEntryTx{a.db.Model(m).Association(a.Name())}
}

func (a qualityReportBelongsToGateEntry) Unscoped() *qualityReportBelongsToGateEntry {
	a.db = a.db.Unscoped()
	return &a
}

type qualityReportBelongsToGateEntryTx struct{ tx *gorm.Association }

func (a qualityReportBelongsToGateEntryTx) Find() (result *models.GateEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a qualityReportBelongsToGateEntryTx) Append(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a qualityReportBelongsToGateEntryTx) Replace(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a qualityReportBelongsToGateEntryTx) Delete(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a qualityReportBelongsToGateEntryTx) Clear() error {
	return a.tx.Clear()
}

func (a qualityReportBelongsToGateEntryTx) Count() int64 {
	return a.tx.Count()
}

func (a qualityReportBelongsToGateEntryTx) Unscoped() *qualityReportBelongsToGateEntryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type qualityReportDo struct{ gen.DO }

func (q qualityReportDo) Debug() *qualityReportDo {
	return q.withDO(q.DO.Debug())
}

func (q qualityReportDo) WithContext(ctx context.Context) *qualityReportDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q qualityReportDo) ReadDB() *qualityReportDo {
	return q.Clauses(dbresolver.Read)
}

func (q qualityReportDo) WriteDB() *qualityReportDo {
	return q.Clauses(dbresolver.Write)
}

func (q qualityReportDo) Session(config *gorm.Session) *qualityReportDo {
	return q.withDO(q.DO.Session(config))
}

func (q qualityReportDo) Clauses(conds ...clause.Expression) *qualityReportDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q qualityReportDo) Returning(value interface{}, columns ...string) *qualityReportDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q qualityReportDo) Not(conds ...gen.Condition) *qualityReportDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q qualityReportDo) Or(conds ...gen.Condition) *qualityReportDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q qualityReportDo) Select(conds ...field.Expr) *qualityReportDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q qualityReportDo) Where(conds ...gen.Condition) *qualityReportDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q qualityReportDo) Order(conds ...field.Expr) *qualityReportDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q qualityReportDo) Distinct(cols ...field.Expr) *qualityReportDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q qualityReportDo) Omit(cols ...field.Expr) *qualityReportDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q qualityReportDo) Join(table schema.Tabler, on ...field.Expr) *qualityReportDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q qualityReportDo) LeftJoin(table schema.Tabler, on ...field.Expr) *qualityReportDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q qualityReportDo) RightJoin(table schema.Tabler, on ...field.Expr) *qualityReportDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q qualityReportDo) Group(cols ...field.Expr) *qualityReportDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q qualityReportDo) Having(conds ...gen.Condition) *qualityReportDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q qualityReportDo) Limit(limit int) *qualityReportDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q qualityReportDo) Offset(offset int) *qualityReportDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q qualityReportDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *qualityReportDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q qualityReportDo) Unscoped() *qualityReportDo {
	return q.withDO(q.DO.Unscoped())
}

func (q qualityReportDo) Create(values ...*models.QualityReport) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q qualityReportDo) CreateInBatches(values []*models.QualityReport, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q qualityReportDo) Save(values ...*models.QualityReport) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q qualityReportDo) First() (*models.QualityReport, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.QualityReport), nil
	}
}

func (q qualityReportDo) Take() (*models.QualityReport, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.QualityReport), nil
	}
}

func (q qualityReportDo) Last() (*models.QualityReport, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.QualityReport), nil
	}
}

func (q qualityReportDo) Find() ([]*models.QualityReport, error) {
	result, err := q.DO.Find()
	return result.([]*models.QualityReport), err
}

func (q qualityReportDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.QualityReport, err error) {
	buf := make([]*models.QualityReport, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q qualityReportDo) FindInBatches(result *[]*models.QualityReport, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q qualityReportDo) Attrs(attrs ...field.AssignExpr) *qualityReportDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q qualityReportDo) Assign(attrs ...field.AssignExpr) *qualityReportDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q qualityReportDo) Joins(fields ...field.RelationField) *qualityReportDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q qualityReportDo) Preload(fields ...field.RelationField) *qualityReportDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q qualityReportDo) FirstOrInit() (*models.QualityReport, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.QualityReport), nil
	}
}

func (q qualityReportDo) FirstOrCreate() (*models.QualityReport, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.QualityReport), nil
	}
}

func (q qualityReportDo) FindByPage(offset int, limit int) (result []*models.QualityReport, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q qualityReportDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q qualityReportDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q qualityReportDo) Delete(models ...*models.QualityReport) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *qualityReportDo) withDO(do gen.Dao) *qualityReportDo {
	q.DO = *do.(*gen.DO)
	return q
}
