// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newSanokata(db *gorm.DB, opts ...gen.DOOption) sanokata {
	_sanokata := sanokata{}

	_sanokata.sanokataDo.UseDB(db, opts...)
	_sanokata.sanokataDo.UseModel(&models.Sanokata{})

	tableName := _sanokata.sanokataDo.TableName()
	_sanokata.ALL = field.NewAsterisk(tableName)
	_sanokata.Id = field.NewInt64(tableName, "id")
	_sanokata.DocumentNo = field.NewString(tableName, "internal_numbering")
	_sanokata.ShippingAddress = field.NewString(tableName, "shipping_address")
	_sanokata.LoadingDate = field.NewString(tableName, "order_date")
	_sanokata.Code = field.NewString(tableName, "code")
	_sanokata.Lot = field.NewString(tableName, "lot")
	_sanokata.SizeMM = field.NewString(tableName, "size_mm")
	_sanokata.Bundles = field.NewInt(tableName, "bundles")
	_sanokata.Pieces = field.NewInt(tableName, "pieces")
	_sanokata.NetWeight = field.NewFloat64(tableName, "net_weight")
	_sanokata.CreatedAt = field.NewString(tableName, "created_at")
	_sanokata.UserId = field.NewInt(tableName, "user_id")
	_sanokata.TokenNo = field.NewString(tableName, "token_no")
	_sanokata.GateEntry = sanokataHasOneGateEntry{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("GateEntry", "models.GateEntry"),
		QualityReport: struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("GateEntry.QualityReport", "models.QualityReport"),
			Agent: struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.Agent", "models.Agent"),
				QualityReports: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Agent.QualityReports", "models.QualityReport"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.GateEntry", "models.GateEntry"),
			},
			Details: struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.Details", "models.QualityReportDetails"),
				ScrapTypeInfo: struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
					Details: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("GateEntry.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
					},
				},
				Report: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Details.Report", "models.QualityReport"),
				},
			},
		},
		Scrap: struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Scrap", "models.Scrap"),
			Vendor: struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.Vendor", "models.Vendors"),
				Scraps: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Scrap.Vendor.Scraps", "models.Scrap"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.GateEntry", "models.GateEntry"),
			},
			MultiUnloads: struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
				Scrap: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Scrap.MultiUnloads.Scrap", "models.Scrap"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.GateEntries", "models.GateEntry"),
			},
		},
		Thulokata: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Thulokata", "models.Thulokata"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.GateEntry", "models.GateEntry"),
			},
			Loadings: struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.Loadings", "models.ThulokataLoading"),
				Thulokata: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Thulokata.Loadings.Thulokata", "models.Thulokata"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.GateEntries", "models.GateEntry"),
			},
		},
		LoadingEntry: struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.LoadingEntry", "models.LoadingEntry"),
			Details: struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.LoadingEntry.Details", "models.LoadingEntryDetails"),
				LoadingEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.LoadingEntry.GateEntries", "models.GateEntry"),
			},
		},
		Sanokatas: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Sanokatas", "models.Sanokata"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Sanokatas.User", "models.User"),
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Sanokatas.GateEntry", "models.GateEntry"),
			},
		},
		SHooks: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.SHooks", "models.SHook"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.SHooks.GateEntry", "models.GateEntry"),
			},
		},
	}

	_sanokata.User = sanokataBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
	}

	_sanokata.fillFieldMap()

	return _sanokata
}

type sanokata struct {
	sanokataDo sanokataDo

	ALL             field.Asterisk
	Id              field.Int64
	DocumentNo      field.String
	ShippingAddress field.String
	LoadingDate     field.String
	Code            field.String
	Lot             field.String
	SizeMM          field.String
	Bundles         field.Int
	Pieces          field.Int
	NetWeight       field.Float64
	CreatedAt       field.String
	UserId          field.Int
	TokenNo         field.String
	GateEntry       sanokataHasOneGateEntry

	User sanokataBelongsToUser

	fieldMap map[string]field.Expr
}

func (s sanokata) Table(newTableName string) *sanokata {
	s.sanokataDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sanokata) As(alias string) *sanokata {
	s.sanokataDo.DO = *(s.sanokataDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sanokata) updateTableName(table string) *sanokata {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewInt64(table, "id")
	s.DocumentNo = field.NewString(table, "internal_numbering")
	s.ShippingAddress = field.NewString(table, "shipping_address")
	s.LoadingDate = field.NewString(table, "order_date")
	s.Code = field.NewString(table, "code")
	s.Lot = field.NewString(table, "lot")
	s.SizeMM = field.NewString(table, "size_mm")
	s.Bundles = field.NewInt(table, "bundles")
	s.Pieces = field.NewInt(table, "pieces")
	s.NetWeight = field.NewFloat64(table, "net_weight")
	s.CreatedAt = field.NewString(table, "created_at")
	s.UserId = field.NewInt(table, "user_id")
	s.TokenNo = field.NewString(table, "token_no")

	s.fillFieldMap()

	return s
}

func (s *sanokata) WithContext(ctx context.Context) *sanokataDo { return s.sanokataDo.WithContext(ctx) }

func (s sanokata) TableName() string { return s.sanokataDo.TableName() }

func (s sanokata) Alias() string { return s.sanokataDo.Alias() }

func (s sanokata) Columns(cols ...field.Expr) gen.Columns { return s.sanokataDo.Columns(cols...) }

func (s *sanokata) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sanokata) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 15)
	s.fieldMap["id"] = s.Id
	s.fieldMap["internal_numbering"] = s.DocumentNo
	s.fieldMap["shipping_address"] = s.ShippingAddress
	s.fieldMap["order_date"] = s.LoadingDate
	s.fieldMap["code"] = s.Code
	s.fieldMap["lot"] = s.Lot
	s.fieldMap["size_mm"] = s.SizeMM
	s.fieldMap["bundles"] = s.Bundles
	s.fieldMap["pieces"] = s.Pieces
	s.fieldMap["net_weight"] = s.NetWeight
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["user_id"] = s.UserId
	s.fieldMap["token_no"] = s.TokenNo

}

func (s sanokata) clone(db *gorm.DB) sanokata {
	s.sanokataDo.ReplaceConnPool(db.Statement.ConnPool)
	s.GateEntry.db = db.Session(&gorm.Session{Initialized: true})
	s.GateEntry.db.Statement.ConnPool = db.Statement.ConnPool
	s.User.db = db.Session(&gorm.Session{Initialized: true})
	s.User.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sanokata) replaceDB(db *gorm.DB) sanokata {
	s.sanokataDo.ReplaceDB(db)
	s.GateEntry.db = db.Session(&gorm.Session{})
	s.User.db = db.Session(&gorm.Session{})
	return s
}

type sanokataHasOneGateEntry struct {
	db *gorm.DB

	field.RelationField

	QualityReport struct {
		field.RelationField
		Agent struct {
			field.RelationField
			QualityReports struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		Details struct {
			field.RelationField
			ScrapTypeInfo struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}
			Report struct {
				field.RelationField
			}
		}
	}
	Scrap struct {
		field.RelationField
		Vendor struct {
			field.RelationField
			Scraps struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		MultiUnloads struct {
			field.RelationField
			Scrap struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Thulokata struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
		Loadings struct {
			field.RelationField
			Thulokata struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	LoadingEntry struct {
		field.RelationField
		Details struct {
			field.RelationField
			LoadingEntry struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Sanokatas struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		GateEntry struct {
			field.RelationField
		}
	}
	SHooks struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
	}
}

func (a sanokataHasOneGateEntry) Where(conds ...field.Expr) *sanokataHasOneGateEntry {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sanokataHasOneGateEntry) WithContext(ctx context.Context) *sanokataHasOneGateEntry {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sanokataHasOneGateEntry) Session(session *gorm.Session) *sanokataHasOneGateEntry {
	a.db = a.db.Session(session)
	return &a
}

func (a sanokataHasOneGateEntry) Model(m *models.Sanokata) *sanokataHasOneGateEntryTx {
	return &sanokataHasOneGateEntryTx{a.db.Model(m).Association(a.Name())}
}

func (a sanokataHasOneGateEntry) Unscoped() *sanokataHasOneGateEntry {
	a.db = a.db.Unscoped()
	return &a
}

type sanokataHasOneGateEntryTx struct{ tx *gorm.Association }

func (a sanokataHasOneGateEntryTx) Find() (result *models.GateEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a sanokataHasOneGateEntryTx) Append(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sanokataHasOneGateEntryTx) Replace(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sanokataHasOneGateEntryTx) Delete(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sanokataHasOneGateEntryTx) Clear() error {
	return a.tx.Clear()
}

func (a sanokataHasOneGateEntryTx) Count() int64 {
	return a.tx.Count()
}

func (a sanokataHasOneGateEntryTx) Unscoped() *sanokataHasOneGateEntryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sanokataBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a sanokataBelongsToUser) Where(conds ...field.Expr) *sanokataBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sanokataBelongsToUser) WithContext(ctx context.Context) *sanokataBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sanokataBelongsToUser) Session(session *gorm.Session) *sanokataBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a sanokataBelongsToUser) Model(m *models.Sanokata) *sanokataBelongsToUserTx {
	return &sanokataBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a sanokataBelongsToUser) Unscoped() *sanokataBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type sanokataBelongsToUserTx struct{ tx *gorm.Association }

func (a sanokataBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a sanokataBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sanokataBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sanokataBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sanokataBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a sanokataBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a sanokataBelongsToUserTx) Unscoped() *sanokataBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sanokataDo struct{ gen.DO }

func (s sanokataDo) Debug() *sanokataDo {
	return s.withDO(s.DO.Debug())
}

func (s sanokataDo) WithContext(ctx context.Context) *sanokataDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sanokataDo) ReadDB() *sanokataDo {
	return s.Clauses(dbresolver.Read)
}

func (s sanokataDo) WriteDB() *sanokataDo {
	return s.Clauses(dbresolver.Write)
}

func (s sanokataDo) Session(config *gorm.Session) *sanokataDo {
	return s.withDO(s.DO.Session(config))
}

func (s sanokataDo) Clauses(conds ...clause.Expression) *sanokataDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sanokataDo) Returning(value interface{}, columns ...string) *sanokataDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sanokataDo) Not(conds ...gen.Condition) *sanokataDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sanokataDo) Or(conds ...gen.Condition) *sanokataDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sanokataDo) Select(conds ...field.Expr) *sanokataDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sanokataDo) Where(conds ...gen.Condition) *sanokataDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sanokataDo) Order(conds ...field.Expr) *sanokataDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sanokataDo) Distinct(cols ...field.Expr) *sanokataDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sanokataDo) Omit(cols ...field.Expr) *sanokataDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sanokataDo) Join(table schema.Tabler, on ...field.Expr) *sanokataDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sanokataDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sanokataDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sanokataDo) RightJoin(table schema.Tabler, on ...field.Expr) *sanokataDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sanokataDo) Group(cols ...field.Expr) *sanokataDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sanokataDo) Having(conds ...gen.Condition) *sanokataDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sanokataDo) Limit(limit int) *sanokataDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sanokataDo) Offset(offset int) *sanokataDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sanokataDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sanokataDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sanokataDo) Unscoped() *sanokataDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sanokataDo) Create(values ...*models.Sanokata) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sanokataDo) CreateInBatches(values []*models.Sanokata, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sanokataDo) Save(values ...*models.Sanokata) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sanokataDo) First() (*models.Sanokata, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Sanokata), nil
	}
}

func (s sanokataDo) Take() (*models.Sanokata, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Sanokata), nil
	}
}

func (s sanokataDo) Last() (*models.Sanokata, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Sanokata), nil
	}
}

func (s sanokataDo) Find() ([]*models.Sanokata, error) {
	result, err := s.DO.Find()
	return result.([]*models.Sanokata), err
}

func (s sanokataDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Sanokata, err error) {
	buf := make([]*models.Sanokata, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sanokataDo) FindInBatches(result *[]*models.Sanokata, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sanokataDo) Attrs(attrs ...field.AssignExpr) *sanokataDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sanokataDo) Assign(attrs ...field.AssignExpr) *sanokataDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sanokataDo) Joins(fields ...field.RelationField) *sanokataDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sanokataDo) Preload(fields ...field.RelationField) *sanokataDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sanokataDo) FirstOrInit() (*models.Sanokata, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Sanokata), nil
	}
}

func (s sanokataDo) FirstOrCreate() (*models.Sanokata, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Sanokata), nil
	}
}

func (s sanokataDo) FindByPage(offset int, limit int) (result []*models.Sanokata, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sanokataDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sanokataDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sanokataDo) Delete(models ...*models.Sanokata) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sanokataDo) withDO(do gen.Dao) *sanokataDo {
	s.DO = *do.(*gen.DO)
	return s
}
