// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newScrap(db *gorm.DB, opts ...gen.DOOption) scrap {
	_scrap := scrap{}

	_scrap.scrapDo.UseDB(db, opts...)
	_scrap.scrapDo.UseModel(&models.Scrap{})

	tableName := _scrap.scrapDo.TableName()
	_scrap.ALL = field.NewAsterisk(tableName)
	_scrap.Sn = field.NewInt64(tableName, "sn")
	_scrap.DocumentNo = field.NewString(tableName, "document_no")
	_scrap.VehicleNumber = field.NewString(tableName, "vehicle_number")
	_scrap.BillNo = field.NewString(tableName, "bill_no")
	_scrap.BillDate = field.NewString(tableName, "bill_date")
	_scrap.EntryDate = field.NewString(tableName, "entry_date")
	_scrap.EntryTime = field.NewString(tableName, "entry_time")
	_scrap.PartyName = field.NewString(tableName, "party_name")
	_scrap.MaterialName = field.NewString(tableName, "material_name")
	_scrap.PartyWeight = field.NewFloat64(tableName, "party_weight")
	_scrap.SslWeight = field.NewFloat64(tableName, "ssl_weight")
	_scrap.SslFinalWeight = field.NewFloat64(tableName, "ssl_final_weight")
	_scrap.DifferenceWeight = field.NewFloat64(tableName, "difference_weight")
	_scrap.SslFinalDate = field.NewString(tableName, "ssl_final_date")
	_scrap.SslFinalTime = field.NewString(tableName, "ssl_final_time")
	_scrap.SslPrintedBy = field.NewString(tableName, "ssl_printed_by")
	_scrap.CreatedAt = field.NewString(tableName, "created_at")
	_scrap.UpdatedAt = field.NewString(tableName, "updated_at")
	_scrap.GateEntry = scrapHasOneGateEntry{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("GateEntry", "models.GateEntry"),
		QualityReport: struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("GateEntry.QualityReport", "models.QualityReport"),
			Agent: struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.Agent", "models.Agent"),
				QualityReports: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Agent.QualityReports", "models.QualityReport"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.GateEntry", "models.GateEntry"),
			},
			Details: struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.Details", "models.QualityReportDetails"),
				ScrapTypeInfo: struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
					Details: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("GateEntry.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
					},
				},
				Report: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Details.Report", "models.QualityReport"),
				},
			},
		},
		Scrap: struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Scrap", "models.Scrap"),
			Vendor: struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.Vendor", "models.Vendors"),
				Scraps: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Scrap.Vendor.Scraps", "models.Scrap"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.GateEntry", "models.GateEntry"),
			},
			MultiUnloads: struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
				Scrap: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Scrap.MultiUnloads.Scrap", "models.Scrap"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.GateEntries", "models.GateEntry"),
			},
		},
		Thulokata: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Thulokata", "models.Thulokata"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.GateEntry", "models.GateEntry"),
			},
			Loadings: struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.Loadings", "models.ThulokataLoading"),
				Thulokata: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Thulokata.Loadings.Thulokata", "models.Thulokata"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.GateEntries", "models.GateEntry"),
			},
		},
		LoadingEntry: struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.LoadingEntry", "models.LoadingEntry"),
			Details: struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.LoadingEntry.Details", "models.LoadingEntryDetails"),
				LoadingEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.LoadingEntry.GateEntries", "models.GateEntry"),
			},
		},
		Sanokatas: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Sanokatas", "models.Sanokata"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Sanokatas.User", "models.User"),
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Sanokatas.GateEntry", "models.GateEntry"),
			},
		},
		SHooks: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.SHooks", "models.SHook"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.SHooks.GateEntry", "models.GateEntry"),
			},
		},
	}

	_scrap.MultiUnloads = scrapHasManyMultiUnloads{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("MultiUnloads", "models.ScrapMultiUnload"),
		Scrap: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("MultiUnloads.Scrap", "models.Scrap"),
		},
	}

	_scrap.GateEntries = scrapHasManyGateEntries{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("GateEntries", "models.GateEntry"),
		QualityReport: struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("GateEntries.QualityReport", "models.QualityReport"),
			Agent: struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.QualityReport.Agent", "models.Agent"),
				QualityReports: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.QualityReport.Agent.QualityReports", "models.QualityReport"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.QualityReport.GateEntry", "models.GateEntry"),
			},
			Details: struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.QualityReport.Details", "models.QualityReportDetails"),
				ScrapTypeInfo: struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("GateEntries.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
					Details: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("GateEntries.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
					},
				},
				Report: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.QualityReport.Details.Report", "models.QualityReport"),
				},
			},
		},
		Scrap: struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.Scrap", "models.Scrap"),
			Vendor: struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.Vendor", "models.Vendors"),
				Scraps: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.Scrap.Vendor.Scraps", "models.Scrap"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.GateEntry", "models.GateEntry"),
			},
			MultiUnloads: struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
				Scrap: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.Scrap.MultiUnloads.Scrap", "models.Scrap"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.GateEntries", "models.GateEntry"),
			},
		},
		Thulokata: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.Thulokata", "models.Thulokata"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Thulokata.GateEntry", "models.GateEntry"),
			},
			Loadings: struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.Thulokata.Loadings", "models.ThulokataLoading"),
				Thulokata: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.Thulokata.Loadings.Thulokata", "models.Thulokata"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Thulokata.GateEntries", "models.GateEntry"),
			},
		},
		LoadingEntry: struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.LoadingEntry", "models.LoadingEntry"),
			Details: struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.LoadingEntry.Details", "models.LoadingEntryDetails"),
				LoadingEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.LoadingEntry.GateEntries", "models.GateEntry"),
			},
		},
		Sanokatas: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.Sanokatas", "models.Sanokata"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Sanokatas.User", "models.User"),
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Sanokatas.GateEntry", "models.GateEntry"),
			},
		},
		SHooks: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.SHooks", "models.SHook"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.SHooks.GateEntry", "models.GateEntry"),
			},
		},
	}

	_scrap.Vendor = scrapBelongsToVendor{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Vendor", "models.Vendors"),
		Scraps: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Vendor.Scraps", "models.Scrap"),
		},
	}

	_scrap.fillFieldMap()

	return _scrap
}

type scrap struct {
	scrapDo scrapDo

	ALL              field.Asterisk
	Sn               field.Int64
	DocumentNo       field.String
	VehicleNumber    field.String
	BillNo           field.String
	BillDate         field.String
	EntryDate        field.String
	EntryTime        field.String
	PartyName        field.String
	MaterialName     field.String
	PartyWeight      field.Float64
	SslWeight        field.Float64
	SslFinalWeight   field.Float64
	DifferenceWeight field.Float64
	SslFinalDate     field.String
	SslFinalTime     field.String
	SslPrintedBy     field.String
	CreatedAt        field.String
	UpdatedAt        field.String
	GateEntry        scrapHasOneGateEntry

	MultiUnloads scrapHasManyMultiUnloads

	GateEntries scrapHasManyGateEntries

	Vendor scrapBelongsToVendor

	fieldMap map[string]field.Expr
}

func (s scrap) Table(newTableName string) *scrap {
	s.scrapDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s scrap) As(alias string) *scrap {
	s.scrapDo.DO = *(s.scrapDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *scrap) updateTableName(table string) *scrap {
	s.ALL = field.NewAsterisk(table)
	s.Sn = field.NewInt64(table, "sn")
	s.DocumentNo = field.NewString(table, "document_no")
	s.VehicleNumber = field.NewString(table, "vehicle_number")
	s.BillNo = field.NewString(table, "bill_no")
	s.BillDate = field.NewString(table, "bill_date")
	s.EntryDate = field.NewString(table, "entry_date")
	s.EntryTime = field.NewString(table, "entry_time")
	s.PartyName = field.NewString(table, "party_name")
	s.MaterialName = field.NewString(table, "material_name")
	s.PartyWeight = field.NewFloat64(table, "party_weight")
	s.SslWeight = field.NewFloat64(table, "ssl_weight")
	s.SslFinalWeight = field.NewFloat64(table, "ssl_final_weight")
	s.DifferenceWeight = field.NewFloat64(table, "difference_weight")
	s.SslFinalDate = field.NewString(table, "ssl_final_date")
	s.SslFinalTime = field.NewString(table, "ssl_final_time")
	s.SslPrintedBy = field.NewString(table, "ssl_printed_by")
	s.CreatedAt = field.NewString(table, "created_at")
	s.UpdatedAt = field.NewString(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *scrap) WithContext(ctx context.Context) *scrapDo { return s.scrapDo.WithContext(ctx) }

func (s scrap) TableName() string { return s.scrapDo.TableName() }

func (s scrap) Alias() string { return s.scrapDo.Alias() }

func (s scrap) Columns(cols ...field.Expr) gen.Columns { return s.scrapDo.Columns(cols...) }

func (s *scrap) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *scrap) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 22)
	s.fieldMap["sn"] = s.Sn
	s.fieldMap["document_no"] = s.DocumentNo
	s.fieldMap["vehicle_number"] = s.VehicleNumber
	s.fieldMap["bill_no"] = s.BillNo
	s.fieldMap["bill_date"] = s.BillDate
	s.fieldMap["entry_date"] = s.EntryDate
	s.fieldMap["entry_time"] = s.EntryTime
	s.fieldMap["party_name"] = s.PartyName
	s.fieldMap["material_name"] = s.MaterialName
	s.fieldMap["party_weight"] = s.PartyWeight
	s.fieldMap["ssl_weight"] = s.SslWeight
	s.fieldMap["ssl_final_weight"] = s.SslFinalWeight
	s.fieldMap["difference_weight"] = s.DifferenceWeight
	s.fieldMap["ssl_final_date"] = s.SslFinalDate
	s.fieldMap["ssl_final_time"] = s.SslFinalTime
	s.fieldMap["ssl_printed_by"] = s.SslPrintedBy
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt

}

func (s scrap) clone(db *gorm.DB) scrap {
	s.scrapDo.ReplaceConnPool(db.Statement.ConnPool)
	s.GateEntry.db = db.Session(&gorm.Session{Initialized: true})
	s.GateEntry.db.Statement.ConnPool = db.Statement.ConnPool
	s.MultiUnloads.db = db.Session(&gorm.Session{Initialized: true})
	s.MultiUnloads.db.Statement.ConnPool = db.Statement.ConnPool
	s.GateEntries.db = db.Session(&gorm.Session{Initialized: true})
	s.GateEntries.db.Statement.ConnPool = db.Statement.ConnPool
	s.Vendor.db = db.Session(&gorm.Session{Initialized: true})
	s.Vendor.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s scrap) replaceDB(db *gorm.DB) scrap {
	s.scrapDo.ReplaceDB(db)
	s.GateEntry.db = db.Session(&gorm.Session{})
	s.MultiUnloads.db = db.Session(&gorm.Session{})
	s.GateEntries.db = db.Session(&gorm.Session{})
	s.Vendor.db = db.Session(&gorm.Session{})
	return s
}

type scrapHasOneGateEntry struct {
	db *gorm.DB

	field.RelationField

	QualityReport struct {
		field.RelationField
		Agent struct {
			field.RelationField
			QualityReports struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		Details struct {
			field.RelationField
			ScrapTypeInfo struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}
			Report struct {
				field.RelationField
			}
		}
	}
	Scrap struct {
		field.RelationField
		Vendor struct {
			field.RelationField
			Scraps struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		MultiUnloads struct {
			field.RelationField
			Scrap struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Thulokata struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
		Loadings struct {
			field.RelationField
			Thulokata struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	LoadingEntry struct {
		field.RelationField
		Details struct {
			field.RelationField
			LoadingEntry struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Sanokatas struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		GateEntry struct {
			field.RelationField
		}
	}
	SHooks struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
	}
}

func (a scrapHasOneGateEntry) Where(conds ...field.Expr) *scrapHasOneGateEntry {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a scrapHasOneGateEntry) WithContext(ctx context.Context) *scrapHasOneGateEntry {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a scrapHasOneGateEntry) Session(session *gorm.Session) *scrapHasOneGateEntry {
	a.db = a.db.Session(session)
	return &a
}

func (a scrapHasOneGateEntry) Model(m *models.Scrap) *scrapHasOneGateEntryTx {
	return &scrapHasOneGateEntryTx{a.db.Model(m).Association(a.Name())}
}

func (a scrapHasOneGateEntry) Unscoped() *scrapHasOneGateEntry {
	a.db = a.db.Unscoped()
	return &a
}

type scrapHasOneGateEntryTx struct{ tx *gorm.Association }

func (a scrapHasOneGateEntryTx) Find() (result *models.GateEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a scrapHasOneGateEntryTx) Append(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a scrapHasOneGateEntryTx) Replace(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a scrapHasOneGateEntryTx) Delete(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a scrapHasOneGateEntryTx) Clear() error {
	return a.tx.Clear()
}

func (a scrapHasOneGateEntryTx) Count() int64 {
	return a.tx.Count()
}

func (a scrapHasOneGateEntryTx) Unscoped() *scrapHasOneGateEntryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type scrapHasManyMultiUnloads struct {
	db *gorm.DB

	field.RelationField

	Scrap struct {
		field.RelationField
	}
}

func (a scrapHasManyMultiUnloads) Where(conds ...field.Expr) *scrapHasManyMultiUnloads {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a scrapHasManyMultiUnloads) WithContext(ctx context.Context) *scrapHasManyMultiUnloads {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a scrapHasManyMultiUnloads) Session(session *gorm.Session) *scrapHasManyMultiUnloads {
	a.db = a.db.Session(session)
	return &a
}

func (a scrapHasManyMultiUnloads) Model(m *models.Scrap) *scrapHasManyMultiUnloadsTx {
	return &scrapHasManyMultiUnloadsTx{a.db.Model(m).Association(a.Name())}
}

func (a scrapHasManyMultiUnloads) Unscoped() *scrapHasManyMultiUnloads {
	a.db = a.db.Unscoped()
	return &a
}

type scrapHasManyMultiUnloadsTx struct{ tx *gorm.Association }

func (a scrapHasManyMultiUnloadsTx) Find() (result []*models.ScrapMultiUnload, err error) {
	return result, a.tx.Find(&result)
}

func (a scrapHasManyMultiUnloadsTx) Append(values ...*models.ScrapMultiUnload) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a scrapHasManyMultiUnloadsTx) Replace(values ...*models.ScrapMultiUnload) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a scrapHasManyMultiUnloadsTx) Delete(values ...*models.ScrapMultiUnload) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a scrapHasManyMultiUnloadsTx) Clear() error {
	return a.tx.Clear()
}

func (a scrapHasManyMultiUnloadsTx) Count() int64 {
	return a.tx.Count()
}

func (a scrapHasManyMultiUnloadsTx) Unscoped() *scrapHasManyMultiUnloadsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type scrapHasManyGateEntries struct {
	db *gorm.DB

	field.RelationField

	QualityReport struct {
		field.RelationField
		Agent struct {
			field.RelationField
			QualityReports struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		Details struct {
			field.RelationField
			ScrapTypeInfo struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}
			Report struct {
				field.RelationField
			}
		}
	}
	Scrap struct {
		field.RelationField
		Vendor struct {
			field.RelationField
			Scraps struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		MultiUnloads struct {
			field.RelationField
			Scrap struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Thulokata struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
		Loadings struct {
			field.RelationField
			Thulokata struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	LoadingEntry struct {
		field.RelationField
		Details struct {
			field.RelationField
			LoadingEntry struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Sanokatas struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		GateEntry struct {
			field.RelationField
		}
	}
	SHooks struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
	}
}

func (a scrapHasManyGateEntries) Where(conds ...field.Expr) *scrapHasManyGateEntries {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a scrapHasManyGateEntries) WithContext(ctx context.Context) *scrapHasManyGateEntries {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a scrapHasManyGateEntries) Session(session *gorm.Session) *scrapHasManyGateEntries {
	a.db = a.db.Session(session)
	return &a
}

func (a scrapHasManyGateEntries) Model(m *models.Scrap) *scrapHasManyGateEntriesTx {
	return &scrapHasManyGateEntriesTx{a.db.Model(m).Association(a.Name())}
}

func (a scrapHasManyGateEntries) Unscoped() *scrapHasManyGateEntries {
	a.db = a.db.Unscoped()
	return &a
}

type scrapHasManyGateEntriesTx struct{ tx *gorm.Association }

func (a scrapHasManyGateEntriesTx) Find() (result []*models.GateEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a scrapHasManyGateEntriesTx) Append(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a scrapHasManyGateEntriesTx) Replace(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a scrapHasManyGateEntriesTx) Delete(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a scrapHasManyGateEntriesTx) Clear() error {
	return a.tx.Clear()
}

func (a scrapHasManyGateEntriesTx) Count() int64 {
	return a.tx.Count()
}

func (a scrapHasManyGateEntriesTx) Unscoped() *scrapHasManyGateEntriesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type scrapBelongsToVendor struct {
	db *gorm.DB

	field.RelationField

	Scraps struct {
		field.RelationField
	}
}

func (a scrapBelongsToVendor) Where(conds ...field.Expr) *scrapBelongsToVendor {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a scrapBelongsToVendor) WithContext(ctx context.Context) *scrapBelongsToVendor {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a scrapBelongsToVendor) Session(session *gorm.Session) *scrapBelongsToVendor {
	a.db = a.db.Session(session)
	return &a
}

func (a scrapBelongsToVendor) Model(m *models.Scrap) *scrapBelongsToVendorTx {
	return &scrapBelongsToVendorTx{a.db.Model(m).Association(a.Name())}
}

func (a scrapBelongsToVendor) Unscoped() *scrapBelongsToVendor {
	a.db = a.db.Unscoped()
	return &a
}

type scrapBelongsToVendorTx struct{ tx *gorm.Association }

func (a scrapBelongsToVendorTx) Find() (result *models.Vendors, err error) {
	return result, a.tx.Find(&result)
}

func (a scrapBelongsToVendorTx) Append(values ...*models.Vendors) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a scrapBelongsToVendorTx) Replace(values ...*models.Vendors) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a scrapBelongsToVendorTx) Delete(values ...*models.Vendors) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a scrapBelongsToVendorTx) Clear() error {
	return a.tx.Clear()
}

func (a scrapBelongsToVendorTx) Count() int64 {
	return a.tx.Count()
}

func (a scrapBelongsToVendorTx) Unscoped() *scrapBelongsToVendorTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type scrapDo struct{ gen.DO }

func (s scrapDo) Debug() *scrapDo {
	return s.withDO(s.DO.Debug())
}

func (s scrapDo) WithContext(ctx context.Context) *scrapDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s scrapDo) ReadDB() *scrapDo {
	return s.Clauses(dbresolver.Read)
}

func (s scrapDo) WriteDB() *scrapDo {
	return s.Clauses(dbresolver.Write)
}

func (s scrapDo) Session(config *gorm.Session) *scrapDo {
	return s.withDO(s.DO.Session(config))
}

func (s scrapDo) Clauses(conds ...clause.Expression) *scrapDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s scrapDo) Returning(value interface{}, columns ...string) *scrapDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s scrapDo) Not(conds ...gen.Condition) *scrapDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s scrapDo) Or(conds ...gen.Condition) *scrapDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s scrapDo) Select(conds ...field.Expr) *scrapDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s scrapDo) Where(conds ...gen.Condition) *scrapDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s scrapDo) Order(conds ...field.Expr) *scrapDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s scrapDo) Distinct(cols ...field.Expr) *scrapDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s scrapDo) Omit(cols ...field.Expr) *scrapDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s scrapDo) Join(table schema.Tabler, on ...field.Expr) *scrapDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s scrapDo) LeftJoin(table schema.Tabler, on ...field.Expr) *scrapDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s scrapDo) RightJoin(table schema.Tabler, on ...field.Expr) *scrapDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s scrapDo) Group(cols ...field.Expr) *scrapDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s scrapDo) Having(conds ...gen.Condition) *scrapDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s scrapDo) Limit(limit int) *scrapDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s scrapDo) Offset(offset int) *scrapDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s scrapDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *scrapDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s scrapDo) Unscoped() *scrapDo {
	return s.withDO(s.DO.Unscoped())
}

func (s scrapDo) Create(values ...*models.Scrap) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s scrapDo) CreateInBatches(values []*models.Scrap, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s scrapDo) Save(values ...*models.Scrap) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s scrapDo) First() (*models.Scrap, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Scrap), nil
	}
}

func (s scrapDo) Take() (*models.Scrap, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Scrap), nil
	}
}

func (s scrapDo) Last() (*models.Scrap, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Scrap), nil
	}
}

func (s scrapDo) Find() ([]*models.Scrap, error) {
	result, err := s.DO.Find()
	return result.([]*models.Scrap), err
}

func (s scrapDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Scrap, err error) {
	buf := make([]*models.Scrap, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s scrapDo) FindInBatches(result *[]*models.Scrap, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s scrapDo) Attrs(attrs ...field.AssignExpr) *scrapDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s scrapDo) Assign(attrs ...field.AssignExpr) *scrapDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s scrapDo) Joins(fields ...field.RelationField) *scrapDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s scrapDo) Preload(fields ...field.RelationField) *scrapDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s scrapDo) FirstOrInit() (*models.Scrap, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Scrap), nil
	}
}

func (s scrapDo) FirstOrCreate() (*models.Scrap, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Scrap), nil
	}
}

func (s scrapDo) FindByPage(offset int, limit int) (result []*models.Scrap, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s scrapDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s scrapDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s scrapDo) Delete(models ...*models.Scrap) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *scrapDo) withDO(do gen.Dao) *scrapDo {
	s.DO = *do.(*gen.DO)
	return s
}
