// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newSHook(db *gorm.DB, opts ...gen.DOOption) sHook {
	_sHook := sHook{}

	_sHook.sHookDo.UseDB(db, opts...)
	_sHook.sHookDo.UseModel(&models.SHook{})

	tableName := _sHook.sHookDo.TableName()
	_sHook.ALL = field.NewAsterisk(tableName)
	_sHook.Id = field.NewInt64(tableName, "id")
	_sHook.DocumentNo = field.NewString(tableName, "document_number")
	_sHook.TokenNo = field.NewString(tableName, "token_no")
	_sHook.Size = field.NewString(tableName, "size")
	_sHook.Quantity = field.NewInt(tableName, "quantity")
	_sHook.GateEntry = sHookHasOneGateEntry{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("GateEntry", "models.GateEntry"),
		QualityReport: struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("GateEntry.QualityReport", "models.QualityReport"),
			Agent: struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.Agent", "models.Agent"),
				QualityReports: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Agent.QualityReports", "models.QualityReport"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.GateEntry", "models.GateEntry"),
			},
			Details: struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.Details", "models.QualityReportDetails"),
				ScrapTypeInfo: struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
					Details: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("GateEntry.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
					},
				},
				Report: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Details.Report", "models.QualityReport"),
				},
			},
		},
		Scrap: struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Scrap", "models.Scrap"),
			Vendor: struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.Vendor", "models.Vendors"),
				Scraps: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Scrap.Vendor.Scraps", "models.Scrap"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.GateEntry", "models.GateEntry"),
			},
			MultiUnloads: struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
				Scrap: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Scrap.MultiUnloads.Scrap", "models.Scrap"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.GateEntries", "models.GateEntry"),
			},
		},
		Thulokata: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Thulokata", "models.Thulokata"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.GateEntry", "models.GateEntry"),
			},
			Loadings: struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.Loadings", "models.ThulokataLoading"),
				Thulokata: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Thulokata.Loadings.Thulokata", "models.Thulokata"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.GateEntries", "models.GateEntry"),
			},
		},
		LoadingEntry: struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.LoadingEntry", "models.LoadingEntry"),
			Details: struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.LoadingEntry.Details", "models.LoadingEntryDetails"),
				LoadingEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.LoadingEntry.GateEntries", "models.GateEntry"),
			},
		},
		Sanokatas: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Sanokatas", "models.Sanokata"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Sanokatas.User", "models.User"),
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Sanokatas.GateEntry", "models.GateEntry"),
			},
		},
		SHooks: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.SHooks", "models.SHook"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.SHooks.GateEntry", "models.GateEntry"),
			},
		},
	}

	_sHook.fillFieldMap()

	return _sHook
}

type sHook struct {
	sHookDo sHookDo

	ALL        field.Asterisk
	Id         field.Int64
	DocumentNo field.String
	TokenNo    field.String
	Size       field.String
	Quantity   field.Int
	GateEntry  sHookHasOneGateEntry

	fieldMap map[string]field.Expr
}

func (s sHook) Table(newTableName string) *sHook {
	s.sHookDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sHook) As(alias string) *sHook {
	s.sHookDo.DO = *(s.sHookDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sHook) updateTableName(table string) *sHook {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewInt64(table, "id")
	s.DocumentNo = field.NewString(table, "document_number")
	s.TokenNo = field.NewString(table, "token_no")
	s.Size = field.NewString(table, "size")
	s.Quantity = field.NewInt(table, "quantity")

	s.fillFieldMap()

	return s
}

func (s *sHook) WithContext(ctx context.Context) *sHookDo { return s.sHookDo.WithContext(ctx) }

func (s sHook) TableName() string { return s.sHookDo.TableName() }

func (s sHook) Alias() string { return s.sHookDo.Alias() }

func (s sHook) Columns(cols ...field.Expr) gen.Columns { return s.sHookDo.Columns(cols...) }

func (s *sHook) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sHook) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.Id
	s.fieldMap["document_number"] = s.DocumentNo
	s.fieldMap["token_no"] = s.TokenNo
	s.fieldMap["size"] = s.Size
	s.fieldMap["quantity"] = s.Quantity

}

func (s sHook) clone(db *gorm.DB) sHook {
	s.sHookDo.ReplaceConnPool(db.Statement.ConnPool)
	s.GateEntry.db = db.Session(&gorm.Session{Initialized: true})
	s.GateEntry.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sHook) replaceDB(db *gorm.DB) sHook {
	s.sHookDo.ReplaceDB(db)
	s.GateEntry.db = db.Session(&gorm.Session{})
	return s
}

type sHookHasOneGateEntry struct {
	db *gorm.DB

	field.RelationField

	QualityReport struct {
		field.RelationField
		Agent struct {
			field.RelationField
			QualityReports struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		Details struct {
			field.RelationField
			ScrapTypeInfo struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}
			Report struct {
				field.RelationField
			}
		}
	}
	Scrap struct {
		field.RelationField
		Vendor struct {
			field.RelationField
			Scraps struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		MultiUnloads struct {
			field.RelationField
			Scrap struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Thulokata struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
		Loadings struct {
			field.RelationField
			Thulokata struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	LoadingEntry struct {
		field.RelationField
		Details struct {
			field.RelationField
			LoadingEntry struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Sanokatas struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		GateEntry struct {
			field.RelationField
		}
	}
	SHooks struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
	}
}

func (a sHookHasOneGateEntry) Where(conds ...field.Expr) *sHookHasOneGateEntry {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sHookHasOneGateEntry) WithContext(ctx context.Context) *sHookHasOneGateEntry {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sHookHasOneGateEntry) Session(session *gorm.Session) *sHookHasOneGateEntry {
	a.db = a.db.Session(session)
	return &a
}

func (a sHookHasOneGateEntry) Model(m *models.SHook) *sHookHasOneGateEntryTx {
	return &sHookHasOneGateEntryTx{a.db.Model(m).Association(a.Name())}
}

func (a sHookHasOneGateEntry) Unscoped() *sHookHasOneGateEntry {
	a.db = a.db.Unscoped()
	return &a
}

type sHookHasOneGateEntryTx struct{ tx *gorm.Association }

func (a sHookHasOneGateEntryTx) Find() (result *models.GateEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a sHookHasOneGateEntryTx) Append(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sHookHasOneGateEntryTx) Replace(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sHookHasOneGateEntryTx) Delete(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sHookHasOneGateEntryTx) Clear() error {
	return a.tx.Clear()
}

func (a sHookHasOneGateEntryTx) Count() int64 {
	return a.tx.Count()
}

func (a sHookHasOneGateEntryTx) Unscoped() *sHookHasOneGateEntryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sHookDo struct{ gen.DO }

func (s sHookDo) Debug() *sHookDo {
	return s.withDO(s.DO.Debug())
}

func (s sHookDo) WithContext(ctx context.Context) *sHookDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sHookDo) ReadDB() *sHookDo {
	return s.Clauses(dbresolver.Read)
}

func (s sHookDo) WriteDB() *sHookDo {
	return s.Clauses(dbresolver.Write)
}

func (s sHookDo) Session(config *gorm.Session) *sHookDo {
	return s.withDO(s.DO.Session(config))
}

func (s sHookDo) Clauses(conds ...clause.Expression) *sHookDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sHookDo) Returning(value interface{}, columns ...string) *sHookDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sHookDo) Not(conds ...gen.Condition) *sHookDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sHookDo) Or(conds ...gen.Condition) *sHookDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sHookDo) Select(conds ...field.Expr) *sHookDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sHookDo) Where(conds ...gen.Condition) *sHookDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sHookDo) Order(conds ...field.Expr) *sHookDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sHookDo) Distinct(cols ...field.Expr) *sHookDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sHookDo) Omit(cols ...field.Expr) *sHookDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sHookDo) Join(table schema.Tabler, on ...field.Expr) *sHookDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sHookDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sHookDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sHookDo) RightJoin(table schema.Tabler, on ...field.Expr) *sHookDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sHookDo) Group(cols ...field.Expr) *sHookDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sHookDo) Having(conds ...gen.Condition) *sHookDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sHookDo) Limit(limit int) *sHookDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sHookDo) Offset(offset int) *sHookDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sHookDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sHookDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sHookDo) Unscoped() *sHookDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sHookDo) Create(values ...*models.SHook) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sHookDo) CreateInBatches(values []*models.SHook, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sHookDo) Save(values ...*models.SHook) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sHookDo) First() (*models.SHook, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SHook), nil
	}
}

func (s sHookDo) Take() (*models.SHook, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SHook), nil
	}
}

func (s sHookDo) Last() (*models.SHook, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SHook), nil
	}
}

func (s sHookDo) Find() ([]*models.SHook, error) {
	result, err := s.DO.Find()
	return result.([]*models.SHook), err
}

func (s sHookDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SHook, err error) {
	buf := make([]*models.SHook, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sHookDo) FindInBatches(result *[]*models.SHook, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sHookDo) Attrs(attrs ...field.AssignExpr) *sHookDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sHookDo) Assign(attrs ...field.AssignExpr) *sHookDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sHookDo) Joins(fields ...field.RelationField) *sHookDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sHookDo) Preload(fields ...field.RelationField) *sHookDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sHookDo) FirstOrInit() (*models.SHook, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SHook), nil
	}
}

func (s sHookDo) FirstOrCreate() (*models.SHook, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SHook), nil
	}
}

func (s sHookDo) FindByPage(offset int, limit int) (result []*models.SHook, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sHookDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sHookDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sHookDo) Delete(models ...*models.SHook) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sHookDo) withDO(do gen.Dao) *sHookDo {
	s.DO = *do.(*gen.DO)
	return s
}
