// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newThulokataLoading(db *gorm.DB, opts ...gen.DOOption) thulokataLoading {
	_thulokataLoading := thulokataLoading{}

	_thulokataLoading.thulokataLoadingDo.UseDB(db, opts...)
	_thulokataLoading.thulokataLoadingDo.UseModel(&models.ThulokataLoading{})

	tableName := _thulokataLoading.thulokataLoadingDo.TableName()
	_thulokataLoading.ALL = field.NewAsterisk(tableName)
	_thulokataLoading.Sn = field.NewInt64(tableName, "sn")
	_thulokataLoading.ThuloKataEntryNo = field.NewInt64(tableName, "th_entry_no")
	_thulokataLoading.Materials = field.NewString(tableName, "materials")
	_thulokataLoading.InitialWeight = field.NewFloat64(tableName, "initial_weight")
	_thulokataLoading.FinalWeight = field.NewFloat64(tableName, "final_weight")
	_thulokataLoading.NetWeight = field.NewFloat64(tableName, "net_weight")
	_thulokataLoading.OgFinalWeight = field.NewFloat64(tableName, "og_final_weight")
	_thulokataLoading.Bundles = field.NewInt(tableName, "bundles")
	_thulokataLoading.InitialDate = field.NewString(tableName, "initial_date")
	_thulokataLoading.InitialTime = field.NewString(tableName, "initial_time")
	_thulokataLoading.FinalDate = field.NewString(tableName, "final_date")
	_thulokataLoading.FinalTime = field.NewString(tableName, "final_time")
	_thulokataLoading.UserId = field.NewInt(tableName, "user_id")
	_thulokataLoading.Thulokata = thulokataLoadingBelongsToThulokata{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Thulokata", "models.Thulokata"),
		GateEntry: struct {
			field.RelationField
			QualityReport struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}
			Scrap struct {
				field.RelationField
				Vendor struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				MultiUnloads struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Thulokata struct {
				field.RelationField
			}
			LoadingEntry struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Sanokatas struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}
			SHooks struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Thulokata.GateEntry", "models.GateEntry"),
			QualityReport: struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Thulokata.GateEntry.QualityReport", "models.QualityReport"),
				Agent: struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.QualityReport.Agent", "models.Agent"),
					QualityReports: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Thulokata.GateEntry.QualityReport.Agent.QualityReports", "models.QualityReport"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.QualityReport.GateEntry", "models.GateEntry"),
				},
				Details: struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.QualityReport.Details", "models.QualityReportDetails"),
					ScrapTypeInfo: struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Thulokata.GateEntry.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
						Details: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Thulokata.GateEntry.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
						},
					},
					Report: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Thulokata.GateEntry.QualityReport.Details.Report", "models.QualityReport"),
					},
				},
			},
			Scrap: struct {
				field.RelationField
				Vendor struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				MultiUnloads struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Thulokata.GateEntry.Scrap", "models.Scrap"),
				Vendor: struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.Scrap.Vendor", "models.Vendors"),
					Scraps: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Thulokata.GateEntry.Scrap.Vendor.Scraps", "models.Scrap"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.Scrap.GateEntry", "models.GateEntry"),
				},
				MultiUnloads: struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
					Scrap: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Thulokata.GateEntry.Scrap.MultiUnloads.Scrap", "models.Scrap"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.Scrap.GateEntries", "models.GateEntry"),
				},
			},
			Thulokata: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Thulokata.GateEntry.Thulokata", "models.Thulokata"),
			},
			LoadingEntry: struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Thulokata.GateEntry.LoadingEntry", "models.LoadingEntry"),
				Details: struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.LoadingEntry.Details", "models.LoadingEntryDetails"),
					LoadingEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Thulokata.GateEntry.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.LoadingEntry.GateEntries", "models.GateEntry"),
				},
			},
			Sanokatas: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Thulokata.GateEntry.Sanokatas", "models.Sanokata"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.Sanokatas.User", "models.User"),
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.Sanokatas.GateEntry", "models.GateEntry"),
				},
			},
			SHooks: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Thulokata.GateEntry.SHooks", "models.SHook"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntry.SHooks.GateEntry", "models.GateEntry"),
				},
			},
		},
		Loadings: struct {
			field.RelationField
			Thulokata struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Thulokata.Loadings", "models.ThulokataLoading"),
			Thulokata: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Thulokata.Loadings.Thulokata", "models.Thulokata"),
			},
		},
		GateEntries: struct {
			field.RelationField
			QualityReport struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}
			Scrap struct {
				field.RelationField
				Vendor struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				MultiUnloads struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Thulokata struct {
				field.RelationField
			}
			LoadingEntry struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}
			Sanokatas struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}
			SHooks struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Thulokata.GateEntries", "models.GateEntry"),
			QualityReport: struct {
				field.RelationField
				Agent struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				Details struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Thulokata.GateEntries.QualityReport", "models.QualityReport"),
				Agent: struct {
					field.RelationField
					QualityReports struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.QualityReport.Agent", "models.Agent"),
					QualityReports: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Thulokata.GateEntries.QualityReport.Agent.QualityReports", "models.QualityReport"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.QualityReport.GateEntry", "models.GateEntry"),
				},
				Details: struct {
					field.RelationField
					ScrapTypeInfo struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}
					Report struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.QualityReport.Details", "models.QualityReportDetails"),
					ScrapTypeInfo: struct {
						field.RelationField
						Details struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Thulokata.GateEntries.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
						Details: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Thulokata.GateEntries.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
						},
					},
					Report: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Thulokata.GateEntries.QualityReport.Details.Report", "models.QualityReport"),
					},
				},
			},
			Scrap: struct {
				field.RelationField
				Vendor struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}
				GateEntry struct {
					field.RelationField
				}
				MultiUnloads struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Thulokata.GateEntries.Scrap", "models.Scrap"),
				Vendor: struct {
					field.RelationField
					Scraps struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.Scrap.Vendor", "models.Vendors"),
					Scraps: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Thulokata.GateEntries.Scrap.Vendor.Scraps", "models.Scrap"),
					},
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.Scrap.GateEntry", "models.GateEntry"),
				},
				MultiUnloads: struct {
					field.RelationField
					Scrap struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
					Scrap: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Thulokata.GateEntries.Scrap.MultiUnloads.Scrap", "models.Scrap"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.Scrap.GateEntries", "models.GateEntry"),
				},
			},
			Thulokata: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Thulokata.GateEntries.Thulokata", "models.Thulokata"),
			},
			LoadingEntry: struct {
				field.RelationField
				Details struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}
				GateEntries struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Thulokata.GateEntries.LoadingEntry", "models.LoadingEntry"),
				Details: struct {
					field.RelationField
					LoadingEntry struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.LoadingEntry.Details", "models.LoadingEntryDetails"),
					LoadingEntry: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Thulokata.GateEntries.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
					},
				},
				GateEntries: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.LoadingEntry.GateEntries", "models.GateEntry"),
				},
			},
			Sanokatas: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Thulokata.GateEntries.Sanokatas", "models.Sanokata"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.Sanokatas.User", "models.User"),
				},
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.Sanokatas.GateEntry", "models.GateEntry"),
				},
			},
			SHooks: struct {
				field.RelationField
				GateEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Thulokata.GateEntries.SHooks", "models.SHook"),
				GateEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Thulokata.GateEntries.SHooks.GateEntry", "models.GateEntry"),
				},
			},
		},
	}

	_thulokataLoading.fillFieldMap()

	return _thulokataLoading
}

type thulokataLoading struct {
	thulokataLoadingDo thulokataLoadingDo

	ALL              field.Asterisk
	Sn               field.Int64
	ThuloKataEntryNo field.Int64
	Materials        field.String
	InitialWeight    field.Float64
	FinalWeight      field.Float64
	NetWeight        field.Float64
	OgFinalWeight    field.Float64
	Bundles          field.Int
	InitialDate      field.String
	InitialTime      field.String
	FinalDate        field.String
	FinalTime        field.String
	UserId           field.Int
	Thulokata        thulokataLoadingBelongsToThulokata

	fieldMap map[string]field.Expr
}

func (t thulokataLoading) Table(newTableName string) *thulokataLoading {
	t.thulokataLoadingDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t thulokataLoading) As(alias string) *thulokataLoading {
	t.thulokataLoadingDo.DO = *(t.thulokataLoadingDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *thulokataLoading) updateTableName(table string) *thulokataLoading {
	t.ALL = field.NewAsterisk(table)
	t.Sn = field.NewInt64(table, "sn")
	t.ThuloKataEntryNo = field.NewInt64(table, "th_entry_no")
	t.Materials = field.NewString(table, "materials")
	t.InitialWeight = field.NewFloat64(table, "initial_weight")
	t.FinalWeight = field.NewFloat64(table, "final_weight")
	t.NetWeight = field.NewFloat64(table, "net_weight")
	t.OgFinalWeight = field.NewFloat64(table, "og_final_weight")
	t.Bundles = field.NewInt(table, "bundles")
	t.InitialDate = field.NewString(table, "initial_date")
	t.InitialTime = field.NewString(table, "initial_time")
	t.FinalDate = field.NewString(table, "final_date")
	t.FinalTime = field.NewString(table, "final_time")
	t.UserId = field.NewInt(table, "user_id")

	t.fillFieldMap()

	return t
}

func (t *thulokataLoading) WithContext(ctx context.Context) *thulokataLoadingDo {
	return t.thulokataLoadingDo.WithContext(ctx)
}

func (t thulokataLoading) TableName() string { return t.thulokataLoadingDo.TableName() }

func (t thulokataLoading) Alias() string { return t.thulokataLoadingDo.Alias() }

func (t thulokataLoading) Columns(cols ...field.Expr) gen.Columns {
	return t.thulokataLoadingDo.Columns(cols...)
}

func (t *thulokataLoading) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *thulokataLoading) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 14)
	t.fieldMap["sn"] = t.Sn
	t.fieldMap["th_entry_no"] = t.ThuloKataEntryNo
	t.fieldMap["materials"] = t.Materials
	t.fieldMap["initial_weight"] = t.InitialWeight
	t.fieldMap["final_weight"] = t.FinalWeight
	t.fieldMap["net_weight"] = t.NetWeight
	t.fieldMap["og_final_weight"] = t.OgFinalWeight
	t.fieldMap["bundles"] = t.Bundles
	t.fieldMap["initial_date"] = t.InitialDate
	t.fieldMap["initial_time"] = t.InitialTime
	t.fieldMap["final_date"] = t.FinalDate
	t.fieldMap["final_time"] = t.FinalTime
	t.fieldMap["user_id"] = t.UserId

}

func (t thulokataLoading) clone(db *gorm.DB) thulokataLoading {
	t.thulokataLoadingDo.ReplaceConnPool(db.Statement.ConnPool)
	t.Thulokata.db = db.Session(&gorm.Session{Initialized: true})
	t.Thulokata.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t thulokataLoading) replaceDB(db *gorm.DB) thulokataLoading {
	t.thulokataLoadingDo.ReplaceDB(db)
	t.Thulokata.db = db.Session(&gorm.Session{})
	return t
}

type thulokataLoadingBelongsToThulokata struct {
	db *gorm.DB

	field.RelationField

	GateEntry struct {
		field.RelationField
		QualityReport struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}
		Scrap struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Thulokata struct {
			field.RelationField
		}
		LoadingEntry struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Sanokatas struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}
		SHooks struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}
	}
	Loadings struct {
		field.RelationField
		Thulokata struct {
			field.RelationField
		}
	}
	GateEntries struct {
		field.RelationField
		QualityReport struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}
		Scrap struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Thulokata struct {
			field.RelationField
		}
		LoadingEntry struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}
		Sanokatas struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}
		SHooks struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}
	}
}

func (a thulokataLoadingBelongsToThulokata) Where(conds ...field.Expr) *thulokataLoadingBelongsToThulokata {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a thulokataLoadingBelongsToThulokata) WithContext(ctx context.Context) *thulokataLoadingBelongsToThulokata {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a thulokataLoadingBelongsToThulokata) Session(session *gorm.Session) *thulokataLoadingBelongsToThulokata {
	a.db = a.db.Session(session)
	return &a
}

func (a thulokataLoadingBelongsToThulokata) Model(m *models.ThulokataLoading) *thulokataLoadingBelongsToThulokataTx {
	return &thulokataLoadingBelongsToThulokataTx{a.db.Model(m).Association(a.Name())}
}

func (a thulokataLoadingBelongsToThulokata) Unscoped() *thulokataLoadingBelongsToThulokata {
	a.db = a.db.Unscoped()
	return &a
}

type thulokataLoadingBelongsToThulokataTx struct{ tx *gorm.Association }

func (a thulokataLoadingBelongsToThulokataTx) Find() (result *models.Thulokata, err error) {
	return result, a.tx.Find(&result)
}

func (a thulokataLoadingBelongsToThulokataTx) Append(values ...*models.Thulokata) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a thulokataLoadingBelongsToThulokataTx) Replace(values ...*models.Thulokata) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a thulokataLoadingBelongsToThulokataTx) Delete(values ...*models.Thulokata) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a thulokataLoadingBelongsToThulokataTx) Clear() error {
	return a.tx.Clear()
}

func (a thulokataLoadingBelongsToThulokataTx) Count() int64 {
	return a.tx.Count()
}

func (a thulokataLoadingBelongsToThulokataTx) Unscoped() *thulokataLoadingBelongsToThulokataTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type thulokataLoadingDo struct{ gen.DO }

func (t thulokataLoadingDo) Debug() *thulokataLoadingDo {
	return t.withDO(t.DO.Debug())
}

func (t thulokataLoadingDo) WithContext(ctx context.Context) *thulokataLoadingDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t thulokataLoadingDo) ReadDB() *thulokataLoadingDo {
	return t.Clauses(dbresolver.Read)
}

func (t thulokataLoadingDo) WriteDB() *thulokataLoadingDo {
	return t.Clauses(dbresolver.Write)
}

func (t thulokataLoadingDo) Session(config *gorm.Session) *thulokataLoadingDo {
	return t.withDO(t.DO.Session(config))
}

func (t thulokataLoadingDo) Clauses(conds ...clause.Expression) *thulokataLoadingDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t thulokataLoadingDo) Returning(value interface{}, columns ...string) *thulokataLoadingDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t thulokataLoadingDo) Not(conds ...gen.Condition) *thulokataLoadingDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t thulokataLoadingDo) Or(conds ...gen.Condition) *thulokataLoadingDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t thulokataLoadingDo) Select(conds ...field.Expr) *thulokataLoadingDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t thulokataLoadingDo) Where(conds ...gen.Condition) *thulokataLoadingDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t thulokataLoadingDo) Order(conds ...field.Expr) *thulokataLoadingDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t thulokataLoadingDo) Distinct(cols ...field.Expr) *thulokataLoadingDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t thulokataLoadingDo) Omit(cols ...field.Expr) *thulokataLoadingDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t thulokataLoadingDo) Join(table schema.Tabler, on ...field.Expr) *thulokataLoadingDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t thulokataLoadingDo) LeftJoin(table schema.Tabler, on ...field.Expr) *thulokataLoadingDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t thulokataLoadingDo) RightJoin(table schema.Tabler, on ...field.Expr) *thulokataLoadingDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t thulokataLoadingDo) Group(cols ...field.Expr) *thulokataLoadingDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t thulokataLoadingDo) Having(conds ...gen.Condition) *thulokataLoadingDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t thulokataLoadingDo) Limit(limit int) *thulokataLoadingDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t thulokataLoadingDo) Offset(offset int) *thulokataLoadingDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t thulokataLoadingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *thulokataLoadingDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t thulokataLoadingDo) Unscoped() *thulokataLoadingDo {
	return t.withDO(t.DO.Unscoped())
}

func (t thulokataLoadingDo) Create(values ...*models.ThulokataLoading) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t thulokataLoadingDo) CreateInBatches(values []*models.ThulokataLoading, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t thulokataLoadingDo) Save(values ...*models.ThulokataLoading) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t thulokataLoadingDo) First() (*models.ThulokataLoading, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ThulokataLoading), nil
	}
}

func (t thulokataLoadingDo) Take() (*models.ThulokataLoading, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ThulokataLoading), nil
	}
}

func (t thulokataLoadingDo) Last() (*models.ThulokataLoading, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ThulokataLoading), nil
	}
}

func (t thulokataLoadingDo) Find() ([]*models.ThulokataLoading, error) {
	result, err := t.DO.Find()
	return result.([]*models.ThulokataLoading), err
}

func (t thulokataLoadingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ThulokataLoading, err error) {
	buf := make([]*models.ThulokataLoading, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t thulokataLoadingDo) FindInBatches(result *[]*models.ThulokataLoading, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t thulokataLoadingDo) Attrs(attrs ...field.AssignExpr) *thulokataLoadingDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t thulokataLoadingDo) Assign(attrs ...field.AssignExpr) *thulokataLoadingDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t thulokataLoadingDo) Joins(fields ...field.RelationField) *thulokataLoadingDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t thulokataLoadingDo) Preload(fields ...field.RelationField) *thulokataLoadingDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t thulokataLoadingDo) FirstOrInit() (*models.ThulokataLoading, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ThulokataLoading), nil
	}
}

func (t thulokataLoadingDo) FirstOrCreate() (*models.ThulokataLoading, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ThulokataLoading), nil
	}
}

func (t thulokataLoadingDo) FindByPage(offset int, limit int) (result []*models.ThulokataLoading, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t thulokataLoadingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t thulokataLoadingDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t thulokataLoadingDo) Delete(models ...*models.ThulokataLoading) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *thulokataLoadingDo) withDO(do gen.Dao) *thulokataLoadingDo {
	t.DO = *do.(*gen.DO)
	return t
}
