// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/gatepass/models"
)

func newThulokata(db *gorm.DB, opts ...gen.DOOption) thulokata {
	_thulokata := thulokata{}

	_thulokata.thulokataDo.UseDB(db, opts...)
	_thulokata.thulokataDo.UseModel(&models.Thulokata{})

	tableName := _thulokata.thulokataDo.TableName()
	_thulokata.ALL = field.NewAsterisk(tableName)
	_thulokata.Sn = field.NewInt64(tableName, "sn")
	_thulokata.DocumentNo = field.NewString(tableName, "document_no")
	_thulokata.PartyName = field.NewString(tableName, "party_name")
	_thulokata.Materials = field.NewString(tableName, "materials")
	_thulokata.Remarks = field.NewString(tableName, "remarks")
	_thulokata.GrossWeight = field.NewFloat64(tableName, "gross_weight")
	_thulokata.TareWeight = field.NewFloat64(tableName, "tare_weight")
	_thulokata.NetWeight = field.NewFloat64(tableName, "net_weight")
	_thulokata.TareDate = field.NewString(tableName, "tare_date")
	_thulokata.TareTime = field.NewString(tableName, "tare_time")
	_thulokata.GrossDate = field.NewString(tableName, "gross_date")
	_thulokata.GrossTime = field.NewString(tableName, "gross_time")
	_thulokata.PrintedBy = field.NewString(tableName, "printed_by")
	_thulokata.GateEntry = thulokataHasOneGateEntry{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("GateEntry", "models.GateEntry"),
		QualityReport: struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("GateEntry.QualityReport", "models.QualityReport"),
			Agent: struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.Agent", "models.Agent"),
				QualityReports: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Agent.QualityReports", "models.QualityReport"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.GateEntry", "models.GateEntry"),
			},
			Details: struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.QualityReport.Details", "models.QualityReportDetails"),
				ScrapTypeInfo: struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
					Details: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("GateEntry.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
					},
				},
				Report: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.QualityReport.Details.Report", "models.QualityReport"),
				},
			},
		},
		Scrap: struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Scrap", "models.Scrap"),
			Vendor: struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.Vendor", "models.Vendors"),
				Scraps: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Scrap.Vendor.Scraps", "models.Scrap"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.GateEntry", "models.GateEntry"),
			},
			MultiUnloads: struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
				Scrap: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Scrap.MultiUnloads.Scrap", "models.Scrap"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Scrap.GateEntries", "models.GateEntry"),
			},
		},
		Thulokata: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Thulokata", "models.Thulokata"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.GateEntry", "models.GateEntry"),
			},
			Loadings: struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.Loadings", "models.ThulokataLoading"),
				Thulokata: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.Thulokata.Loadings.Thulokata", "models.Thulokata"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Thulokata.GateEntries", "models.GateEntry"),
			},
		},
		LoadingEntry: struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.LoadingEntry", "models.LoadingEntry"),
			Details: struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntry.LoadingEntry.Details", "models.LoadingEntryDetails"),
				LoadingEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntry.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.LoadingEntry.GateEntries", "models.GateEntry"),
			},
		},
		Sanokatas: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.Sanokatas", "models.Sanokata"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Sanokatas.User", "models.User"),
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.Sanokatas.GateEntry", "models.GateEntry"),
			},
		},
		SHooks: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntry.SHooks", "models.SHook"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntry.SHooks.GateEntry", "models.GateEntry"),
			},
		},
	}

	_thulokata.Loadings = thulokataHasManyLoadings{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Loadings", "models.ThulokataLoading"),
		Thulokata: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Loadings.Thulokata", "models.Thulokata"),
		},
	}

	_thulokata.GateEntries = thulokataHasManyGateEntries{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("GateEntries", "models.GateEntry"),
		QualityReport: struct {
			field.RelationField
			Agent struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			Details struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("GateEntries.QualityReport", "models.QualityReport"),
			Agent: struct {
				field.RelationField
				QualityReports struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.QualityReport.Agent", "models.Agent"),
				QualityReports: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.QualityReport.Agent.QualityReports", "models.QualityReport"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.QualityReport.GateEntry", "models.GateEntry"),
			},
			Details: struct {
				field.RelationField
				ScrapTypeInfo struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}
				Report struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.QualityReport.Details", "models.QualityReportDetails"),
				ScrapTypeInfo: struct {
					field.RelationField
					Details struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("GateEntries.QualityReport.Details.ScrapTypeInfo", "models.ScrapType"),
					Details: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("GateEntries.QualityReport.Details.ScrapTypeInfo.Details", "models.QualityReportDetails"),
					},
				},
				Report: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.QualityReport.Details.Report", "models.QualityReport"),
				},
			},
		},
		Scrap: struct {
			field.RelationField
			Vendor struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}
			GateEntry struct {
				field.RelationField
			}
			MultiUnloads struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.Scrap", "models.Scrap"),
			Vendor: struct {
				field.RelationField
				Scraps struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.Vendor", "models.Vendors"),
				Scraps: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.Scrap.Vendor.Scraps", "models.Scrap"),
				},
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.GateEntry", "models.GateEntry"),
			},
			MultiUnloads: struct {
				field.RelationField
				Scrap struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.MultiUnloads", "models.ScrapMultiUnload"),
				Scrap: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.Scrap.MultiUnloads.Scrap", "models.Scrap"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Scrap.GateEntries", "models.GateEntry"),
			},
		},
		Thulokata: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
			Loadings struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.Thulokata", "models.Thulokata"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Thulokata.GateEntry", "models.GateEntry"),
			},
			Loadings: struct {
				field.RelationField
				Thulokata struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.Thulokata.Loadings", "models.ThulokataLoading"),
				Thulokata: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.Thulokata.Loadings.Thulokata", "models.Thulokata"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Thulokata.GateEntries", "models.GateEntry"),
			},
		},
		LoadingEntry: struct {
			field.RelationField
			Details struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}
			GateEntries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.LoadingEntry", "models.LoadingEntry"),
			Details: struct {
				field.RelationField
				LoadingEntry struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("GateEntries.LoadingEntry.Details", "models.LoadingEntryDetails"),
				LoadingEntry: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("GateEntries.LoadingEntry.Details.LoadingEntry", "models.LoadingEntry"),
				},
			},
			GateEntries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.LoadingEntry.GateEntries", "models.GateEntry"),
			},
		},
		Sanokatas: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.Sanokatas", "models.Sanokata"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Sanokatas.User", "models.User"),
			},
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.Sanokatas.GateEntry", "models.GateEntry"),
			},
		},
		SHooks: struct {
			field.RelationField
			GateEntry struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("GateEntries.SHooks", "models.SHook"),
			GateEntry: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("GateEntries.SHooks.GateEntry", "models.GateEntry"),
			},
		},
	}

	_thulokata.fillFieldMap()

	return _thulokata
}

type thulokata struct {
	thulokataDo thulokataDo

	ALL         field.Asterisk
	Sn          field.Int64
	DocumentNo  field.String
	PartyName   field.String
	Materials   field.String
	Remarks     field.String
	GrossWeight field.Float64
	TareWeight  field.Float64
	NetWeight   field.Float64
	TareDate    field.String
	TareTime    field.String
	GrossDate   field.String
	GrossTime   field.String
	PrintedBy   field.String
	GateEntry   thulokataHasOneGateEntry

	Loadings thulokataHasManyLoadings

	GateEntries thulokataHasManyGateEntries

	fieldMap map[string]field.Expr
}

func (t thulokata) Table(newTableName string) *thulokata {
	t.thulokataDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t thulokata) As(alias string) *thulokata {
	t.thulokataDo.DO = *(t.thulokataDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *thulokata) updateTableName(table string) *thulokata {
	t.ALL = field.NewAsterisk(table)
	t.Sn = field.NewInt64(table, "sn")
	t.DocumentNo = field.NewString(table, "document_no")
	t.PartyName = field.NewString(table, "party_name")
	t.Materials = field.NewString(table, "materials")
	t.Remarks = field.NewString(table, "remarks")
	t.GrossWeight = field.NewFloat64(table, "gross_weight")
	t.TareWeight = field.NewFloat64(table, "tare_weight")
	t.NetWeight = field.NewFloat64(table, "net_weight")
	t.TareDate = field.NewString(table, "tare_date")
	t.TareTime = field.NewString(table, "tare_time")
	t.GrossDate = field.NewString(table, "gross_date")
	t.GrossTime = field.NewString(table, "gross_time")
	t.PrintedBy = field.NewString(table, "printed_by")

	t.fillFieldMap()

	return t
}

func (t *thulokata) WithContext(ctx context.Context) *thulokataDo {
	return t.thulokataDo.WithContext(ctx)
}

func (t thulokata) TableName() string { return t.thulokataDo.TableName() }

func (t thulokata) Alias() string { return t.thulokataDo.Alias() }

func (t thulokata) Columns(cols ...field.Expr) gen.Columns { return t.thulokataDo.Columns(cols...) }

func (t *thulokata) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *thulokata) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 16)
	t.fieldMap["sn"] = t.Sn
	t.fieldMap["document_no"] = t.DocumentNo
	t.fieldMap["party_name"] = t.PartyName
	t.fieldMap["materials"] = t.Materials
	t.fieldMap["remarks"] = t.Remarks
	t.fieldMap["gross_weight"] = t.GrossWeight
	t.fieldMap["tare_weight"] = t.TareWeight
	t.fieldMap["net_weight"] = t.NetWeight
	t.fieldMap["tare_date"] = t.TareDate
	t.fieldMap["tare_time"] = t.TareTime
	t.fieldMap["gross_date"] = t.GrossDate
	t.fieldMap["gross_time"] = t.GrossTime
	t.fieldMap["printed_by"] = t.PrintedBy

}

func (t thulokata) clone(db *gorm.DB) thulokata {
	t.thulokataDo.ReplaceConnPool(db.Statement.ConnPool)
	t.GateEntry.db = db.Session(&gorm.Session{Initialized: true})
	t.GateEntry.db.Statement.ConnPool = db.Statement.ConnPool
	t.Loadings.db = db.Session(&gorm.Session{Initialized: true})
	t.Loadings.db.Statement.ConnPool = db.Statement.ConnPool
	t.GateEntries.db = db.Session(&gorm.Session{Initialized: true})
	t.GateEntries.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t thulokata) replaceDB(db *gorm.DB) thulokata {
	t.thulokataDo.ReplaceDB(db)
	t.GateEntry.db = db.Session(&gorm.Session{})
	t.Loadings.db = db.Session(&gorm.Session{})
	t.GateEntries.db = db.Session(&gorm.Session{})
	return t
}

type thulokataHasOneGateEntry struct {
	db *gorm.DB

	field.RelationField

	QualityReport struct {
		field.RelationField
		Agent struct {
			field.RelationField
			QualityReports struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		Details struct {
			field.RelationField
			ScrapTypeInfo struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}
			Report struct {
				field.RelationField
			}
		}
	}
	Scrap struct {
		field.RelationField
		Vendor struct {
			field.RelationField
			Scraps struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		MultiUnloads struct {
			field.RelationField
			Scrap struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Thulokata struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
		Loadings struct {
			field.RelationField
			Thulokata struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	LoadingEntry struct {
		field.RelationField
		Details struct {
			field.RelationField
			LoadingEntry struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Sanokatas struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		GateEntry struct {
			field.RelationField
		}
	}
	SHooks struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
	}
}

func (a thulokataHasOneGateEntry) Where(conds ...field.Expr) *thulokataHasOneGateEntry {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a thulokataHasOneGateEntry) WithContext(ctx context.Context) *thulokataHasOneGateEntry {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a thulokataHasOneGateEntry) Session(session *gorm.Session) *thulokataHasOneGateEntry {
	a.db = a.db.Session(session)
	return &a
}

func (a thulokataHasOneGateEntry) Model(m *models.Thulokata) *thulokataHasOneGateEntryTx {
	return &thulokataHasOneGateEntryTx{a.db.Model(m).Association(a.Name())}
}

func (a thulokataHasOneGateEntry) Unscoped() *thulokataHasOneGateEntry {
	a.db = a.db.Unscoped()
	return &a
}

type thulokataHasOneGateEntryTx struct{ tx *gorm.Association }

func (a thulokataHasOneGateEntryTx) Find() (result *models.GateEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a thulokataHasOneGateEntryTx) Append(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a thulokataHasOneGateEntryTx) Replace(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a thulokataHasOneGateEntryTx) Delete(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a thulokataHasOneGateEntryTx) Clear() error {
	return a.tx.Clear()
}

func (a thulokataHasOneGateEntryTx) Count() int64 {
	return a.tx.Count()
}

func (a thulokataHasOneGateEntryTx) Unscoped() *thulokataHasOneGateEntryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type thulokataHasManyLoadings struct {
	db *gorm.DB

	field.RelationField

	Thulokata struct {
		field.RelationField
	}
}

func (a thulokataHasManyLoadings) Where(conds ...field.Expr) *thulokataHasManyLoadings {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a thulokataHasManyLoadings) WithContext(ctx context.Context) *thulokataHasManyLoadings {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a thulokataHasManyLoadings) Session(session *gorm.Session) *thulokataHasManyLoadings {
	a.db = a.db.Session(session)
	return &a
}

func (a thulokataHasManyLoadings) Model(m *models.Thulokata) *thulokataHasManyLoadingsTx {
	return &thulokataHasManyLoadingsTx{a.db.Model(m).Association(a.Name())}
}

func (a thulokataHasManyLoadings) Unscoped() *thulokataHasManyLoadings {
	a.db = a.db.Unscoped()
	return &a
}

type thulokataHasManyLoadingsTx struct{ tx *gorm.Association }

func (a thulokataHasManyLoadingsTx) Find() (result []*models.ThulokataLoading, err error) {
	return result, a.tx.Find(&result)
}

func (a thulokataHasManyLoadingsTx) Append(values ...*models.ThulokataLoading) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a thulokataHasManyLoadingsTx) Replace(values ...*models.ThulokataLoading) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a thulokataHasManyLoadingsTx) Delete(values ...*models.ThulokataLoading) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a thulokataHasManyLoadingsTx) Clear() error {
	return a.tx.Clear()
}

func (a thulokataHasManyLoadingsTx) Count() int64 {
	return a.tx.Count()
}

func (a thulokataHasManyLoadingsTx) Unscoped() *thulokataHasManyLoadingsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type thulokataHasManyGateEntries struct {
	db *gorm.DB

	field.RelationField

	QualityReport struct {
		field.RelationField
		Agent struct {
			field.RelationField
			QualityReports struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		Details struct {
			field.RelationField
			ScrapTypeInfo struct {
				field.RelationField
				Details struct {
					field.RelationField
				}
			}
			Report struct {
				field.RelationField
			}
		}
	}
	Scrap struct {
		field.RelationField
		Vendor struct {
			field.RelationField
			Scraps struct {
				field.RelationField
			}
		}
		GateEntry struct {
			field.RelationField
		}
		MultiUnloads struct {
			field.RelationField
			Scrap struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Thulokata struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
		Loadings struct {
			field.RelationField
			Thulokata struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	LoadingEntry struct {
		field.RelationField
		Details struct {
			field.RelationField
			LoadingEntry struct {
				field.RelationField
			}
		}
		GateEntries struct {
			field.RelationField
		}
	}
	Sanokatas struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		GateEntry struct {
			field.RelationField
		}
	}
	SHooks struct {
		field.RelationField
		GateEntry struct {
			field.RelationField
		}
	}
}

func (a thulokataHasManyGateEntries) Where(conds ...field.Expr) *thulokataHasManyGateEntries {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a thulokataHasManyGateEntries) WithContext(ctx context.Context) *thulokataHasManyGateEntries {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a thulokataHasManyGateEntries) Session(session *gorm.Session) *thulokataHasManyGateEntries {
	a.db = a.db.Session(session)
	return &a
}

func (a thulokataHasManyGateEntries) Model(m *models.Thulokata) *thulokataHasManyGateEntriesTx {
	return &thulokataHasManyGateEntriesTx{a.db.Model(m).Association(a.Name())}
}

func (a thulokataHasManyGateEntries) Unscoped() *thulokataHasManyGateEntries {
	a.db = a.db.Unscoped()
	return &a
}

type thulokataHasManyGateEntriesTx struct{ tx *gorm.Association }

func (a thulokataHasManyGateEntriesTx) Find() (result []*models.GateEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a thulokataHasManyGateEntriesTx) Append(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a thulokataHasManyGateEntriesTx) Replace(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a thulokataHasManyGateEntriesTx) Delete(values ...*models.GateEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a thulokataHasManyGateEntriesTx) Clear() error {
	return a.tx.Clear()
}

func (a thulokataHasManyGateEntriesTx) Count() int64 {
	return a.tx.Count()
}

func (a thulokataHasManyGateEntriesTx) Unscoped() *thulokataHasManyGateEntriesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type thulokataDo struct{ gen.DO }

func (t thulokataDo) Debug() *thulokataDo {
	return t.withDO(t.DO.Debug())
}

func (t thulokataDo) WithContext(ctx context.Context) *thulokataDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t thulokataDo) ReadDB() *thulokataDo {
	return t.Clauses(dbresolver.Read)
}

func (t thulokataDo) WriteDB() *thulokataDo {
	return t.Clauses(dbresolver.Write)
}

func (t thulokataDo) Session(config *gorm.Session) *thulokataDo {
	return t.withDO(t.DO.Session(config))
}

func (t thulokataDo) Clauses(conds ...clause.Expression) *thulokataDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t thulokataDo) Returning(value interface{}, columns ...string) *thulokataDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t thulokataDo) Not(conds ...gen.Condition) *thulokataDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t thulokataDo) Or(conds ...gen.Condition) *thulokataDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t thulokataDo) Select(conds ...field.Expr) *thulokataDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t thulokataDo) Where(conds ...gen.Condition) *thulokataDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t thulokataDo) Order(conds ...field.Expr) *thulokataDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t thulokataDo) Distinct(cols ...field.Expr) *thulokataDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t thulokataDo) Omit(cols ...field.Expr) *thulokataDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t thulokataDo) Join(table schema.Tabler, on ...field.Expr) *thulokataDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t thulokataDo) LeftJoin(table schema.Tabler, on ...field.Expr) *thulokataDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t thulokataDo) RightJoin(table schema.Tabler, on ...field.Expr) *thulokataDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t thulokataDo) Group(cols ...field.Expr) *thulokataDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t thulokataDo) Having(conds ...gen.Condition) *thulokataDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t thulokataDo) Limit(limit int) *thulokataDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t thulokataDo) Offset(offset int) *thulokataDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t thulokataDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *thulokataDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t thulokataDo) Unscoped() *thulokataDo {
	return t.withDO(t.DO.Unscoped())
}

func (t thulokataDo) Create(values ...*models.Thulokata) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t thulokataDo) CreateInBatches(values []*models.Thulokata, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t thulokataDo) Save(values ...*models.Thulokata) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t thulokataDo) First() (*models.Thulokata, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Thulokata), nil
	}
}

func (t thulokataDo) Take() (*models.Thulokata, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Thulokata), nil
	}
}

func (t thulokataDo) Last() (*models.Thulokata, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Thulokata), nil
	}
}

func (t thulokataDo) Find() ([]*models.Thulokata, error) {
	result, err := t.DO.Find()
	return result.([]*models.Thulokata), err
}

func (t thulokataDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Thulokata, err error) {
	buf := make([]*models.Thulokata, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t thulokataDo) FindInBatches(result *[]*models.Thulokata, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t thulokataDo) Attrs(attrs ...field.AssignExpr) *thulokataDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t thulokataDo) Assign(attrs ...field.AssignExpr) *thulokataDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t thulokataDo) Joins(fields ...field.RelationField) *thulokataDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t thulokataDo) Preload(fields ...field.RelationField) *thulokataDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t thulokataDo) FirstOrInit() (*models.Thulokata, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Thulokata), nil
	}
}

func (t thulokataDo) FirstOrCreate() (*models.Thulokata, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Thulokata), nil
	}
}

func (t thulokataDo) FindByPage(offset int, limit int) (result []*models.Thulokata, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t thulokataDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t thulokataDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t thulokataDo) Delete(models ...*models.Thulokata) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *thulokataDo) withDO(do gen.Dao) *thulokataDo {
	t.DO = *do.(*gen.DO)
	return t
}
