// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"ssl-custom-api/internal/app/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newApiKey(db *gorm.DB, opts ...gen.DOOption) apiKey {
	_apiKey := apiKey{}

	_apiKey.apiKeyDo.UseDB(db, opts...)
	_apiKey.apiKeyDo.UseModel(&models.ApiKey{})

	tableName := _apiKey.apiKeyDo.TableName()
	_apiKey.ALL = field.NewAsterisk(tableName)
	_apiKey.ID = field.NewField(tableName, "id")
	_apiKey.UserID = field.NewField(tableName, "user_id")
	_apiKey.Key = field.NewString(tableName, "key")
	_apiKey.User = apiKeyBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
	}

	_apiKey.fillFieldMap()

	return _apiKey
}

type apiKey struct {
	apiKeyDo apiKeyDo

	ALL    field.Asterisk
	ID     field.Field
	UserID field.Field
	Key    field.String
	User   apiKeyBelongsToUser

	fieldMap map[string]field.Expr
}

func (a apiKey) Table(newTableName string) *apiKey {
	a.apiKeyDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a apiKey) As(alias string) *apiKey {
	a.apiKeyDo.DO = *(a.apiKeyDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *apiKey) updateTableName(table string) *apiKey {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewField(table, "id")
	a.UserID = field.NewField(table, "user_id")
	a.Key = field.NewString(table, "key")

	a.fillFieldMap()

	return a
}

func (a *apiKey) WithContext(ctx context.Context) *apiKeyDo { return a.apiKeyDo.WithContext(ctx) }

func (a apiKey) TableName() string { return a.apiKeyDo.TableName() }

func (a apiKey) Alias() string { return a.apiKeyDo.Alias() }

func (a apiKey) Columns(cols ...field.Expr) gen.Columns { return a.apiKeyDo.Columns(cols...) }

func (a *apiKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *apiKey) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["key"] = a.Key

}

func (a apiKey) clone(db *gorm.DB) apiKey {
	a.apiKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	a.User.db = db.Session(&gorm.Session{Initialized: true})
	a.User.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a apiKey) replaceDB(db *gorm.DB) apiKey {
	a.apiKeyDo.ReplaceDB(db)
	a.User.db = db.Session(&gorm.Session{})
	return a
}

type apiKeyBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a apiKeyBelongsToUser) Where(conds ...field.Expr) *apiKeyBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a apiKeyBelongsToUser) WithContext(ctx context.Context) *apiKeyBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a apiKeyBelongsToUser) Session(session *gorm.Session) *apiKeyBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a apiKeyBelongsToUser) Model(m *models.ApiKey) *apiKeyBelongsToUserTx {
	return &apiKeyBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a apiKeyBelongsToUser) Unscoped() *apiKeyBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type apiKeyBelongsToUserTx struct{ tx *gorm.Association }

func (a apiKeyBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a apiKeyBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a apiKeyBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a apiKeyBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a apiKeyBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a apiKeyBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a apiKeyBelongsToUserTx) Unscoped() *apiKeyBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type apiKeyDo struct{ gen.DO }

func (a apiKeyDo) Debug() *apiKeyDo {
	return a.withDO(a.DO.Debug())
}

func (a apiKeyDo) WithContext(ctx context.Context) *apiKeyDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a apiKeyDo) ReadDB() *apiKeyDo {
	return a.Clauses(dbresolver.Read)
}

func (a apiKeyDo) WriteDB() *apiKeyDo {
	return a.Clauses(dbresolver.Write)
}

func (a apiKeyDo) Session(config *gorm.Session) *apiKeyDo {
	return a.withDO(a.DO.Session(config))
}

func (a apiKeyDo) Clauses(conds ...clause.Expression) *apiKeyDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a apiKeyDo) Returning(value interface{}, columns ...string) *apiKeyDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a apiKeyDo) Not(conds ...gen.Condition) *apiKeyDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a apiKeyDo) Or(conds ...gen.Condition) *apiKeyDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a apiKeyDo) Select(conds ...field.Expr) *apiKeyDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a apiKeyDo) Where(conds ...gen.Condition) *apiKeyDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a apiKeyDo) Order(conds ...field.Expr) *apiKeyDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a apiKeyDo) Distinct(cols ...field.Expr) *apiKeyDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a apiKeyDo) Omit(cols ...field.Expr) *apiKeyDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a apiKeyDo) Join(table schema.Tabler, on ...field.Expr) *apiKeyDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a apiKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *apiKeyDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a apiKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) *apiKeyDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a apiKeyDo) Group(cols ...field.Expr) *apiKeyDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a apiKeyDo) Having(conds ...gen.Condition) *apiKeyDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a apiKeyDo) Limit(limit int) *apiKeyDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a apiKeyDo) Offset(offset int) *apiKeyDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a apiKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *apiKeyDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a apiKeyDo) Unscoped() *apiKeyDo {
	return a.withDO(a.DO.Unscoped())
}

func (a apiKeyDo) Create(values ...*models.ApiKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a apiKeyDo) CreateInBatches(values []*models.ApiKey, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a apiKeyDo) Save(values ...*models.ApiKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a apiKeyDo) First() (*models.ApiKey, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ApiKey), nil
	}
}

func (a apiKeyDo) Take() (*models.ApiKey, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ApiKey), nil
	}
}

func (a apiKeyDo) Last() (*models.ApiKey, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ApiKey), nil
	}
}

func (a apiKeyDo) Find() ([]*models.ApiKey, error) {
	result, err := a.DO.Find()
	return result.([]*models.ApiKey), err
}

func (a apiKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ApiKey, err error) {
	buf := make([]*models.ApiKey, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a apiKeyDo) FindInBatches(result *[]*models.ApiKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a apiKeyDo) Attrs(attrs ...field.AssignExpr) *apiKeyDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a apiKeyDo) Assign(attrs ...field.AssignExpr) *apiKeyDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a apiKeyDo) Joins(fields ...field.RelationField) *apiKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a apiKeyDo) Preload(fields ...field.RelationField) *apiKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a apiKeyDo) FirstOrInit() (*models.ApiKey, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ApiKey), nil
	}
}

func (a apiKeyDo) FirstOrCreate() (*models.ApiKey, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ApiKey), nil
	}
}

func (a apiKeyDo) FindByPage(offset int, limit int) (result []*models.ApiKey, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a apiKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a apiKeyDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a apiKeyDo) Delete(models ...*models.ApiKey) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *apiKeyDo) withDO(do gen.Dao) *apiKeyDo {
	a.DO = *do.(*gen.DO)
	return a
}
