// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"ssl-custom-api/internal/app/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAPIPermission(db *gorm.DB, opts ...gen.DOOption) aPIPermission {
	_aPIPermission := aPIPermission{}

	_aPIPermission.aPIPermissionDo.UseDB(db, opts...)
	_aPIPermission.aPIPermissionDo.UseModel(&models.APIPermission{})

	tableName := _aPIPermission.aPIPermissionDo.TableName()
	_aPIPermission.ALL = field.NewAsterisk(tableName)
	_aPIPermission.ID = field.NewField(tableName, "id")
	_aPIPermission.ApiKeyID = field.NewField(tableName, "api_key_id")
	_aPIPermission.ResourceCode = field.NewString(tableName, "resource_code")
	_aPIPermission.Permission = field.NewString(tableName, "permission")
	_aPIPermission.ApiKey = aPIPermissionBelongsToApiKey{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ApiKey", "models.ApiKey"),
		User: struct {
			field.RelationField
			Role struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("ApiKey.User", "models.User"),
			Role: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ApiKey.User.Role", "models.Role"),
			},
		},
	}

	_aPIPermission.fillFieldMap()

	return _aPIPermission
}

type aPIPermission struct {
	aPIPermissionDo aPIPermissionDo

	ALL          field.Asterisk
	ID           field.Field
	ApiKeyID     field.Field
	ResourceCode field.String
	Permission   field.String
	ApiKey       aPIPermissionBelongsToApiKey

	fieldMap map[string]field.Expr
}

func (a aPIPermission) Table(newTableName string) *aPIPermission {
	a.aPIPermissionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aPIPermission) As(alias string) *aPIPermission {
	a.aPIPermissionDo.DO = *(a.aPIPermissionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aPIPermission) updateTableName(table string) *aPIPermission {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewField(table, "id")
	a.ApiKeyID = field.NewField(table, "api_key_id")
	a.ResourceCode = field.NewString(table, "resource_code")
	a.Permission = field.NewString(table, "permission")

	a.fillFieldMap()

	return a
}

func (a *aPIPermission) WithContext(ctx context.Context) *aPIPermissionDo {
	return a.aPIPermissionDo.WithContext(ctx)
}

func (a aPIPermission) TableName() string { return a.aPIPermissionDo.TableName() }

func (a aPIPermission) Alias() string { return a.aPIPermissionDo.Alias() }

func (a aPIPermission) Columns(cols ...field.Expr) gen.Columns {
	return a.aPIPermissionDo.Columns(cols...)
}

func (a *aPIPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aPIPermission) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 5)
	a.fieldMap["id"] = a.ID
	a.fieldMap["api_key_id"] = a.ApiKeyID
	a.fieldMap["resource_code"] = a.ResourceCode
	a.fieldMap["permission"] = a.Permission

}

func (a aPIPermission) clone(db *gorm.DB) aPIPermission {
	a.aPIPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	a.ApiKey.db = db.Session(&gorm.Session{Initialized: true})
	a.ApiKey.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a aPIPermission) replaceDB(db *gorm.DB) aPIPermission {
	a.aPIPermissionDo.ReplaceDB(db)
	a.ApiKey.db = db.Session(&gorm.Session{})
	return a
}

type aPIPermissionBelongsToApiKey struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		Role struct {
			field.RelationField
		}
	}
}

func (a aPIPermissionBelongsToApiKey) Where(conds ...field.Expr) *aPIPermissionBelongsToApiKey {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a aPIPermissionBelongsToApiKey) WithContext(ctx context.Context) *aPIPermissionBelongsToApiKey {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a aPIPermissionBelongsToApiKey) Session(session *gorm.Session) *aPIPermissionBelongsToApiKey {
	a.db = a.db.Session(session)
	return &a
}

func (a aPIPermissionBelongsToApiKey) Model(m *models.APIPermission) *aPIPermissionBelongsToApiKeyTx {
	return &aPIPermissionBelongsToApiKeyTx{a.db.Model(m).Association(a.Name())}
}

func (a aPIPermissionBelongsToApiKey) Unscoped() *aPIPermissionBelongsToApiKey {
	a.db = a.db.Unscoped()
	return &a
}

type aPIPermissionBelongsToApiKeyTx struct{ tx *gorm.Association }

func (a aPIPermissionBelongsToApiKeyTx) Find() (result *models.ApiKey, err error) {
	return result, a.tx.Find(&result)
}

func (a aPIPermissionBelongsToApiKeyTx) Append(values ...*models.ApiKey) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a aPIPermissionBelongsToApiKeyTx) Replace(values ...*models.ApiKey) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a aPIPermissionBelongsToApiKeyTx) Delete(values ...*models.ApiKey) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a aPIPermissionBelongsToApiKeyTx) Clear() error {
	return a.tx.Clear()
}

func (a aPIPermissionBelongsToApiKeyTx) Count() int64 {
	return a.tx.Count()
}

func (a aPIPermissionBelongsToApiKeyTx) Unscoped() *aPIPermissionBelongsToApiKeyTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type aPIPermissionDo struct{ gen.DO }

func (a aPIPermissionDo) Debug() *aPIPermissionDo {
	return a.withDO(a.DO.Debug())
}

func (a aPIPermissionDo) WithContext(ctx context.Context) *aPIPermissionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aPIPermissionDo) ReadDB() *aPIPermissionDo {
	return a.Clauses(dbresolver.Read)
}

func (a aPIPermissionDo) WriteDB() *aPIPermissionDo {
	return a.Clauses(dbresolver.Write)
}

func (a aPIPermissionDo) Session(config *gorm.Session) *aPIPermissionDo {
	return a.withDO(a.DO.Session(config))
}

func (a aPIPermissionDo) Clauses(conds ...clause.Expression) *aPIPermissionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aPIPermissionDo) Returning(value interface{}, columns ...string) *aPIPermissionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aPIPermissionDo) Not(conds ...gen.Condition) *aPIPermissionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aPIPermissionDo) Or(conds ...gen.Condition) *aPIPermissionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aPIPermissionDo) Select(conds ...field.Expr) *aPIPermissionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aPIPermissionDo) Where(conds ...gen.Condition) *aPIPermissionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aPIPermissionDo) Order(conds ...field.Expr) *aPIPermissionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aPIPermissionDo) Distinct(cols ...field.Expr) *aPIPermissionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aPIPermissionDo) Omit(cols ...field.Expr) *aPIPermissionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aPIPermissionDo) Join(table schema.Tabler, on ...field.Expr) *aPIPermissionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aPIPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *aPIPermissionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aPIPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) *aPIPermissionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aPIPermissionDo) Group(cols ...field.Expr) *aPIPermissionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aPIPermissionDo) Having(conds ...gen.Condition) *aPIPermissionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aPIPermissionDo) Limit(limit int) *aPIPermissionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aPIPermissionDo) Offset(offset int) *aPIPermissionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aPIPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *aPIPermissionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aPIPermissionDo) Unscoped() *aPIPermissionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aPIPermissionDo) Create(values ...*models.APIPermission) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aPIPermissionDo) CreateInBatches(values []*models.APIPermission, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aPIPermissionDo) Save(values ...*models.APIPermission) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aPIPermissionDo) First() (*models.APIPermission, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.APIPermission), nil
	}
}

func (a aPIPermissionDo) Take() (*models.APIPermission, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.APIPermission), nil
	}
}

func (a aPIPermissionDo) Last() (*models.APIPermission, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.APIPermission), nil
	}
}

func (a aPIPermissionDo) Find() ([]*models.APIPermission, error) {
	result, err := a.DO.Find()
	return result.([]*models.APIPermission), err
}

func (a aPIPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.APIPermission, err error) {
	buf := make([]*models.APIPermission, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aPIPermissionDo) FindInBatches(result *[]*models.APIPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aPIPermissionDo) Attrs(attrs ...field.AssignExpr) *aPIPermissionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aPIPermissionDo) Assign(attrs ...field.AssignExpr) *aPIPermissionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aPIPermissionDo) Joins(fields ...field.RelationField) *aPIPermissionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aPIPermissionDo) Preload(fields ...field.RelationField) *aPIPermissionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aPIPermissionDo) FirstOrInit() (*models.APIPermission, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.APIPermission), nil
	}
}

func (a aPIPermissionDo) FirstOrCreate() (*models.APIPermission, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.APIPermission), nil
	}
}

func (a aPIPermissionDo) FindByPage(offset int, limit int) (result []*models.APIPermission, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aPIPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aPIPermissionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aPIPermissionDo) Delete(models ...*models.APIPermission) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aPIPermissionDo) withDO(do gen.Dao) *aPIPermissionDo {
	a.DO = *do.(*gen.DO)
	return a
}
