// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ssl-custom-api/internal/app/models"
)

func newModule(db *gorm.DB, opts ...gen.DOOption) module {
	_module := module{}

	_module.moduleDo.UseDB(db, opts...)
	_module.moduleDo.UseModel(&models.Module{})

	tableName := _module.moduleDo.TableName()
	_module.ALL = field.NewAsterisk(tableName)
	_module.ID = field.NewField(tableName, "id")
	_module.Name = field.NewString(tableName, "name")
	_module.Code = field.NewString(tableName, "code")
	_module.Description = field.NewString(tableName, "description")
	_module.CreatedAt = field.NewTime(tableName, "created_at")
	_module.UpdatedAt = field.NewTime(tableName, "updated_at")

	_module.fillFieldMap()

	return _module
}

type module struct {
	moduleDo moduleDo

	ALL         field.Asterisk
	ID          field.Field
	Name        field.String
	Code        field.String
	Description field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m module) Table(newTableName string) *module {
	m.moduleDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m module) As(alias string) *module {
	m.moduleDo.DO = *(m.moduleDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *module) updateTableName(table string) *module {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewField(table, "id")
	m.Name = field.NewString(table, "name")
	m.Code = field.NewString(table, "code")
	m.Description = field.NewString(table, "description")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *module) WithContext(ctx context.Context) *moduleDo { return m.moduleDo.WithContext(ctx) }

func (m module) TableName() string { return m.moduleDo.TableName() }

func (m module) Alias() string { return m.moduleDo.Alias() }

func (m module) Columns(cols ...field.Expr) gen.Columns { return m.moduleDo.Columns(cols...) }

func (m *module) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *module) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 6)
	m.fieldMap["id"] = m.ID
	m.fieldMap["name"] = m.Name
	m.fieldMap["code"] = m.Code
	m.fieldMap["description"] = m.Description
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m module) clone(db *gorm.DB) module {
	m.moduleDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m module) replaceDB(db *gorm.DB) module {
	m.moduleDo.ReplaceDB(db)
	return m
}

type moduleDo struct{ gen.DO }

func (m moduleDo) Debug() *moduleDo {
	return m.withDO(m.DO.Debug())
}

func (m moduleDo) WithContext(ctx context.Context) *moduleDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m moduleDo) ReadDB() *moduleDo {
	return m.Clauses(dbresolver.Read)
}

func (m moduleDo) WriteDB() *moduleDo {
	return m.Clauses(dbresolver.Write)
}

func (m moduleDo) Session(config *gorm.Session) *moduleDo {
	return m.withDO(m.DO.Session(config))
}

func (m moduleDo) Clauses(conds ...clause.Expression) *moduleDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m moduleDo) Returning(value interface{}, columns ...string) *moduleDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m moduleDo) Not(conds ...gen.Condition) *moduleDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m moduleDo) Or(conds ...gen.Condition) *moduleDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m moduleDo) Select(conds ...field.Expr) *moduleDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m moduleDo) Where(conds ...gen.Condition) *moduleDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m moduleDo) Order(conds ...field.Expr) *moduleDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m moduleDo) Distinct(cols ...field.Expr) *moduleDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m moduleDo) Omit(cols ...field.Expr) *moduleDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m moduleDo) Join(table schema.Tabler, on ...field.Expr) *moduleDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m moduleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *moduleDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m moduleDo) RightJoin(table schema.Tabler, on ...field.Expr) *moduleDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m moduleDo) Group(cols ...field.Expr) *moduleDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m moduleDo) Having(conds ...gen.Condition) *moduleDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m moduleDo) Limit(limit int) *moduleDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m moduleDo) Offset(offset int) *moduleDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m moduleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *moduleDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m moduleDo) Unscoped() *moduleDo {
	return m.withDO(m.DO.Unscoped())
}

func (m moduleDo) Create(values ...*models.Module) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m moduleDo) CreateInBatches(values []*models.Module, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m moduleDo) Save(values ...*models.Module) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m moduleDo) First() (*models.Module, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Module), nil
	}
}

func (m moduleDo) Take() (*models.Module, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Module), nil
	}
}

func (m moduleDo) Last() (*models.Module, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Module), nil
	}
}

func (m moduleDo) Find() ([]*models.Module, error) {
	result, err := m.DO.Find()
	return result.([]*models.Module), err
}

func (m moduleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Module, err error) {
	buf := make([]*models.Module, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m moduleDo) FindInBatches(result *[]*models.Module, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m moduleDo) Attrs(attrs ...field.AssignExpr) *moduleDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m moduleDo) Assign(attrs ...field.AssignExpr) *moduleDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m moduleDo) Joins(fields ...field.RelationField) *moduleDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m moduleDo) Preload(fields ...field.RelationField) *moduleDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m moduleDo) FirstOrInit() (*models.Module, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Module), nil
	}
}

func (m moduleDo) FirstOrCreate() (*models.Module, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Module), nil
	}
}

func (m moduleDo) FindByPage(offset int, limit int) (result []*models.Module, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m moduleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m moduleDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m moduleDo) Delete(models ...*models.Module) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *moduleDo) withDO(do gen.Dao) *moduleDo {
	m.DO = *do.(*gen.DO)
	return m
}
