// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"ssl-custom-api/internal/app/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newResource(db *gorm.DB, opts ...gen.DOOption) resource {
	_resource := resource{}

	_resource.resourceDo.UseDB(db, opts...)
	_resource.resourceDo.UseModel(&models.Resource{})

	tableName := _resource.resourceDo.TableName()
	_resource.ALL = field.NewAsterisk(tableName)
	_resource.ID = field.NewField(tableName, "id")
	_resource.ModuleID = field.NewField(tableName, "module_id")
	_resource.Name = field.NewString(tableName, "name")
	_resource.Code = field.NewString(tableName, "code")
	_resource.Description = field.NewString(tableName, "description")
	_resource.Module = resourceBelongsToModule{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Module", "models.Module"),
	}

	_resource.fillFieldMap()

	return _resource
}

type resource struct {
	resourceDo resourceDo

	ALL         field.Asterisk
	ID          field.Field
	ModuleID    field.Field
	Name        field.String
	Code        field.String
	Description field.String
	Module      resourceBelongsToModule

	fieldMap map[string]field.Expr
}

func (r resource) Table(newTableName string) *resource {
	r.resourceDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resource) As(alias string) *resource {
	r.resourceDo.DO = *(r.resourceDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resource) updateTableName(table string) *resource {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewField(table, "id")
	r.ModuleID = field.NewField(table, "module_id")
	r.Name = field.NewString(table, "name")
	r.Code = field.NewString(table, "code")
	r.Description = field.NewString(table, "description")

	r.fillFieldMap()

	return r
}

func (r *resource) WithContext(ctx context.Context) *resourceDo { return r.resourceDo.WithContext(ctx) }

func (r resource) TableName() string { return r.resourceDo.TableName() }

func (r resource) Alias() string { return r.resourceDo.Alias() }

func (r resource) Columns(cols ...field.Expr) gen.Columns { return r.resourceDo.Columns(cols...) }

func (r *resource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resource) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["module_id"] = r.ModuleID
	r.fieldMap["name"] = r.Name
	r.fieldMap["code"] = r.Code
	r.fieldMap["description"] = r.Description

}

func (r resource) clone(db *gorm.DB) resource {
	r.resourceDo.ReplaceConnPool(db.Statement.ConnPool)
	r.Module.db = db.Session(&gorm.Session{Initialized: true})
	r.Module.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r resource) replaceDB(db *gorm.DB) resource {
	r.resourceDo.ReplaceDB(db)
	r.Module.db = db.Session(&gorm.Session{})
	return r
}

type resourceBelongsToModule struct {
	db *gorm.DB

	field.RelationField
}

func (a resourceBelongsToModule) Where(conds ...field.Expr) *resourceBelongsToModule {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a resourceBelongsToModule) WithContext(ctx context.Context) *resourceBelongsToModule {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a resourceBelongsToModule) Session(session *gorm.Session) *resourceBelongsToModule {
	a.db = a.db.Session(session)
	return &a
}

func (a resourceBelongsToModule) Model(m *models.Resource) *resourceBelongsToModuleTx {
	return &resourceBelongsToModuleTx{a.db.Model(m).Association(a.Name())}
}

func (a resourceBelongsToModule) Unscoped() *resourceBelongsToModule {
	a.db = a.db.Unscoped()
	return &a
}

type resourceBelongsToModuleTx struct{ tx *gorm.Association }

func (a resourceBelongsToModuleTx) Find() (result *models.Module, err error) {
	return result, a.tx.Find(&result)
}

func (a resourceBelongsToModuleTx) Append(values ...*models.Module) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a resourceBelongsToModuleTx) Replace(values ...*models.Module) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a resourceBelongsToModuleTx) Delete(values ...*models.Module) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a resourceBelongsToModuleTx) Clear() error {
	return a.tx.Clear()
}

func (a resourceBelongsToModuleTx) Count() int64 {
	return a.tx.Count()
}

func (a resourceBelongsToModuleTx) Unscoped() *resourceBelongsToModuleTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type resourceDo struct{ gen.DO }

func (r resourceDo) Debug() *resourceDo {
	return r.withDO(r.DO.Debug())
}

func (r resourceDo) WithContext(ctx context.Context) *resourceDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resourceDo) ReadDB() *resourceDo {
	return r.Clauses(dbresolver.Read)
}

func (r resourceDo) WriteDB() *resourceDo {
	return r.Clauses(dbresolver.Write)
}

func (r resourceDo) Session(config *gorm.Session) *resourceDo {
	return r.withDO(r.DO.Session(config))
}

func (r resourceDo) Clauses(conds ...clause.Expression) *resourceDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resourceDo) Returning(value interface{}, columns ...string) *resourceDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resourceDo) Not(conds ...gen.Condition) *resourceDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resourceDo) Or(conds ...gen.Condition) *resourceDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resourceDo) Select(conds ...field.Expr) *resourceDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resourceDo) Where(conds ...gen.Condition) *resourceDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resourceDo) Order(conds ...field.Expr) *resourceDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resourceDo) Distinct(cols ...field.Expr) *resourceDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resourceDo) Omit(cols ...field.Expr) *resourceDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resourceDo) Join(table schema.Tabler, on ...field.Expr) *resourceDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *resourceDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resourceDo) RightJoin(table schema.Tabler, on ...field.Expr) *resourceDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resourceDo) Group(cols ...field.Expr) *resourceDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resourceDo) Having(conds ...gen.Condition) *resourceDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resourceDo) Limit(limit int) *resourceDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resourceDo) Offset(offset int) *resourceDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *resourceDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resourceDo) Unscoped() *resourceDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resourceDo) Create(values ...*models.Resource) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resourceDo) CreateInBatches(values []*models.Resource, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resourceDo) Save(values ...*models.Resource) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resourceDo) First() (*models.Resource, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Resource), nil
	}
}

func (r resourceDo) Take() (*models.Resource, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Resource), nil
	}
}

func (r resourceDo) Last() (*models.Resource, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Resource), nil
	}
}

func (r resourceDo) Find() ([]*models.Resource, error) {
	result, err := r.DO.Find()
	return result.([]*models.Resource), err
}

func (r resourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Resource, err error) {
	buf := make([]*models.Resource, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resourceDo) FindInBatches(result *[]*models.Resource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resourceDo) Attrs(attrs ...field.AssignExpr) *resourceDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resourceDo) Assign(attrs ...field.AssignExpr) *resourceDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resourceDo) Joins(fields ...field.RelationField) *resourceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resourceDo) Preload(fields ...field.RelationField) *resourceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resourceDo) FirstOrInit() (*models.Resource, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Resource), nil
	}
}

func (r resourceDo) FirstOrCreate() (*models.Resource, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Resource), nil
	}
}

func (r resourceDo) FindByPage(offset int, limit int) (result []*models.Resource, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resourceDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resourceDo) Delete(models ...*models.Resource) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resourceDo) withDO(do gen.Dao) *resourceDo {
	r.DO = *do.(*gen.DO)
	return r
}
