// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"ssl-custom-api/internal/app/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newUserModulePermission(db *gorm.DB, opts ...gen.DOOption) userModulePermission {
	_userModulePermission := userModulePermission{}

	_userModulePermission.userModulePermissionDo.UseDB(db, opts...)
	_userModulePermission.userModulePermissionDo.UseModel(&models.UserModulePermission{})

	tableName := _userModulePermission.userModulePermissionDo.TableName()
	_userModulePermission.ALL = field.NewAsterisk(tableName)
	_userModulePermission.ID = field.NewField(tableName, "id")
	_userModulePermission.UserID = field.NewField(tableName, "user_id")
	_userModulePermission.ModuleID = field.NewField(tableName, "module_id")
	_userModulePermission.Permission = field.NewString(tableName, "permission")
	_userModulePermission.User = userModulePermissionBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
		Role: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.Role", "models.Role"),
		},
	}

	_userModulePermission.Module = userModulePermissionBelongsToModule{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Module", "models.Module"),
	}

	_userModulePermission.fillFieldMap()

	return _userModulePermission
}

type userModulePermission struct {
	userModulePermissionDo userModulePermissionDo

	ALL        field.Asterisk
	ID         field.Field
	UserID     field.Field
	ModuleID   field.Field
	Permission field.String
	User       userModulePermissionBelongsToUser

	Module userModulePermissionBelongsToModule

	fieldMap map[string]field.Expr
}

func (u userModulePermission) Table(newTableName string) *userModulePermission {
	u.userModulePermissionDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userModulePermission) As(alias string) *userModulePermission {
	u.userModulePermissionDo.DO = *(u.userModulePermissionDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userModulePermission) updateTableName(table string) *userModulePermission {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewField(table, "id")
	u.UserID = field.NewField(table, "user_id")
	u.ModuleID = field.NewField(table, "module_id")
	u.Permission = field.NewString(table, "permission")

	u.fillFieldMap()

	return u
}

func (u *userModulePermission) WithContext(ctx context.Context) *userModulePermissionDo {
	return u.userModulePermissionDo.WithContext(ctx)
}

func (u userModulePermission) TableName() string { return u.userModulePermissionDo.TableName() }

func (u userModulePermission) Alias() string { return u.userModulePermissionDo.Alias() }

func (u userModulePermission) Columns(cols ...field.Expr) gen.Columns {
	return u.userModulePermissionDo.Columns(cols...)
}

func (u *userModulePermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userModulePermission) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["module_id"] = u.ModuleID
	u.fieldMap["permission"] = u.Permission

}

func (u userModulePermission) clone(db *gorm.DB) userModulePermission {
	u.userModulePermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	u.User.db = db.Session(&gorm.Session{Initialized: true})
	u.User.db.Statement.ConnPool = db.Statement.ConnPool
	u.Module.db = db.Session(&gorm.Session{Initialized: true})
	u.Module.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u userModulePermission) replaceDB(db *gorm.DB) userModulePermission {
	u.userModulePermissionDo.ReplaceDB(db)
	u.User.db = db.Session(&gorm.Session{})
	u.Module.db = db.Session(&gorm.Session{})
	return u
}

type userModulePermissionBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	Role struct {
		field.RelationField
	}
}

func (a userModulePermissionBelongsToUser) Where(conds ...field.Expr) *userModulePermissionBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userModulePermissionBelongsToUser) WithContext(ctx context.Context) *userModulePermissionBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userModulePermissionBelongsToUser) Session(session *gorm.Session) *userModulePermissionBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a userModulePermissionBelongsToUser) Model(m *models.UserModulePermission) *userModulePermissionBelongsToUserTx {
	return &userModulePermissionBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a userModulePermissionBelongsToUser) Unscoped() *userModulePermissionBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type userModulePermissionBelongsToUserTx struct{ tx *gorm.Association }

func (a userModulePermissionBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a userModulePermissionBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userModulePermissionBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userModulePermissionBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userModulePermissionBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a userModulePermissionBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a userModulePermissionBelongsToUserTx) Unscoped() *userModulePermissionBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userModulePermissionBelongsToModule struct {
	db *gorm.DB

	field.RelationField
}

func (a userModulePermissionBelongsToModule) Where(conds ...field.Expr) *userModulePermissionBelongsToModule {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userModulePermissionBelongsToModule) WithContext(ctx context.Context) *userModulePermissionBelongsToModule {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userModulePermissionBelongsToModule) Session(session *gorm.Session) *userModulePermissionBelongsToModule {
	a.db = a.db.Session(session)
	return &a
}

func (a userModulePermissionBelongsToModule) Model(m *models.UserModulePermission) *userModulePermissionBelongsToModuleTx {
	return &userModulePermissionBelongsToModuleTx{a.db.Model(m).Association(a.Name())}
}

func (a userModulePermissionBelongsToModule) Unscoped() *userModulePermissionBelongsToModule {
	a.db = a.db.Unscoped()
	return &a
}

type userModulePermissionBelongsToModuleTx struct{ tx *gorm.Association }

func (a userModulePermissionBelongsToModuleTx) Find() (result *models.Module, err error) {
	return result, a.tx.Find(&result)
}

func (a userModulePermissionBelongsToModuleTx) Append(values ...*models.Module) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userModulePermissionBelongsToModuleTx) Replace(values ...*models.Module) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userModulePermissionBelongsToModuleTx) Delete(values ...*models.Module) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userModulePermissionBelongsToModuleTx) Clear() error {
	return a.tx.Clear()
}

func (a userModulePermissionBelongsToModuleTx) Count() int64 {
	return a.tx.Count()
}

func (a userModulePermissionBelongsToModuleTx) Unscoped() *userModulePermissionBelongsToModuleTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userModulePermissionDo struct{ gen.DO }

func (u userModulePermissionDo) Debug() *userModulePermissionDo {
	return u.withDO(u.DO.Debug())
}

func (u userModulePermissionDo) WithContext(ctx context.Context) *userModulePermissionDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userModulePermissionDo) ReadDB() *userModulePermissionDo {
	return u.Clauses(dbresolver.Read)
}

func (u userModulePermissionDo) WriteDB() *userModulePermissionDo {
	return u.Clauses(dbresolver.Write)
}

func (u userModulePermissionDo) Session(config *gorm.Session) *userModulePermissionDo {
	return u.withDO(u.DO.Session(config))
}

func (u userModulePermissionDo) Clauses(conds ...clause.Expression) *userModulePermissionDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userModulePermissionDo) Returning(value interface{}, columns ...string) *userModulePermissionDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userModulePermissionDo) Not(conds ...gen.Condition) *userModulePermissionDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userModulePermissionDo) Or(conds ...gen.Condition) *userModulePermissionDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userModulePermissionDo) Select(conds ...field.Expr) *userModulePermissionDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userModulePermissionDo) Where(conds ...gen.Condition) *userModulePermissionDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userModulePermissionDo) Order(conds ...field.Expr) *userModulePermissionDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userModulePermissionDo) Distinct(cols ...field.Expr) *userModulePermissionDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userModulePermissionDo) Omit(cols ...field.Expr) *userModulePermissionDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userModulePermissionDo) Join(table schema.Tabler, on ...field.Expr) *userModulePermissionDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userModulePermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userModulePermissionDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userModulePermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) *userModulePermissionDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userModulePermissionDo) Group(cols ...field.Expr) *userModulePermissionDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userModulePermissionDo) Having(conds ...gen.Condition) *userModulePermissionDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userModulePermissionDo) Limit(limit int) *userModulePermissionDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userModulePermissionDo) Offset(offset int) *userModulePermissionDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userModulePermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userModulePermissionDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userModulePermissionDo) Unscoped() *userModulePermissionDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userModulePermissionDo) Create(values ...*models.UserModulePermission) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userModulePermissionDo) CreateInBatches(values []*models.UserModulePermission, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userModulePermissionDo) Save(values ...*models.UserModulePermission) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userModulePermissionDo) First() (*models.UserModulePermission, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserModulePermission), nil
	}
}

func (u userModulePermissionDo) Take() (*models.UserModulePermission, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserModulePermission), nil
	}
}

func (u userModulePermissionDo) Last() (*models.UserModulePermission, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserModulePermission), nil
	}
}

func (u userModulePermissionDo) Find() ([]*models.UserModulePermission, error) {
	result, err := u.DO.Find()
	return result.([]*models.UserModulePermission), err
}

func (u userModulePermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserModulePermission, err error) {
	buf := make([]*models.UserModulePermission, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userModulePermissionDo) FindInBatches(result *[]*models.UserModulePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userModulePermissionDo) Attrs(attrs ...field.AssignExpr) *userModulePermissionDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userModulePermissionDo) Assign(attrs ...field.AssignExpr) *userModulePermissionDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userModulePermissionDo) Joins(fields ...field.RelationField) *userModulePermissionDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userModulePermissionDo) Preload(fields ...field.RelationField) *userModulePermissionDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userModulePermissionDo) FirstOrInit() (*models.UserModulePermission, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserModulePermission), nil
	}
}

func (u userModulePermissionDo) FirstOrCreate() (*models.UserModulePermission, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserModulePermission), nil
	}
}

func (u userModulePermissionDo) FindByPage(offset int, limit int) (result []*models.UserModulePermission, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userModulePermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userModulePermissionDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userModulePermissionDo) Delete(models ...*models.UserModulePermission) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userModulePermissionDo) withDO(do gen.Dao) *userModulePermissionDo {
	u.DO = *do.(*gen.DO)
	return u
}
